refactor(cluster): improve scylla.yaml patching
scylladb/scylla-cluster-tests pull request #2524
Opened 2020-08-18 09:20 UTC by enaydanov

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

2020-08-19 19:26 UTC, fruch approved these changes
I liked the idea, simplify it alot

2020-08-24 11:23 UTC, bentsi commented on sdcm/cluster.py
> +    def update_scylla_yaml(self, path=SCYLLA_YAML_PATH):
`update_scylla_yaml` - > `scylla_yaml_remote`| `remote_scylla_yaml`

2020-08-24 11:23 UTC, bentsi requested changes
please address small comment

2020-08-25 04:23 UTC, enaydanov commented on sdcm/cluster.py
> +    def update_scylla_yaml(self, path=SCYLLA_YAML_PATH):
done

2020-08-25 07:34 UTC, bentsi approved these changes

2020-08-25 07:37 UTC, merged