fix(killscylla): wait_db_down has too large wait
scylladb/scylla-cluster-tests pull request #2560
Opened 2020-08-27 06:20 UTC by fgelcer

the function wait_db_down had too large wait between
the tries, so we missed the time window where
the port stopped replying, and the test got stuck
on waiting for db down, when it was already up.
Reducing the time between tries will give us better
coverage for the time the port stops listening

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2020-08-27 07:14 UTC, aleksbykov approved these changes
LGTM, 
Small comments, name of new parameter is not very informative, maybe some another name: check_interval, interval,

2020-08-27 07:17 UTC, fgelcer commented
> LGTM,
> Small comments, name of new parameter is not very informative, maybe some another name: check_interval, interval,

I agree the name is not very informative, but this is the name that the function wait_for uses

2020-08-27 10:27 UTC, bentsi requested changes
@fgelcer if the argument has a bad name in called functions that doesn't mean that you need to continue the "bad naming" and use it everywhere...
Please change to `check_interval` as @aleksbykov suggested

2020-08-27 10:50 UTC, fgelcer commented
> @fgelcer if the argument has a bad name in called functions that doesn't mean that you need to continue the "bad naming" and use it everywhere...
> Please change to `check_interval` as @aleksbykov suggested

done

2020-08-27 11:09 UTC, aleksbykov approved these changes
LGTM

2020-08-30 11:37 UTC, roydahan commented on sdcm/nemesis.py
> +        self.target_node.wait_db_down(check_interval=5)
I think it should be even less than 5.

2020-08-30 11:37 UTC, roydahan requested changes

2020-08-30 11:37 UTC, roydahan commented on sdcm/nemesis.py
> +        self.target_node.wait_db_down(check_interval=5)
maybe even 2 seconds.

2020-08-30 11:42 UTC, fgelcer commented on sdcm/nemesis.py
> +        self.target_node.wait_db_down(check_interval=5)
reducing to 2 seconds.

2020-08-31 22:30 UTC, bentsi approved these changes

2020-08-31 22:31 UTC, merged