fix(replacement node with public): replacement node procedure fix when ip_ssh_connections is public
scylladb/scylla-cluster-tests pull request #2619
Opened 2020-09-06 16:33 UTC by juliayakovlev

If disrupt_restart_then_repair_node nemesis is run with ip_ssh_connections='public'
replacement node procedure should be initiated also, not like for private

[Task](https://trello.com/c/X1uyyhS6/2316-change-disruptrestartthenrepairnode-nemesis-to-be-able-to-run-it-when-ipsshconnectionspublic)

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2020-09-06 18:37 UTC, fruch requested changes
This is not correct
Should be `self.ip_address` it has all the needed logic to select the correct address

2020-09-06 22:14 UTC, bentsi commented
@juliayakovlev as Israel commented you need to use `self.ip_address` otherwise, this won't work when private network IPs are used.

2020-09-07 06:35 UTC, juliayakovlev commented
@bentsi @fruch
Changed

2020-09-07 06:37 UTC, fruch approved these changes
LGTM

2020-09-07 06:39 UTC, fruch commented
@juliayakovlev what about backports ?, since it just for debugging purposes I'm not sure we need to backport or not.

2020-09-07 06:48 UTC, juliayakovlev commented
> @juliayakovlev what about backports ?, since it just for debugging purposes I'm not sure we need to backport or not.

I also not think that we need backport

2020-09-07 06:58 UTC, merged