feature(scylla-bench refactor): refactor usage of scylla-bench
scylladb/scylla-cluster-tests pull request #2796
Opened 2020-10-15 10:16 UTC by juliayakovlev

Move the implementation of scylla-bench usage to it's own file.
Read the output and supply stats for Prometheus.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2020-10-15 20:36 UTC, fruch commented on sdcm/loader.py
> +class ScyllaBenchStressExported(StressExporter):
```suggestion
class ScyllaBenchStressExporter(StressExporter):
```

2020-10-15 20:40 UTC, fruch commented
How about doing the extra mile and putting it under docker while changing this ? Or this is plan in next steps ?

2020-10-18 06:25 UTC, juliayakovlev commented
> How about doing the extra mile and putting it under docker while changing this ? Or this is plan in next steps ?

There is separate task for docker< I think. It's not the part of this task

2020-10-18 06:28 UTC, juliayakovlev commented on sdcm/loader.py
> +class ScyllaBenchStressExported(StressExporter):
thanks. fixed

2020-11-06 10:03 UTC, enaydanov requested changes

2020-11-06 10:03 UTC, enaydanov commented on sdcm/utils/common.py
> +        metric_converted = float(metric.rstrip('ms'))
Can it raise `ValueError` too?

2020-11-08 09:50 UTC, bentsi commented on sdcm/scylla_bench_thread.py
> +# Copyright (c) 2019 ScyllaDB
fix preamble

2020-11-08 09:52 UTC, bentsi commented on sdcm/sct_events.py
> +            f"end={self.end} description={self.description} updated={self.updated} state={self.state} "\
same here

2020-11-08 09:54 UTC, bentsi commented on sdcm/loader.py
> +    @abc.abstractmethod
better "@abstractmethod"

2020-11-08 13:18 UTC, juliayakovlev commented on sdcm/loader.py
> +    def __init__(self, instance_name, metrics, stress_operation, stress_log_filename, loader_idx, cpu_idx=1):  # pylint: disable=too-many-arguments
done

2020-11-08 13:18 UTC, juliayakovlev commented on sdcm/loader.py
> +    def set_metric(self, name, value) -> None:
done

2020-11-08 13:19 UTC, juliayakovlev commented on sdcm/loader.py
> +                errors = int(cols[self.metrics_positions.errors])
changed

2020-11-08 13:19 UTC, juliayakovlev commented on sdcm/loader.py
> +        line_splitted = line.split()
fixed

2020-11-08 13:19 UTC, juliayakovlev commented on sdcm/loader.py
> +        except:
changed

2020-11-08 13:20 UTC, juliayakovlev commented on sdcm/loader.py
> +        return True if not 'total,' in line else False
fixed

2020-11-08 13:20 UTC, juliayakovlev commented on sdcm/loader.py
> +            _ = float(line_splitted[0].rstrip('s'))
changed

2020-11-08 13:20 UTC, juliayakovlev commented on sdcm/sct_events.py
> +            f"{self.line}"
done

2020-11-08 13:20 UTC, juliayakovlev commented on sdcm/scylla_bench_thread.py
> +from __future__ import print_function
removed

2020-11-08 13:21 UTC, juliayakovlev commented on sdcm/utils/common.py
> +        metric_converted = float(metric.rstrip('µs')) / 1000
fixed

2020-11-08 13:21 UTC, juliayakovlev commented on sdcm/utils/common.py
> +        metric_converted = float(metric.rstrip('ms'))
done

2020-11-08 13:21 UTC, juliayakovlev commented on sdcm/scylla_bench_thread.py
> +# Copyright (c) 2019 ScyllaDB
fixed

2020-11-08 13:21 UTC, juliayakovlev commented on sdcm/sct_events.py
> +            f"end={self.end} description={self.description} updated={self.updated} state={self.state} "\
done

2020-11-08 13:21 UTC, juliayakovlev commented on sdcm/loader.py
> +    @abc.abstractmethod
fixed

2020-11-08 16:11 UTC, bentsi commented on sdcm/tester.py
> +        results = queue.get_stress_results_bench()
??? looks strange

2020-11-08 16:41 UTC, bentsi approved these changes

2020-11-08 16:49 UTC, bentsi commented on sdcm/tester.py
> +        results = queue.get_stress_results_bench()
the name is misleading, but as per our conversation, it is used all over the code. So let's keep it as is...

2020-11-08 16:49 UTC, merged