fix(1tb-longevity): Added use_legacy_cluster_init flag to the config
scylladb/scylla-cluster-tests pull request #2834
Opened 2020-11-04 11:15 UTC by ShlomiBalalis

Since there is more than one seed, the longevity fail on startup
since  the seeds fail to communicate with eachother. To pervent this issue,
I disabled the parallel node setup

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2020-11-04 12:08 UTC, roydahan commented
Now in 4.3 that CDC is GA, Change this parameter to be the default as "false".
And remove it from all those that mark it specifically.

Just in 200-nodes and 500-nodes, set it to the legacy.

2020-11-05 02:07 UTC, ShlomiBalalis commented
@roydahan

2020-11-05 05:13 UTC, amoskong approved these changes

2020-11-05 11:12 UTC, roydahan commented on defaults/test_default.yaml
> -use_legacy_cluster_init: true
This is not what I meant.
If the default was already "false", I don't understand why you needed to set it to "false" in the 1tb test.
(your original PR).

2020-11-05 11:12 UTC, roydahan requested changes
Not what I wanted.

2020-11-05 11:21 UTC, roydahan approved these changes

2020-11-05 11:22 UTC, merged