improvement(cluster): wait for Scylla Machine Image setup to be done
scylladb/scylla-cluster-tests pull request #2856
Opened 2020-11-10 22:11 UTC by bentsi

when image setup is finished SMI touches /etc/scylla/machine_image_configured file.
So the the correct way to wait the image setup to be finished is to check if
the file exists.
Fixes: #2855

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2020-11-10 23:31 UTC, bentsi commented
Artifact test passed: https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-gce-image-test/17/console

2020-11-11 09:13 UTC, enaydanov requested changes

2020-11-11 09:13 UTC, enaydanov commented on sdcm/cluster.py
> +        result = self.remoter.run(cmd=f"ls {smi_configured_path}", ignore_status=True, verbose=False)
Do you think you can replace `ls` with `test -e `?

2020-11-11 09:40 UTC, enaydanov approved these changes

2020-11-11 09:40 UTC, merged