feature(nemesis): new manager nemesis that backs up specific kespaces
scylladb/scylla-cluster-tests pull request #2862
Opened 2020-11-12 10:01 UTC by ShlomiBalalis

https://trello.com/c/vs8ZCLbK/2319-backup-snapshot-multiple-tables-nemesis-using-manager

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2020-11-12 12:47 UTC, fruch commented on sdcm/nemesis.py
> +        self._set_current_disruption('ManagementBackupWithKFlag')
s/ManagementBackupWithKFlag/ManagementBackupWithSpecificKeyspaces/

don't force people to mentally remember what K flag is

2020-11-12 12:48 UTC, fruch commented on sdcm/nemesis.py
> +        self._mgmt_backup(use_k_flag=False)
again k has a specific meaning, writing fulling...

2020-11-12 12:49 UTC, fruch commented on sdcm/nemesis.py
> +        self._set_current_disruption('ManagementBackupWithKFlag')
should match the function name, for clarify

2020-11-12 12:49 UTC, fruch requested changes
mentioning K in function name or arguments is too cryptic
please use full name, so it would be clear

2020-11-12 16:56 UTC, roydahan commented
I don't see any link to staging jobs that shows it works on longevities multiple times.

2020-11-15 08:44 UTC, ShlomiBalalis commented
@roydahan https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Shlomo/job/test-3h-backup-k/

2020-11-15 10:20 UTC, fruch approved these changes
LGTM

2020-11-16 07:47 UTC, merged

2020-11-16 16:10 UTC, roydahan commented
@ShlomiBalalis / @fruch once it pass in a short / long longevity in master, let's backport to 4.3.
We need to see it tested on releases that are out.
(maybe even 4.2).