test(jepsen): run Jepsen using SCT
scylladb/scylla-cluster-tests pull request #2929
Opened 2020-11-29 12:15 UTC by enaydanov

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2020-12-13 11:01 UTC, bentsi commented on vars/jepsenPipeline.groovy
> +#! groovy
use general `vars/runSendEmail.groovy`, `vars/runCollectLogs.groovy`, `vars/runCleanupResource.groovy`

2020-12-13 11:07 UTC, bentsi commented on test-cases/jepsen/jepsen.yaml
> +store_results_in_elasticsearch: False
false

2020-12-13 11:08 UTC, bentsi commented on test-cases/jepsen/jepsen.yaml
> +instance_provision: "on_demand"
remove, add to job

2020-12-13 11:10 UTC, bentsi commented on test-cases/jepsen/jepsen.yaml
> +backtrace_decoding: false
remove

2020-12-13 11:11 UTC, bentsi commented on test-cases/jepsen/jepsen.yaml
> +test_duration: 360
move to the beginning

2020-12-13 11:12 UTC, bentsi requested changes
please address comments

2020-12-14 04:31 UTC, enaydanov commented on vars/jepsenPipeline.groovy
> +#! groovy
done

2020-12-14 04:31 UTC, enaydanov commented on test-cases/jepsen/jepsen.yaml
> +store_results_in_elasticsearch: False
done

2020-12-14 04:31 UTC, enaydanov commented on test-cases/jepsen/jepsen.yaml
> +instance_provision: "on_demand"
done

2020-12-14 04:31 UTC, enaydanov commented on test-cases/jepsen/jepsen.yaml
> +backtrace_decoding: false
done

2020-12-14 04:32 UTC, enaydanov commented on test-cases/jepsen/jepsen.yaml
> +test_duration: 360
done

2020-12-14 07:48 UTC, bentsi approved these changes

2020-12-15 07:49 UTC, merged