install-hydra.sh: Fix install when the /usr/local/bin/hydra exists
scylladb/scylla-cluster-tests pull request #2946
Opened 2020-12-02 03:15 UTC by asias

Step1:

user1 installs hydra
/usr/local/bin/hydra -> /home/user1//scylla-cluster-tests/docker/env/hydra.sh

Step2:

user2 installs hydra
/usr/local/bin/hydra -> /home/user1/scylla-cluster-tests/docker/env/hydra.sh

user2 will use the install from user1.

To fix create the link with -f option and unconditionally.

To make it even better, we'd better create the link under ~/.local/bin not /usr/local/bin.

2020-12-02 12:26 UTC, bentsi requested changes
1) currently, we don't support installing hydra for multiple users, your PR doesn't fix it and I don't really understand your use case: are you using multiple users on your machine?
Any-way, the way to solve this is to create `hydra` alias in ~/.bash_aliases. The alias command should cd to the SCT dir and then run ./docker/env/hydra.sh
2) don't remove the pre-checks template from the description 
3) your commit message is not in the right format, please read in the best practices doc that is part of the pre-checks PR template

2020-12-02 12:33 UTC, asias commented
> 
> 
>     1. currently, we don't support installing hydra for multiple users, your PR doesn't fix it and I don't really understand your use case: are you using multiple users on your machine?

User 1 installs then user 2 installs. User 2's install will use the previous install silently. For example, hydra does not work for me with plain user. I have to try install with root. 

>        Any-way, the way to solve this is to create `hydra` alias in ~/.bash_aliases. The alias command should cd to the SCT dir and then run ./docker/env/hydra.sh
> 
>     2. don't remove the pre-checks template from the description
> 
>     3. your commit message is not in the right format, please read in the best practices doc that is part of the pre-checks PR template

2020-12-02 12:39 UTC, asias commented
Yes, it does not support multiple install. But the latest install should work, no? Before this patch, latest install does not work.

2020-12-03 08:57 UTC, fruch commented
trying it again: https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/oel8/4/
even that I think it's not yet passing.

But I think we could merge, and address issues in core, regardless

2021-03-03 09:27 UTC, bentsi approved these changes

2021-03-03 09:27 UTC, merged