fix(rollingOperatorUpgradePipeline): remove withEnv and make it use routines
scylladb/scylla-cluster-tests pull request #2983
Opened 2020-12-09 08:01 UTC by dkropachev

https://trello.com/c/SPcGhigl/2670-deprecate-withenv-in-the-upgrade-pipeline
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2020-12-09 11:18 UTC, dkropachev commented
Tested - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dk-upgrade-scylla-operator-minikube/42/

2020-12-09 11:19 UTC, dkropachev commented
Test faield as planned (due to the s-o fails on major upgrade), cleanup succeeded

2020-12-12 12:54 UTC, dkropachev commented
Tested on s-o pipeline: https://jenkins.scylladb.com/view/master/job/scylla-master/job/rolling-upgrade/job/major-upgrade-scylla-operator-gke/25/
and on longevity pipeline: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/dmitry/job/dmitry-byo-longevity/428/

2020-12-14 13:07 UTC, enaydanov requested changes

2020-12-14 14:19 UTC, dkropachev commented on vars/getJobTimeouts.groovy
> +    println(testData)H
removed

2020-12-14 16:09 UTC, enaydanov approved these changes

2020-12-14 16:10 UTC, merged