fix(gemini): don't warn for unparsable log messages
scylladb/scylla-cluster-tests pull request #3053
Opened 2020-12-24 05:09 UTC by enaydanov

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [x] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [x] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [x] I have updated the Readme/doc folder accordingly (if needed)

2020-12-24 05:12 UTC, aleksbykov approved these changes

2020-12-30 08:57 UTC, fruch requested changes
please fix the unittest
https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-3053/5/execution/node/32/log/

2021-01-25 11:50 UTC, bentsi commented
@fruch I don't see any unit test that failed here...

2021-01-25 12:09 UTC, fruch commented
> @fruch I don't see any unit test that failed here...

my comment is from almost a month ago... meanwhile, yes seem like unittests are now working and this PR wasn't the cause.
I due want who open a PR to take a look at the unittest, (and I won't merge without know what's the issue is)

2021-01-25 13:24 UTC, bentsi approved these changes

2021-01-25 13:24 UTC, merged