fix(nemesis) disable ValidateHintedHandoffShortDowntime until fixed
scylladb/scylla-cluster-tests pull request #3095
Opened 2021-01-03 10:01 UTC by shoshan

nemesis to be fixed by https://trello.com/c/Ru0T9Nmu/1239-fix-validatehintedhandoff-nemesis

Signed-off-by: Shoshan Dagany <shoshan.dagany@scylladb.com>

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-01-03 10:56 UTC, roydahan commented on sdcm/nemesis.py
> +    def _disrupt_validate_hh_short_downtime(self):  # pylint: disable=invalid-name
```suggestion
    def disable_disrupt_validate_hh_short_downtime(self):  # pylint: disable=invalid-name
```

2021-01-03 10:56 UTC, roydahan commented on sdcm/nemesis.py
> +        self._disrupt_validate_hh_short_downtime()
```suggestion
        self.disable_disrupt_validate_hh_short_downtime()
```

2021-01-03 10:57 UTC, roydahan commented on sdcm/nemesis.py
> +    #  Temporary disable due to https://trello.com/c/Ru0T9Nmu/1239-fix-validatehintedhandoff-nemesis
```suggestion
    # Temporary disable due to https://trello.com/c/Ru0T9Nmu/1239-fix-validatehintedhandoff-nemesis
    # TODO: Bentsi to fix this nemesis or investigate if it's a real scylla issue.
```

2021-01-03 10:57 UTC, roydahan requested changes
Please apply my suggestions into your commit.

2021-01-06 12:06 UTC, shoshan commented on sdcm/nemesis.py
> +    def _disrupt_validate_hh_short_downtime(self):  # pylint: disable=invalid-name
done

2021-01-06 12:07 UTC, shoshan commented on sdcm/nemesis.py
> +        self._disrupt_validate_hh_short_downtime()
done

2021-01-06 12:08 UTC, shoshan commented on sdcm/nemesis.py
> +    #  Temporary disable due to https://trello.com/c/Ru0T9Nmu/1239-fix-validatehintedhandoff-nemesis
done

2021-01-13 18:32 UTC, merged