feature(rollout_restart): implement for all backends
scylladb/scylla-cluster-tests pull request #3231
Opened 2021-02-12 17:07 UTC by vponomaryov

Add support of 'rollout_restart' method for all backend classes.
With this change it is now possible to run 'ClusterRollingRestart'
nemesis on any backend.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [x] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-02-12 17:11 UTC, vponomaryov commented
Task: https://trello.com/c/tNJYSPfL/2638-rollingrestartcluster-nemesis

2021-02-15 09:18 UTC, bentsi requested changes
need to restart the Scylla service

2021-02-15 17:28 UTC, vponomaryov commented
> need to restart the Scylla service

Done

2021-02-17 10:40 UTC, vponomaryov commented
Retry DeepCode

2021-02-19 12:24 UTC, bentsi approved these changes

2021-02-19 12:24 UTC, merged