feature(resetlocalschema): run 'resetlocalschema'
scylladb/scylla-cluster-tests pull request #3252
Opened 2021-02-21 14:24 UTC by juliayakovlev

https://github.com/scylladb/scylla/commit/d3a5814f4fd0ef80f3dbfde4095eb11feb05745a
New nemesis: perform schema recalculation by running 'nodetool resetlocalschema'

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-02-23 14:11 UTC, roydahan approved these changes
LGTM. just minor comment about the TODO comment.

2021-02-23 14:11 UTC, roydahan commented on sdcm/nemesis.py
> +        # TODO: remove the validation below when resetlocalschema option will be available in the 4.5-dev
leave this validation.
It'll be needed in enterprise versions.

2021-02-23 14:11 UTC, roydahan commented on sdcm/nemesis.py
> +        # TODO: remove the validation below when resetlocalschema option will be available in the 4.5-dev
(remove the TODO)

2021-02-24 09:16 UTC, bentsi commented on sdcm/nemesis.py
> +        # Check schema version on the nodes - expected the same version on the all nodes
no need to check that, we run health check validator that verifies that schema is the same on all nodes

2021-02-24 09:16 UTC, bentsi requested changes
please address comments

2021-02-24 12:57 UTC, bentsi approved these changes

2021-02-24 12:58 UTC, merged