fix(rolling-upgrade): increase the test_duration to 360
scylladb/scylla-cluster-tests pull request #3281
Opened 2021-03-02 03:42 UTC by amoskong

Current test_duration (250 mins) isn't enough, some upgrade job was
interrupt for timeout.

> Test started at 2021-02-25 13:37:40, reached it's timeout (250 minute)

The jenkins pipeline timeout is 360, let's set the test_duration to be
same.

Signed-off-by: Amos Kong <amos@scylladb.com>

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-03-03 10:54 UTC, roydahan commented
@amoskong we don't approve duration extensions without understanding the root cause first.
It may point on regressions that we have and we need to understand why they started happening and potentially report an issue.

If this is due to the failure of centOS7 upgrade on 4.4, you also should mention that specifically and we should also explore why it happened only on CentOS7.

2021-03-03 10:54 UTC, roydahan requested changes
IS NOT APPROVED.
Until we understand the reason for this it's considered as regression.

2021-03-09 07:29 UTC, amoskong commented
The timeout (test duration 250 mins) started to occurred after the source scylla changed from 4.3.0-0.20210110.000585522 to 4.3.1-0.20210210.46650adcd

2021-03-23 17:42 UTC, bentsi commented
Is it still needed?

2021-03-29 19:50 UTC, roydahan commented
No, it's a regression we need to understand.

On Tue, Mar 23, 2021 at 7:42 PM Bentsi ***@***.***> wrote:

> Is it still needed?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla-cluster-tests/pull/3281#issuecomment-805099957>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE75CYBA6M7KFSQBLG7RE5TTFDHJ5ANCNFSM4YN4IAKA>
> .
>

2021-04-20 17:53 UTC, bentsi commented
@roydahan can I close this?

2021-04-20 22:33 UTC, roydahan commented
Yes

On Tue, Apr 20, 2021 at 8:53 PM Bentsi ***@***.***> wrote:

> @roydahan <https://github.com/roydahan> can I close this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla-cluster-tests/pull/3281#issuecomment-823481533>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE75CYBA3WPS6BYBO6RPAULTJW5RDANCNFSM4YN4IAKA>
> .
>

2021-04-20 22:56 UTC, closed without merging