fix(scrub nemesis): disable scrub nemesis
scylladb/scylla-cluster-tests pull request #3374
Opened 2021-04-06 14:54 UTC by juliayakovlev

Disable disrupt_corrupt_then_scrub nemesis in 2021.1 version due the issue
https://github.com/scylladb/scylla-enterprise/issues/1688 (Roy's request)

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-04-07 14:15 UTC, roydahan commented
Please send the PR to branch-2021.1.
In master it should already work.

2021-04-07 14:15 UTC, roydahan requested changes
Not to master branch.

2021-04-07 14:16 UTC, roydahan commented on sdcm/nemesis.py
> +        if '2021.1' in self.cluster.nodes[0].get_scylla_version():
I prefer not to check the version like this and work with the branches.

2021-04-07 14:17 UTC, roydahan commented on sdcm/nemesis.py
> +        if '2021.1' in self.cluster.nodes[0].get_scylla_version():
On second thought. it's good enough.

2021-04-07 14:17 UTC, roydahan approved these changes

2021-04-07 14:18 UTC, roydahan requested changes
But still needed only in 2021.1 branch, not master.

2021-04-08 07:33 UTC, juliayakovlev commented
Opened PR in 2021.1 branch
https://github.com/scylladb/scylla-cluster-tests/pull/3383

2021-04-08 07:33 UTC, closed without merging