fix(convert s-b metrics): fix metric conversion to float
scylladb/scylla-cluster-tests pull request #3442
Opened 2021-04-21 15:04 UTC by juliayakovlev

Task https://trello.com/c/iY1FHM8k/3231-conversion-to-float-fails-during-scylla-bench-run
1. Fix metric convertion to float. Support different formats like:
8.592961906s
        18.120703ms
        5.963775µs
        9h0m0.024080491s
        1m0.024080491s
        546431
2. Ignore line with 'EOF' substring

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-04-22 14:18 UTC, bentsi commented on sdcm/utils/common.py
> +from mypy_boto3_ec2 import EC2Client, EC2ServiceResource  # pylint: disable=import-error
remove the pylint disable

2021-04-22 14:19 UTC, bentsi commented on sdcm/utils/common.py
> +    """
please add unit test

2021-04-22 14:19 UTC, bentsi requested changes
please address comments

2021-04-22 14:34 UTC, juliayakovlev commented on sdcm/utils/common.py
> +from mypy_boto3_ec2 import EC2Client, EC2ServiceResource  # pylint: disable=import-error
done

2021-04-22 14:48 UTC, juliayakovlev commented on sdcm/utils/common.py
> +    """
done

2021-04-25 16:17 UTC, bentsi approved these changes

2021-04-25 16:17 UTC, merged