Improve K8S monitoring usefulness
scylladb/scylla-cluster-tests pull request #3655
Opened 2021-06-14 09:58 UTC by vponomaryov

This PR consists of following parts:
1) Use same scrape interval and timeout in K8S prometheus as in the SCT one
2) Make K8S grafana be accessible out-of-cluster
3) Simplify K8S monitoring health checker removing redundant parts.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2021-06-14 13:25 UTC, dkropachev requested changes

2021-06-14 13:25 UTC, dkropachev commented on sdcm/cluster_k8s/__init__.py
> +                    'affinity': monitoring_affinity_rules['affinity'],
Will fail if monitoring_affinity_rules = {}

2021-06-14 13:25 UTC, dkropachev commented on sdcm/cluster_k8s/__init__.py
> +                'affinity': monitoring_affinity_rules['affinity'],
Will fail if monitoring_affinity_rules = {}

2021-06-14 14:07 UTC, vponomaryov commented on sdcm/cluster_k8s/__init__.py
> +                    'affinity': monitoring_affinity_rules['affinity'],
Good catch. Fixed.

2021-06-14 14:07 UTC, vponomaryov commented on sdcm/cluster_k8s/__init__.py
> +                'affinity': monitoring_affinity_rules['affinity'],
Good catch. Fixed.

2021-06-14 16:28 UTC, dkropachev approved these changes

2021-06-15 11:09 UTC, bentsi approved these changes

2021-06-15 11:14 UTC, bentsi approved these changes

2021-06-15 11:14 UTC, merged