feature(grafana_snapshot): Add ability to login to grafana
scylladb/scylla-cluster-tests pull request #3658
Opened 2021-06-14 13:29 UTC by aleksbykov

Next versions of scylla-monitoring is going new grafana versions,
which require authentication for getting grafana livesnapshots.

Added new class to monitoring.ui, which allow to logged in to
grafana and get access to grafana livesnapshots functionality.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~New configuration option are added and documented (in `sdcm/sct_config.py`)~
- [ ] ~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- [ ] All new and existing unit tests passed (CI)
- [ ] ~I have updated the Readme/doc folder accordingly (if needed)~

2021-06-14 16:00 UTC, vponomaryov requested changes
If we do not need auth then why we use "admin" user and not "anonymous" approach without any need to pass auth?

Config example for grafana:

```
grafana.ini:
  users:
    viewers_can_edit: true
  auth:
    disable_login_form: true
    disable_signout_menu: true
  auth.anonymous:
    enabled: true
    org_role: Editor  # Admin, Editor, Viewer
```

Having it will just open grafana and use it.

2021-06-15 05:12 UTC, aleksbykov commented
> If we do not need auth then why we use "admin" user and not "anonymous" approach without any need to pass auth?
> 
> Config example for grafana:
> 
> ```
> grafana.ini:
>   users:
>     viewers_can_edit: true
>   auth:
>     disable_login_form: true
>     disable_signout_menu: true
>   auth.anonymous:
>     enabled: true
>     org_role: Editor  # Admin, Editor, Viewer
> ```
> 
> Having it we will be able to just open grafana and use it without any auth steps.

We not contorl Grafana settigns. And starting from 3.8, grafana in scylla monitoring is going to use authentication.  we use anonymous today. But from next grafana version in scylla monitoring authentication is required for creating live snapshots

2021-06-16 08:43 UTC, vponomaryov commented
> > If we do not need auth then why we use "admin" user and not "anonymous" approach without any need to pass auth?
> > Config example for grafana:
> > ```
> > grafana.ini:
> >   users:
> >     viewers_can_edit: true
> >   auth:
> >     disable_login_form: true
> >     disable_signout_menu: true
> >   auth.anonymous:
> >     enabled: true
> >     org_role: Editor  # Admin, Editor, Viewer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Having it we will be able to just open grafana and use it without any auth steps.
> 
> We not contorl Grafana settigns. And starting from 3.8, grafana in scylla monitoring is going to use authentication. we use anonymous today. But from next grafana version in scylla monitoring authentication is required for creating live snapshots

Can you please provide link for the place where auth part is changed?

2021-06-16 09:01 UTC, roydahan commented
Change also the default monitor branch to 3.8

2021-06-22 09:19 UTC, roydahan approved these changes

2021-06-22 09:20 UTC, merged