fix(get_grafana_snapshot): collect all created snapshots
scylladb/scylla-cluster-tests pull request #3659
Opened 2021-06-14 13:47 UTC by aleksbykov

When grafana snapshots were been taken, if getting any of snapshot
failed, no snapshots were saved.
Collect all snapshots which were created and save them

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~New configuration option are added and documented (in `sdcm/sct_config.py`)~
- [ ] ~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~
- [ ] All new and existing unit tests passed (CI)
- [ ] ~I have updated the Readme/doc folder accordingly (if needed)~

2021-06-14 14:13 UTC, fgelcer submitted a review, later dismissed
LGTM

2021-06-14 14:54 UTC, juliayakovlev submitted a review, later dismissed

2021-07-14 17:23 UTC, dkropachev commented
@aleksbykov , it is empty

2021-07-14 17:24 UTC, dkropachev requested changes

2021-07-14 17:24 UTC, dkropachev commented on sdcm/logcollector.py
> -
Is that all of the change ?)

2021-07-15 07:24 UTC, fgelcer commented
@aleksbykov , looks like you pushed the wrong changes... i see previously https://github.com/scylladb/scylla-cluster-tests/commit/41095d94b7810a152a2e7bd93041b3b80d45ee3d

2021-07-15 11:08 UTC, dkropachev commented
Someone already fixed the problem

2021-07-15 11:08 UTC, closed without merging