fix(sctlogcollector): Add email_data.json file to sctlog arch
scylladb/scylla-cluster-tests pull request #3777
Opened 2021-07-13 10:38 UTC by aleksbykov

during job scylla-master/longevity-200gb-48h/126/
email_data.json file was not saved correctly due to
error:
t:2021-07-11 04:34:51,531 f:send_email.py l:643 c:sdcm.send_email
 p:WARNING > Error during collecting data for email Circular reference detected
And when this file was read durin email_send stage it failed with error:
 t:2021-07-11 04:34:51,742 f:send_email.py l:625 c:sdcm.send_email p:WARNING >
 Error during read email data file /home/ubuntu/sct-results/20210709-030744-525604/email_data.json:
Expecting value: line 1 column 97262 (char 97261)

the main error happened during dumping email_data object to json file:
json.dump(email_data, json_file)

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-07-13 11:53 UTC, dkropachev approved these changes

2021-07-14 11:51 UTC, dkropachev requested changes
@aleksbykov , Alex, could you move out linting part into separate commit

2021-07-14 11:53 UTC, fgelcer requested changes

2021-07-14 11:53 UTC, fgelcer commented on sdcm/logcollector.py
> +                "Check dashbaord: %s", checked_dashboard_url.format(grafana_ip=grafana_ip,
little typo in the word "dashboard"

```suggestion
                "Check dashboard: %s", checked_dashboard_url.format(grafana_ip=grafana_ip,
```

2021-07-14 12:07 UTC, aleksbykov commented
@fgelcer @dkropachev Done

2021-07-14 12:11 UTC, dkropachev approved these changes

2021-07-14 12:11 UTC, merged