feature(sct-runner): allow to define instance type
scylladb/scylla-cluster-tests pull request #3958
Opened 2021-09-15 14:46 UTC by vponomaryov

Also, update vars/createSctRunner.groovy with the logic
where we reuse this feature and set non-default instance types
for the "k8s-local-kind-aws" and "k8s-local-kind-gce" backends.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2021-09-19 16:39 UTC, dkropachev requested changes

2021-09-19 16:39 UTC, dkropachev commented on sdcm/sct_runner.py
> +    def create_instance(self, instance_type: str, test_id: str, test_duration: int, region_az: str):
```suggestion
    def create_instance(self, test_id: str, test_duration: int, region_az: str, instance_type: str = ''):
```

2021-09-19 16:39 UTC, dkropachev commented on vars/createSctRunner.groovy
> +    if [[ "$cloud_provider" == "aws" || "$cloud_provider" == "gce" ]]; then
Does not make any sense, why do you set `instance_type_arg` if you are not using it.
Are we stop using sct runner for `k8s-local-kind-*` backends ?

2021-09-20 07:11 UTC, enaydanov requested changes
I voted for the same change as @dkropachev

2021-09-20 08:33 UTC, vponomaryov commented on sdcm/sct_runner.py
> +    def create_instance(self, instance_type: str, test_id: str, test_duration: int, region_az: str):
Done

2021-09-20 08:48 UTC, enaydanov approved these changes

2021-09-20 08:50 UTC, merged