improvement(gke-cleanup): delete orphaned disks deleting GKE clusters
scylladb/scylla-cluster-tests pull request #4070
Opened 2021-10-29 09:20 UTC by vponomaryov

Without this change deleting each GKE cluster we leave orphaned
two following kinds of disks:
- 10Gb, created for MinIO service
- 10Gb, created for a Scylla which is dedicated for a Scylla Manager

These stay undeleted because it gets created dynamically and Google
doesn't delete it with deletino of a cluster.
So, do it ourselves, and delete all detached disks in the zone of
a deleted GKE cluster. 'All', because we cannot filter disks per
GKE cluster name.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2021-10-29 10:26 UTC, dkropachev submitted a review, later dismissed

2021-11-01 12:47 UTC, bentsi requested changes
Per our discussion let's create hydra command: `clean-gke-orphaned-disks` and run it during clean resources stage in Jenkins jobs

2021-11-02 12:36 UTC, vponomaryov commented
> Per our discussion let's create hydra command: `clean-gke-orphaned-disks` and run it during clean resources stage in Jenkins jobs

Made it be part of the general "clean resources" logic, because implementing it I didn't find any reason to make it be separate hydra command.

2021-11-02 21:20 UTC, dkropachev approved these changes

2021-11-03 09:42 UTC, bentsi approved these changes

2021-11-03 09:42 UTC, merged