improvement(nemesis.py): improve logs RebuildStreamingErr
scylladb/scylla-cluster-tests pull request #4077
Opened 2021-11-01 11:35 UTC by fgelcer

from the logs it is not clear how much we will wait
(sleep), and the message could include it very easily
hence changed the log message to include the "random"
time to sleep.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-11-01 13:59 UTC, juliayakovlev approved these changes

2021-11-01 14:02 UTC, aleksbykov submitted a review, later dismissed
LGTM

2021-11-01 15:50 UTC, enaydanov requested changes

2021-11-01 15:50 UTC, enaydanov commented on sdcm/nemesis.py
> +        self.log.debug(f'wait for random between 10s to 10m --> {sleep_time}')
Please, use lazy logging.

2021-11-01 20:22 UTC, fgelcer commented on sdcm/nemesis.py
> +        self.log.debug(f'wait for random between 10s to 10m --> {sleep_time}')
fixed

2021-11-01 20:28 UTC, aleksbykov approved these changes
LGTM

2021-11-02 05:34 UTC, juliayakovlev submitted a review, later dismissed

2021-11-05 23:08 UTC, amoskong commented on sdcm/nemesis.py
> +        self.log.debug('wait for random between 10s to 10m --> %s', sleep_time)
How about adding a unit    ` --> %s seconds`?

2021-11-07 11:34 UTC, fgelcer commented on sdcm/nemesis.py
> +        self.log.debug('wait for random between 10s to 10m --> %s', sleep_time)
added

2021-11-10 07:13 UTC, enaydanov approved these changes

2021-11-10 07:15 UTC, juliayakovlev approved these changes

2021-11-10 07:16 UTC, merged