fix(longevity-pipeline): do not run provision resources stage for K8S
scylladb/scylla-cluster-tests pull request #4114
Opened 2021-11-11 16:16 UTC by vponomaryov

Recently was added "provision resources" stage to the 'longevity'
pipeline. This stage silently fails if not supported, for it, backend
is used. In such a case stage gets marked as 'SUCCESS' but, it silently
marks whole build as "FAILURE". And all the K8S backends are not
supported as of now.

So, check the backend explicitely and skip this step completely avoiding
false negative results for all the longevity runs using K8S backends.
It will make all the K8S longevities be correctly marked according to
the other stages results.

Also, update post actions with more info about completed stages for
better visibility.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2021-11-11 18:33 UTC, dkropachev requested changes

2021-11-11 18:33 UTC, dkropachev commented on vars/longevityPipeline.groovy
> +                                        if (!params.backend.contains('k8s')) {
```suggestion
                                        if (params.backend == 'aws') {
```

2021-11-12 10:34 UTC, vponomaryov commented on vars/longevityPipeline.groovy
> +                                        if (!params.backend.contains('k8s')) {
Done

2021-11-12 10:38 UTC, dkropachev approved these changes

2021-11-15 12:16 UTC, bentsi approved these changes

2021-11-15 12:16 UTC, merged