revert(health_checker): removing removed_nodes_list check
scylladb/scylla-cluster-tests pull request #4139
Opened 2021-11-18 16:03 UTC by ShlomiBalalis

Due to https://github.com/scylladb/scylla-enterprise/issues/1419 being resloved, I removed
the changes that were inserted in https://github.com/scylladb/scylla-cluster-tests/pull/2383
As of now, ANY node that will not appear as UN during the health check will
trigger a critical event

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-11-18 16:14 UTC, vponomaryov commented
@ShlomiBalalis need to remember that "K8S" backends almost always use only released Scylla versions. 
Moreover, it is pretty possible to be not the latest one. 
So, such changes must align with it. As of now it will break some tests running on K8S.

Maybe it is right time to start using [1] for something else than bunch of nemesis'?

[1] https://github.com/scylladb/scylla-cluster-tests/blob/1c60085c/sdcm/utils/version_utils.py#L365

2021-11-18 16:16 UTC, ShlomiBalalis commented
> @ShlomiBalalis need to remember that "K8S" backends almost always use only released Scylla versions. Moreover, it is pretty possible to be not the latest one. So, such changes must align with it. As of now it will break some tests running on K8S.
> 
> Maybe it is right time to start using [1] for something else than bunch of nemesis'?
> 
> [1] https://github.com/scylladb/scylla-cluster-tests/blob/1c60085c/sdcm/utils/version_utils.py#L365

@vponomaryov The fix for 1419 was even backported to 2020.1, is version that k8s clusters use really older than that?

2021-11-18 20:11 UTC, roydahan commented
@vponomaryov it's a very old fix and backport.
It's already in all supported patch versions.

2021-11-18 20:14 UTC, roydahan requested changes

2021-11-18 20:14 UTC, roydahan commented on sdcm/utils/health_checker.py
> -                severity=Severity.ERROR if node_ip in removed_nodes_list else Severity.CRITICAL,
Maybe it will be easier to debug this or similar issue if we keep that removed_nodes_list here  as a INFO log message if that  list isn't empty.

2021-11-22 18:32 UTC, roydahan approved these changes

2021-11-22 18:33 UTC, roydahan commented
@ShlomiBalalis please check failures.

@juliayakovlev please review.

2021-11-23 12:20 UTC, ShlomiBalalis commented
> @ShlomiBalalis please check failures.

@roydahan I needed to fix the unit test, should be ok now

2021-11-23 14:04 UTC, roydahan approved these changes

2021-11-23 14:04 UTC, roydahan commented
@juliayakovlev ping.

2021-11-23 14:18 UTC, juliayakovlev approved these changes

2021-11-24 02:57 UTC, merged