fix(longevity_test): Skip paxos error/warning messages (#8706)
scylladb/scylla-cluster-tests pull request #4150
Opened 2021-11-23 14:57 UTC by aleksbykov

on branch 4.4 alternator tests usually set as failed due
paxos/errors messages described in issue #8706.
Ingore this messages for alternator tests globally.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-11-23 14:58 UTC, aleksbykov commented
PR should be merged only to branch-4.4

2021-11-23 15:22 UTC, fgelcer approved these changes
LGTM

2021-11-23 15:41 UTC, juliayakovlev requested changes

2021-11-23 15:42 UTC, aleksbykov commented on sdcm/sct_events/group_common_events.py
> +            line="mutation_write_timeout_exception"
Thanks, will add

2021-11-23 18:27 UTC, aleksbykov commented on sdcm/sct_events/group_common_events.py
> +            line="mutation_write_timeout_exception"
done

2021-11-24 03:02 UTC, roydahan approved these changes

2021-11-24 03:03 UTC, merged