fix(upgrade test): change regex in ignore_ycsb_connection_refused filter
scylladb/scylla-cluster-tests pull request #4195
Opened 2021-12-07 13:21 UTC by juliayakovlev

'Connection refused' YcsbStressEvent is filtered in upgrade test when an upgraded node is
restarted and it's unable to connect to.
In the test https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-
alternator-test/63/ another wording of this error was received:

```
Unable to execute HTTP request: Connect to alternator:8080 [alternator/10.142.0.127] failed: Connection refused (Connection refused)
```

Change the regex for the filter accordingly

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-12-07 13:26 UTC, dkropachev requested changes

2021-12-07 13:26 UTC, dkropachev commented on sdcm/sct_events/group_common_events.py
> +    with EventsFilter(event_class=YcsbStressEvent, regex='.*Unable to execute HTTP request: .*Connection refused.*'):
```suggestion
    with EventsFilter(event_class=YcsbStressEvent, regex='Unable to execute HTTP request: .*Connection refused'):
```

2021-12-07 13:42 UTC, juliayakovlev commented on sdcm/sct_events/group_common_events.py
> +    with EventsFilter(event_class=YcsbStressEvent, regex='.*Unable to execute HTTP request: .*Connection refused.*'):
changed

2021-12-08 08:46 UTC, dkropachev approved these changes

2021-12-08 12:15 UTC, bentsi approved these changes

2021-12-08 12:15 UTC, merged