feature(raid_support): Support raid configuration(WIP)
scylladb/scylla-cluster-tests pull request #4225
Opened 2021-12-15 13:26 UTC by aleksbykov

scylla-4.6 have support to create 2 kind of
raid configuration: RAID0 and RAID5.
Scylla: https://github.com/scylladb/scylla/commit/42fd73d0332d034809c6cd228785bff82e1845aa
Feature: https://github.com/scylladb/scylla/pull/9093

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-12-15 13:31 UTC, aleksbykov commented
@dkropachev Could you review the commit. I didn't test it yet, because it depend on another https://github.com/aleksbykov/scylla-machine-image/commit/1a240fa4f98268fe91f54aa3233c57b0a5d47190

2021-12-15 13:54 UTC, dkropachev requested changes

2021-12-15 13:54 UTC, dkropachev commented on sdcm/sct_provision/aws/user_data.py
> +        return self.params.get("raid_level", RaidLevelType.RAID0)
Wont work, you need to go wth:
```suggestion
        return self.params.get("raid_level") or RaidLevelType.RAID0
```

2021-12-15 13:54 UTC, dkropachev commented on sdcm/provision/common/user_data.py
> +    def raid_level(self) -> int:
```suggestion
    def raid_level(self) -> RaidLevelType:
```

2021-12-16 06:21 UTC, aleksbykov commented
@dkropachev thanks, i didn't miss anything related to provision, did i?

2021-12-16 08:01 UTC, dkropachev commented
> @dkropachev thanks, i didn't miss anything related to provision, did i?

Nope, you did a great job, should work like a charmed.

2021-12-16 08:29 UTC, dkropachev commented
You can test it by looking at user-data, when machine-image is extracting it, just run `grep -i user-data -R ./db-logs`

2021-12-16 08:42 UTC, dkropachev commented
Tested with proposed changes:

```
/var/log/syslog:Dec 16 08:34:23 ip-10-0-2-7 scylla_image_setup[992]: 2021-12-16 08:34:23,928 - [scylla_configure] - INFO - Got user-data: {"cluster_name": "longevity-10gb-3h-dkropachev-db-cluster-None", "data_device": "instance_store", "post_configuration_script": "IyEvYmluL2Jhc2gKCnNlZCAtaSAtZSAncy9eXCpbWzpibGFuazpdXSpzb2Z0W1s6Ymxhbms6XV0qbnByb2NbWzpibGFuazpdXSo0MDk2LyoJCXNvZnQJbnByb2MJCXVubGltaXRlZC8nICAgICAgICAgL2V0Yy9zZWN1cml0eS9saW1pdHMuZC8yMC1ucHJvYy5jb25mCmVjaG8gLWUgJyoJCWhhcmQJbnByb2MJCXVubGltaXRlZCcgPj4gL2V0Yy9zZWN1cml0eS9saW1pdHMuZC8yMC1ucHJvYy5jb25mCgpzZWQgLWkgJ3MvI01heFNlc3Npb25zIFwoLipcKSQvTWF4U2Vzc2lvbnMgMTAwMC8nIC9ldGMvc3NoL3NzaGRfY29uZmlnCnNlZCAtaSAncy8jTWF4U3RhcnR1cHMgXCguKlwpJC9NYXhTdGFydHVwcyA2MC8nIC9ldGMvc3NoL3NzaGRfY29uZmlnCnNlZCAtaSAncy8jTG9naW5HcmFjZVRpbWUgXCguKlwpJC9Mb2dpbkdyYWNlVGltZSAxNXMvJyAvZXRjL3NzaC9zc2hkX2NvbmZpZwpzeXN0ZW1jdGwgcmVzdGFydCBzc2hkCg==", "raid_level": 0, "scylla_yaml": {"cluster_name": "longevity-10gb-3h-dkropachev-db-cluster-None"}, "start_scylla_on_first_boot": false}

```

2021-12-16 14:37 UTC, aleksbykov commented on sdcm/sct_provision/aws/user_data.py
> +        return self.params.get("raid_level", RaidLevelType.RAID0)
fixed

2021-12-16 15:11 UTC, aleksbykov commented on sdcm/provision/common/user_data.py
> +    def raid_level(self) -> int:
fixed

2021-12-17 07:43 UTC, dkropachev commented
Alex, please rebase and lets merge it

2022-01-13 08:32 UTC, aleksbykov commented
@dkropachev Conflicts were resolved

2022-01-13 12:00 UTC, fgelcer submitted a review, later dismissed
LGTM

2022-01-17 11:31 UTC, roydahan commented
Add a new longevity to use raid-5, try using it on GCE.
You can use an existing one + a configuration that just add raid-5.

2022-01-19 16:18 UTC, aleksbykov commented
New longevity added.
Job will be added after commit merged

2022-01-19 16:19 UTC, aleksbykov commented
Job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/longevity-3h-10gb-gce-test/2/console. Instances created with raid 5

2022-01-24 13:38 UTC, enaydanov approved these changes

2022-01-24 15:23 UTC, dkropachev approved these changes

2022-01-24 15:23 UTC, merged