fix(ScyllaYaml): experimental_feature as list
scylladb/scylla-cluster-tests pull request #4238
Opened 2021-12-20 06:06 UTC by aleksbykov

experimental_feature should be a list in scylla.yaml instead
of dict

https://docs.scylladb.com/operating-scylla/scylla-yaml/

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2021-12-20 07:09 UTC, dkropachev requested changes

2021-12-20 07:09 UTC, dkropachev commented on sdcm/provision/scylla_yaml/scylla_yaml.py
> +    experimental_features: list = []
```suggestion
    experimental_features: list[str] = []
```

2021-12-20 07:09 UTC, dkropachev requested changes
Alex, could also please fix unit tests

2021-12-21 10:30 UTC, juliayakovlev submitted a review, later dismissed
ok, after addressing of @dkropachev comment

2021-12-29 07:50 UTC, enaydanov submitted a review, later dismissed

2022-01-10 18:32 UTC, roydahan commented
@aleksbykov is this PR still needed?

2022-01-10 18:58 UTC, aleksbykov commented
@roydahan yes, it is needed. Need approval from @dkropachev

2022-01-11 10:23 UTC, dkropachev approved these changes

2022-01-11 10:28 UTC, vponomaryov approved these changes

2022-01-11 10:57 UTC, merged