Fix continues performance
scylladb/scylla-cluster-tests pull request #4245
Opened 2021-12-21 11:26 UTC by dkropachev

Introduce continues_hash that is used to find continues events

https://trello.com/c/R0BXSqmQ/4270-dblogreader-improve-continuous-events-performance
## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2021-12-22 10:10 UTC, bentsi commented on sdcm/sct_events/continuous_event.py
> +        if present_event := self.hashed_continuous_events.get(event.continues_hash):
`continues_hash` -> `continuous_hash`

2021-12-22 10:23 UTC, bentsi commented on sdcm/sct_events/continuous_event.py
> +        return {attr_value: getattr(self, attr_value, None) for attr_value in self.continues_hash_fields}
`attr_value` -> `attr_name`

2021-12-22 10:24 UTC, bentsi commented on sdcm/sct_events/continuous_event.py
> +            str({attr_value: data.get(attr_value, None) for attr_value in cls.continues_hash_fields})
`attr_value` -> `attr_name`

2021-12-22 10:28 UTC, bentsi requested changes
add default behavior when continuous hash fields were not set in a new event

2021-12-22 10:36 UTC, dkropachev commented
Provision failed due to the - https://github.com/scylladb/scylla-cluster-tests/issues/4252, has nothing to do with this PR

2021-12-23 09:44 UTC, dkropachev commented on sdcm/sct_events/continuous_event.py
> +                'Continues event %s with hash %s (%s) is getting replaces with another event %s',
fixed

2021-12-23 09:47 UTC, dkropachev commented on sdcm/sct_events/continuous_event.py
> +        if self.find_events_by_id(event.event_id):
removed

2021-12-23 09:48 UTC, dkropachev commented on sdcm/sct_events/continuous_event.py
> +    def find_events_by_id(self, event_id: Union[uuid.UUID, str]) -> List[ContinuousEvent]:
removed

2021-12-23 09:50 UTC, dkropachev commented on unit_tests/test_sct_events_continuous_events_registry.py
>      def test_get_event_by_id(self,
removed

2021-12-23 09:50 UTC, dkropachev commented on sdcm/sct_events/continuous_event.py
> +        if not errors:
done

2021-12-23 10:36 UTC, KnifeyMoloko submitted a review, later dismissed
Looks good :)

2021-12-27 15:15 UTC, bentsi requested changes
- let's simplify the logic and use tuples instead of generating hashes
- let's remove register/unregister methods and call add_event and del_event directly on the event registry object in `begin_event()` and `end_event()` methods

2021-12-29 11:51 UTC, bentsi approved these changes

2021-12-29 12:30 UTC, merged