feature(split-sct-log): small util for split sct log by nemesis
scylladb/scylla-cluster-tests pull request #4433
Opened 2022-02-10 10:48 UTC by soyacz

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-02-13 07:35 UTC, fruch approved these changes
LGTM

2022-02-13 10:09 UTC, fgelcer submitted a review, later dismissed
other than a small question/comment, LGTM

2022-02-14 09:22 UTC, soyacz commented on utils/split_sct_log.py
> +    for line in sct_log.readlines():
it does not make difference - since line has been written, we don't care.

2022-02-14 11:15 UTC, enaydanov requested changes

2022-02-14 11:15 UTC, enaydanov commented on utils/split_sct_log.py
> +#!/usr/bin/env python
You need to add license preamble and copyright string.

2022-02-14 11:15 UTC, enaydanov commented on utils/split_sct_log.py
> +    return "_".join(line_content.split(" ")[2:3]).split(",", maxsplit=1)[0]
Please, provide an example of a string parsed.

2022-02-14 11:15 UTC, enaydanov commented on utils/split_sct_log.py
> +input_dir = Path(os.getcwd())
`Path.cwd()`

2022-02-14 11:15 UTC, enaydanov commented on utils/split_sct_log.py
> +    os.mkdir(input_dir / "parts")
`Path(input_dir / "parts").mkdir(exist_ok=True)`

2022-02-14 13:34 UTC, soyacz commented on utils/split_sct_log.py
> +    os.mkdir(input_dir / "parts")
Thanks @enaydanov !

2022-02-14 14:07 UTC, enaydanov commented on utils/split_sct_log.py
> +# Copyright (c) 2021 ScyllaDB
2022 :)

2022-02-14 14:31 UTC, soyacz commented on utils/split_sct_log.py
> +# Copyright (c) 2021 ScyllaDB
time goes by so fast... :smile:

2022-02-16 06:00 UTC, enaydanov approved these changes

2022-02-16 07:25 UTC, fgelcer approved these changes
LGTM

2022-02-16 10:59 UTC, merged