fix(UpgradeBaseVersion): filter repos which has only RCs
scylladb/scylla-cluster-tests pull request #4438
Opened 2022-02-10 16:36 UTC by fruch

Version 5.0/4.6 aren't released yet, hence we don't want to set them
as a base version for rolling upgrades. we do this by getting all the versions
from a repo, and filtering out the release canidate to see if we are
left with anything.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-02-13 10:13 UTC, fruch commented on sdcm/utils/version_utils.py
> +def get_all_versions__from_debian_repository(urls):
fixed

2022-02-13 10:21 UTC, fgelcer submitted a review, later dismissed
LGTM

2022-02-14 10:06 UTC, enaydanov requested changes

2022-02-14 10:06 UTC, enaydanov commented on sdcm/utils/version_utils.py
> +def get_all_versions_from_centos_repository(urls):
Please, add type hints.

2022-02-14 10:06 UTC, enaydanov commented on sdcm/utils/version_utils.py
> +def get_all_versions(url):
Please, add type hints.

2022-02-17 09:51 UTC, fruch commented on sdcm/utils/version_utils.py
> +    result = set().union(*[thread.result for thread in threads])
it won't work since set are returned from the functions, and i need a union of them all.

2022-02-17 09:51 UTC, fruch commented on sdcm/utils/version_utils.py
> +            return set()
remove

2022-02-17 09:51 UTC, fruch commented on sdcm/utils/version_utils.py
> +def get_all_versions(url):
added

2022-02-17 09:51 UTC, fruch commented on sdcm/utils/version_utils.py
> +def get_all_versions_from_centos_repository(urls):
added

2022-02-17 09:51 UTC, fruch commented on sdcm/utils/version_utils.py
> +def get_all_versions_from_debian_repository(urls):
added

2022-02-17 15:05 UTC, fgelcer approved these changes
LGTM

2022-02-21 07:14 UTC, enaydanov commented on sdcm/utils/version_utils.py
> +    result = set().union(*[thread.result for thread in threads])
Got it. Maybe, you can use class method then: `set.union()`

2022-02-21 07:33 UTC, enaydanov commented on utils/get_supported_scylla_base_versions.py
> +            if not fliter_rc:
A typo here: `fliter_rc` -> `filter_rc`

2022-02-21 16:52 UTC, roydahan commented
@fruch what happens if we want to test upgrade from 4.6.rc1 to 4.6.rc2?
(It should have been supported but AFAIK there was a bug that tries to upgrade from 4.6.rc2 to 4.6.rc2).
@fgelcer can add more info.

2022-02-22 06:31 UTC, fruch commented
> @fruch what happens if we want to test upgrade from 4.6.rc1 to 4.6.rc2? (It should have been supported but AFAIK there was a bug that tries to upgrade from 4.6.rc2 to 4.6.rc2). @fgelcer can add more info.
> 
> Also, won't it testing in master upgrade from 5.0.rcx to master latest?

This change won't select a 4.6 as base, not until we have the first release of 4.6. so upgrade from rc to rc won't be tested.

2022-02-22 06:33 UTC, fgelcer commented
> @fruch what happens if we want to test upgrade from 4.6.rc1 to 4.6.rc2? (It should have been supported but AFAIK there was a bug that tries to upgrade from 4.6.rc2 to 4.6.rc2). @fgelcer can add more info.
> 
> Also, won't it testing in master upgrade from 5.0.rcx to master latest?

AFAICT since 63ce37b3241a72a6029e0a7da2bc94fbdd63f44e, if we want to run from 4.x.rcY we can set it manually in the Jenkins job's build...
but i think that we don't have to test upgrade between RCs..

2022-02-22 06:44 UTC, fruch commented on utils/get_supported_scylla_base_versions.py
> +            if not fliter_rc:
fixed

2022-02-22 06:45 UTC, fruch commented on sdcm/utils/version_utils.py
> +    result = set().union(*[thread.result for thread in threads])
changed to use the class method

2022-02-22 09:45 UTC, fgelcer approved these changes
LGTM

2022-02-22 15:44 UTC, roydahan commented
> > @fruch what happens if we want to test upgrade from 4.6.rc1 to 4.6.rc2? (It should have been supported but AFAIK there was a bug that tries to upgrade from 4.6.rc2 to 4.6.rc2). @fgelcer can add more info.
> > Also, won't it testing in master upgrade from 5.0.rcx to master latest?
> 
> This change won't select a 4.6 as base, not until we have the first release of 4.6. so upgrade from rc to rc won't be tested.

Well, I'm not sure it's ok.
In theory we should test upgrade between RCs.

2022-02-23 06:01 UTC, fruch commented
> > > @fruch what happens if we want to test upgrade from 4.6.rc1 to 4.6.rc2? (It should have been supported but AFAIK there was a bug that tries to upgrade from 4.6.rc2 to 4.6.rc2). @fgelcer can add more info.
> > > Also, won't it testing in master upgrade from 5.0.rcx to master latest?
> > 
> > 
> > This change won't select a 4.6 as base, not until we have the first release of 4.6. so upgrade from rc to rc won't be tested.
> 
> Well, I'm not sure it's ok. In theory we should test upgrade between RCs.

So you only want guard cases that target version is in the release folder ? I.e. release candidate is promoted and someone is running it (cause of rerunning a job, or something like that ?)

2022-02-23 13:12 UTC, roydahan commented
For now, we will not test a base_version that is RC, because there is a limitation that new repo overrides that old repo.
Once we move to use a base_version that will use a gce image and not a repo, we can try supporting RCs as base version.

2022-02-23 13:13 UTC, roydahan approved these changes

2022-02-23 13:13 UTC, merged