fix(cloud_longevity): collect cloud manager logs
scylladb/scylla-cluster-tests pull request #4494
Opened 2022-03-01 07:59 UTC by juliayakovlev

Collect and upload siren manager logs

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-03-03 11:40 UTC, enaydanov requested changes

2022-03-03 11:40 UTC, enaydanov commented on sdcm/logcollector.py
> +                cloud_manager_id = self.params["cloud_manager_id"] if "cloud_manager_id" in self.params else None
Please, use `self.params.get()` or put a comment why it's done this way.

2022-03-03 11:45 UTC, enaydanov approved these changes

2022-03-03 11:54 UTC, ilya-rarov approved these changes
LGTM

2022-03-03 11:57 UTC, merged

2022-03-07 14:24 UTC, yarongilor commented on sdcm/logcollector.py
> +                from cluster_cloud import get_aws_manager_instance_by_cluster_id  # pylint: disable=import-outside-toplevel
i'm not sure i follow this change. what happens if it is a GCP siren cluster. does it also try importing this AWS method?