fix(DTCS): remove DTCS as is deprecated
scylladb/scylla-cluster-tests pull request #4754
Opened 2022-05-17 16:45 UTC by soyacz

We still use for some tests DTCS which is deprecated.
Especially it generates many warnings in rolling-upgrade tests,
which obscures other warnings.

Fix is about removing DTCS and replacing it with TWCS wherever possible.

https://trello.com/c/zEPZB5wR
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-05-17 19:13 UTC, fgelcer approved these changes
LGTM

2022-05-18 16:31 UTC, roydahan requested changes

2022-05-18 16:31 UTC, roydahan commented on data_dir/cs_profile_background_reads_overload.yaml
> +    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_unit': 'DAYS', 'compaction_window_size': 365}
```suggestion
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_unit': 'MINUTES', 'compaction_window_size': 30}
```

2022-05-18 16:31 UTC, roydahan commented on data_dir/cassandra-stress-custom.yaml
> +    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_unit': 'DAYS', 'compaction_window_size': 365}
```suggestion
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_unit': 'DAYS', 'compaction_window_size': 1}
```

2022-05-19 12:16 UTC, fgelcer approved these changes
LGTM

2022-05-25 07:24 UTC, fgelcer commented
ping @fruch @roydahan

2022-05-29 21:44 UTC, roydahan approved these changes

2022-05-29 21:44 UTC, merged