improvement(operator): Increase time of operator basic 3h to 12h
scylladb/scylla-cluster-tests pull request #4771
Opened 2022-05-22 09:18 UTC by juliayakovlev

Task:
https://trello.com/c/63gWQAl5/4566-increase-time-of-operator-basic-3h-to-12h

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-05-22 09:49 UTC, fruch commented
@juliayakovlev can you trigger it, at least once ? (and put the link here)

2022-05-22 14:08 UTC, juliayakovlev commented
> @juliayakovlev can you trigger it, at least once ? (and put the link here)

@fruch running

2022-05-22 18:02 UTC, bentsi requested changes
longevity-scylla-operator-basic-3h.yaml -> longevity-scylla-operator-basic-**12**h.yaml

2022-05-23 09:54 UTC, vponomaryov requested changes
Agree with Bentsi.
There are more files to be renamed - jenkins ones located at `jenkins-pipelines` directory.

2022-05-23 15:15 UTC, juliayakovlev commented
You are both right. Fixed

2022-05-23 16:09 UTC, vponomaryov approved these changes

2022-05-24 05:43 UTC, fruch commented
@vponomaryov what do you say, should we change also the pipelines names ? (We'll need to manually fix that in Jenkins, in the relevant places)

2022-05-24 05:46 UTC, juliayakovlev commented
> @vponomaryov what do you say, should we change also the pipelines names ? (We'll need to manually fix that in Jenkins, in the relevant places)

Yes, I will change it once the commit will be in

2022-05-24 05:59 UTC, fruch commented
> > @vponomaryov what do you say, should we change also the pipelines names ? (We'll need to manually fix that in Jenkins, in the relevant places)
> 
> Yes, I will change it once the commit will be in

Sorry, I didn't noticed the name change (the screen of my phone is too small)

Do you have a run result of one of them ?

2022-05-24 06:27 UTC, juliayakovlev commented
> > > @vponomaryov what do you say, should we change also the pipelines names ? (We'll need to manually fix that in Jenkins, in the relevant places)
> > 
> > 
> > Yes, I will change it once the commit will be in
> 
> Sorry, I didn't noticed the name change (the screen of my phone is too small)
> 
> Do you have a run result of one of them ?

Yes, all nemeses passed. There is a problem with cluster health validation that I need to check, but it's not connected to current change
https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/yulia-longevity-scylla-operator-basic-3h-eks/21/

2022-05-24 08:59 UTC, vponomaryov commented
> @vponomaryov what do you say, should we change also the pipelines names ? (We'll need to manually fix that in Jenkins, in the relevant places)

Yes, existing jenkins jobs must be updated after this change gets merged.

2022-05-24 09:02 UTC, fruch approved these changes
LGTM

2022-05-24 09:03 UTC, merged

2022-05-24 09:20 UTC, vponomaryov commented
> @vponomaryov if we merge this only to master where are the jobs needs to be updated ? the ones https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/ ? do we have branches of SCT for the previous operator versions, or they were run with SCT all the time ?

We haven't created an SCT branch for operator 1.7.x version.
We had only for 1.6.x and earlier.
For testing of the operator 1.7.x was used `master` branch of SCT.

So, we should update CI jobs in `master` and `1.7.x` directories of jenkins.