test(many-clients test): use sisyphus monkey
scylladb/scylla-cluster-tests pull request #4817
Opened 2022-05-27 12:57 UTC by soyacz

Currently we use ChaosMonkey in many-clients test.
This is bad when we want to reproduce the test flow.
Let's change it to SisyphusMonkey with random seed,
so in case we want to reproduce issue we have option for that.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-05-29 06:21 UTC, fgelcer approved these changes
LGTM

2022-05-29 21:03 UTC, roydahan approved these changes

2022-05-29 21:06 UTC, roydahan requested changes

2022-05-29 21:06 UTC, roydahan commented on test-cases/scale/longevity-many-clients-4h.yaml
>  nemesis_interval: 5
Please add a nemesis_seed

2022-05-30 07:14 UTC, fgelcer commented
@soyacz , please add backport labels

2022-06-01 10:03 UTC, merged