fix(CQL connection): Remove unused 'user' and 'password' parameters
scylladb/scylla-cluster-tests pull request #4906
Opened 2022-06-19 15:12 UTC by yarongilor

The 'user' and 'password' parameters are not in use.
	They are explicitly set by get_db_auth() when creating a session.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-06-19 16:02 UTC, fruch commented
@yarongilor I don't think we should be removing the option, we should be fixing the code to take the user/password is supplied.

I think there are cases, like in ldap or sla, that we will want to connect as a different user.

2022-06-19 18:17 UTC, fgelcer requested changes
username and password are in use, and they cannot be removed from these functions, as they will fail, during other tests that require it configured..

what are you trying to achieve in this PR?
to just remove something you don't know where is used, is not a good practice

2022-06-20 10:05 UTC, yarongilor commented
> @yarongilor I don't think we should be removing the option, we should be fixing the code to take the user/password is supplied.
> 
> I think there are cases, like in ldap or sla, that we will want to connect as a different user.

@fruch , i'm not following what you say - if LDAP wishes to introduce a new usage of user/pwd, it is welcome to be added in a new PR.
But, currently in SCT, all features are being tested without a need of user/pwd parameters. so this PR is simply fixes a bug of unused parameters in method declaration. i see we already have LDAP tests and they are probably passing OK regardless of these 2 unused parameters. It was actually confusing and wasted time for me on another cql-fix PR.

2022-06-20 10:06 UTC, fgelcer commented
> > @yarongilor I don't think we should be removing the option, we should be fixing the code to take the user/password is supplied.
> > I think there are cases, like in ldap or sla, that we will want to connect as a different user.
> 
> @fruch , i'm not following what you say - if LDAP wishes to introduce a new usage of user/pwd, it is welcome to be added in a new PR. But, currently in SCT, all features are being tested without a need of user/pwd parameters. so this PR is simply fixes a bug of unused parameters in method declaration. i see we already have LDAP tests and they are probably passing OK regardless of these 2 unused parameters. It was actually confusing and wasted time for me on another cql-fix PR.

the LDAP feature is already in place, so no PR will be sent to fix something that you are removing

2022-06-20 10:07 UTC, yarongilor commented
> > > @yarongilor I don't think we should be removing the option, we should be fixing the code to take the user/password is supplied.
> > > I think there are cases, like in ldap or sla, that we will want to connect as a different user.
> > 
> > 
> > @fruch , i'm not following what you say - if LDAP wishes to introduce a new usage of user/pwd, it is welcome to be added in a new PR. But, currently in SCT, all features are being tested without a need of user/pwd parameters. so this PR is simply fixes a bug of unused parameters in method declaration. i see we already have LDAP tests and they are probably passing OK regardless of these 2 unused parameters. It was actually confusing and wasted time for me on another cql-fix PR.
> 
> the LDAP feature is already in place, so no PR will be sent to fix something that you are removing

great, so we can safely merge tis PR.

2022-06-20 10:09 UTC, fgelcer commented
> great, so we can safely merge tis PR.

did you run a LDAP test using your PR's code? if it passes, than maybe we can.. but i think it breaks the usage of username and password needed by LDAP (and other features as well)

2022-06-21 07:58 UTC, yarongilor commented
> > great, so we can safely merge tis PR.
> 
> did you run a LDAP test using your PR's code? if it passes, than maybe we can.. but i think it breaks the usage of username and password needed by LDAP (and other features as well)

Ldap test passed successfully. It ran 5 hours as expected (It got non related scylla 2021.1 errors of stream-mutation).
Tested  in:
https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-100gb-4h-test-ldap-yaron/3/

test_config=["test-cases/longevity/longevity-100gb-4h.yaml", "configurations/ldap-authorization.yaml"]

2022-06-21 08:33 UTC, fruch commented on sdcm/tester.py
>              username, password = credentials if credentials else (None, None)
those two line also unneeded, if username/password isn't used

2022-06-21 08:35 UTC, fgelcer commented
@k0machi , FYI

2022-06-22 10:34 UTC, yarongilor commented
Test passed OK with 2022.1 in: https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-100gb-4h-test-ldap-yaron/5/

2022-06-22 10:44 UTC, yarongilor commented on sdcm/tester.py
>              username, password = credentials if credentials else (None, None)
fixed.

2022-07-04 06:08 UTC, fgelcer commented
the solution for it is to fix where the credentials are being used, and not remove it, and expect someone who will fix it will return it in place to then fix it.

2022-07-04 06:08 UTC, closed without merging

2022-07-04 06:21 UTC, yarongilor commented
> the solution for it is to fix where the credentials are being used, and not remove it, and expect someone who will fix it will return it in place to then fix it.

@fgelcer where exactly the credentials are being used? the answer is - currently nowhere. so the best-practice and code-conventions states that unused code should not be left in files. It only make sense to leave it if there's an open task or PR that requests that.

2022-07-04 06:27 UTC, fgelcer commented
> > the solution for it is to fix where the credentials are being used, and not remove it, and expect someone who will fix it will return it in place to then fix it.
> 
> @fgelcer where exactly the credentials are being used? the answer is - currently nowhere. so the best-practice and code-conventions states that unused code should not be left in files. It only make sense to leave it if there's an open task or PR that requests that. @fruch do you have an idea if it is needed by anything?

@yarongilor , so congratulations, you just got the task to fix the misuse of the credentials...
your task is here --> https://trello.com/c/pf2BS8G8