fix(nemesis): reduce sleep time in disrupt_no_corrupt_repair nemesis
scylladb/scylla-cluster-tests pull request #4964
Opened 2022-06-30 14:25 UTC by vponomaryov

This nemesis runs repair in a separate thread and then tries to
drop 10 tables 1 by 1 sleeping for random time from 0 to 300 seconds.
The problem is that repair may get finished earlier than all the
drop table commands get run. And it can cause client call issues.

So, to minimize the probability of this problem reduce the time
we allow to sleep before makind a 'drop table' client call.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2022-06-30 16:14 UTC, fruch commented
@vponomaryov can you point to an example of this happening, what's the problem of dropping those tables one after the other ? and what do you mean by client call issue ? can you be more specific ?

also I would recommend using the same session to all of the truncate, since opening/closing sessions is just wasteful (mostly in time, under you connect to all of the shards on all of the nodes)

2022-06-30 17:44 UTC, fgelcer approved these changes
LGTM

2022-07-01 08:42 UTC, vponomaryov commented
@fruch http://13.48.103.68/test/60bb7738-cbd4-456e-8db1-489396070db3/runs?additionalRuns[]=8a05b72c-8514-4c2f-893f-96395c836102

2022-07-03 06:45 UTC, fruch commented
> @fruch [http://13.48.103.68/test/60bb7738-cbd4-456e-8db1-489396070db3/runs?additionalRuns[]=8a05b72c-8514-4c2f-893f-96395c836102](http://13.48.103.68/test/60bb7738-cbd4-456e-8db1-489396070db3/runs?additionalRuns%5B%5D=8a05b72c-8514-4c2f-893f-96395c836102)

@vponomaryov reading the explication, this is maybe nice to have, but really fixes the timeout you've got to the truncate (client issues you are referring to in the commit message, they are unrelated to whatever repair is taking place currently or not, on the contrary, if repair has finished we expect less issues with doing truncate)

also this kind of change should be backported

2022-07-17 19:22 UTC, roydahan commented
I don't think this change is needed.
It was designed to be as such and the limitations are known.

I don't think it causes any client issues or timeouts.

2022-07-17 19:22 UTC, roydahan requested changes
Not needed IMO.

2022-07-17 21:16 UTC, fruch commented
> Not needed IMO.

Me and @vponomaryov talked about this offline, the only thing I think would need to change is that the random should be seeded based on the nemesis seed, so we won't get surprises here. But that not a fix, just a way that is would be more reproduceable

2022-07-17 21:16 UTC, closed without merging