fix(upgrade): fix upgrade scylla enterprise
scylladb/scylla-cluster-tests pull request #4984
Opened 2022-07-08 13:00 UTC by soyacz

When removing with yum, some scylla config files are backed up
(e.g. `io.conf` get moved to `io.conf.rpmsave`).
When installing Scylla, this files get
default values which don't work and require full scylla setup.

This fix recovers these config files from backup after removal.
Also fixes wrong type of `workaround_kernel_bug_for_iotune` param when
`false` string was coerced to python's `True` as it was treated as
string.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-07-10 06:36 UTC, fruch commented
> It still requires testing - please don't merge it yet. Waiting for jenkins to be back.

I'm not sure it's a good direction, we first need to understand what have changed, cause we never had to do this before on upgrade (i.e. it's not part of the documented upgrade procedure, hence so first file as a bug in scylla, before we try to overcome it in SCT)

2022-07-10 07:17 UTC, fgelcer requested changes
let's first of all have an issue to Scylla, if you now know for sure that these files are being moved (as we haven't seen it in previous enterprise versions), as @fruch said, and then we proceed to merge this workaround (that should include in the docstring this one should be reverted once the Scylla issue will be fixed, or added to the documentation.

2022-07-10 07:17 UTC, fgelcer commented on sdcm/utils/scylla_install_utils.py
> +    """Since Scylla 5.0 some config files on rhel get backed up upon Scylla uninstallation.
haven't seen it for Scylla 5.0, but only for 2022.1

2022-07-11 06:45 UTC, soyacz commented
Issue created: https://github.com/scylladb/scylla-pkg/issues/2978
@fruch @fruch

2022-07-11 10:39 UTC, soyacz commented
Wrong issue, wrong fix.
Proper issue: https://github.com/scylladb/scylla-cluster-tests/issues/4987
proper fix: https://github.com/scylladb/scylla-cluster-tests/pull/4988

2022-07-11 10:39 UTC, closed without merging