fix(Full-Partition-Scan): Increase scan interval
scylladb/scylla-cluster-tests pull request #5033
Opened 2022-07-19 08:44 UTC by yarongilor

In order to decrease connection requests load on cluster by scan thread.
	Intervals of 4 large-partitions longevities are increased to 5 minutes.
	Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4960

https://trello.com/c/U3bhzNUL
## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-07-19 11:38 UTC, fgelcer requested changes
issue #4960 it was asked not only to increase the timeout, but to align the unit used (from seconds, to minutes) to be according to `run_fullscan` threads..
please change the unit to be in minutes.

2022-07-19 16:51 UTC, roydahan commented
> issue #4960 it was asked not only to increase the timeout, but to align the unit used (from seconds, to minutes) to be according to `run_fullscan` threads.. please change the unit to be in minutes.

I disagree with that.
@yarongilor wrote correctly that he leaves the units as seconds in case we want to change it back in the future.

2022-07-19 17:26 UTC, fgelcer commented
> > issue #4960 it was asked not only to increase the timeout, but to align the unit used (from seconds, to minutes) to be according to `run_fullscan` threads.. please change the unit to be in minutes.
> 
> I disagree with that. @yarongilor wrote correctly that he leaves the units as seconds in case we want to change it back in the future.

the issue this PR claims to fix, has a very clear request: `we should align the meaning of interval, and also not do the scan in such small intervals`

so if we really want to keep it in seconds to still have the ability to return to this smaller granularity, we shall change the other one to use seconds, instead of minutes..

2022-07-20 10:17 UTC, roydahan commented
Not needed.

2022-07-20 10:18 UTC, merged

2022-07-26 19:56 UTC, fgelcer commented
@roydahan , IIUC we are seeing this issue on 2022.1 Azure longevity, as the instances in there are kind of 1/2 of the ones we usually use for the parallel longevity in AWS, so i believe the cluster is super overloaded, and these full scans are surely not helping.

or maybe we should disable the full scans for Azure, until we get better quota to run the test with the resources we need?
@soyacz , WDYT?

2022-07-27 13:58 UTC, soyacz commented
I wouldn't disable it, we don't hit too many issues related to high load on 2022.1 branch (perf. is different on master - higher ops/s and load, while on 2022.1 ops/s and load is lower)