fix(get_specific_tag_of_docker_image): tag doesn't have images anymore
scylladb/scylla-cluster-tests pull request #5065
Opened 2022-07-27 10:06 UTC by fruch

seem like since the last few days the image in dockerhub doesn't
show the layers and thier digest anymore, switching
to more crude way of getting the correct version/tag
to use.

Ref: https://github.com/scylladb/scylla-pkg/issues/3009

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-07-27 12:02 UTC, vponomaryov requested changes

2022-07-27 15:36 UTC, fruch commented on sdcm/utils/version_utils.py
> +        return ret.stdout.replace('~', '-')
the idea is to get accurate response, I don't care if we'll reuse the image or not.
we will get a correct working tag out of it ? then GKE/EKS could work with that.

I prefer the API, but it's currently broken,  and not exactly clear who will fix it (not sure it's on our side)

2022-07-27 15:47 UTC, vponomaryov commented on sdcm/utils/version_utils.py
> +        return ret.stdout.replace('~', '-')
Finding bugs is our job. This particular case is the bug we must cover. Removing info from docker images is not ok. At all.
I am still sure we should just make this function be safe and not fail when docker images don't have info.

2022-07-28 14:42 UTC, vponomaryov approved these changes
LGTM

2022-07-31 09:41 UTC, juliayakovlev commented
Please, fix unittests failure

2022-07-31 11:13 UTC, fruch commented
> Please, fix unittests failure

the tests failed, cause of latest docker image was broken on dockerhub.
now it's working and passing

2022-07-31 11:18 UTC, juliayakovlev approved these changes

2022-07-31 11:39 UTC, merged