fix(longevity): adjust assymetric 12h test
scylladb/scylla-cluster-tests pull request #5235
Opened 2022-09-06 09:15 UTC by juliayakovlev

Now test runs 7 hours instead of 12. Fix it.

@roydahan @fruch 
The data set is about 140GB on every node is created. Should I decrease it or rename the test?

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-09-06 09:40 UTC, fruch commented
> Now test runs 7 hours instead of 12. Fix it.
> 
> @roydahan @fruch The data set is about 140GB on every node is created. Should I decrease it or rename the test?

I think we should change the name of the yaml  to match the size, also to match the job name (i.e. to say assymetric 12h)

also if this file is only used in this test, I see no reason to have two separate configuration for only one parameter `db_nodes_shards_selection: "random"` (I think it was premature optimization to keep that separate in it's own yaml file)

2022-09-06 13:36 UTC, roydahan requested changes

2022-09-06 13:36 UTC, roydahan commented on test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml
> +stress_cmd: ["cassandra-stress write cl=QUORUM duration=42000m  -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -mode cql3 native -rate threads=250  -col 'size=FIXED(10
4200m is 70h which is a mistake.
Also, better to set it in hours and not minutes (e.g. 12h).

2022-09-06 13:36 UTC, roydahan commented on test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml
> +instance_type_db: 'i3.2xlarge'
Why did you decrease it to 2xlarge instead of 4x?
This is a mistake, we want some nodes to have more shards.

2022-09-06 13:53 UTC, juliayakovlev commented
> The data set is about 140GB on every node is created. Should I decrease it or rename the test?

@roydahan 
The data set is about 140GB on every node is created. Should I decrease it or rename the test?

2022-09-06 13:55 UTC, juliayakovlev commented
> > Now test runs 7 hours instead of 12. Fix it.
> > @roydahan @fruch The data set is about 140GB on every node is created. Should I decrease it or rename the test?
> 
> I think we should change the name of the yaml to match the size, also to match the job name (i.e. to say assymetric 12h)
> 
> also if this file is only used in this test, I see no reason to have two separate configuration for only one parameter `db_nodes_shards_selection: "random"` (I think it was premature optimization to keep that separate in it's own yaml file)

@fruch 
AFAIR in was done by intention (separate configuration) as we wanted to use this test for non-assymetric test

2022-09-07 06:34 UTC, juliayakovlev commented
> > > > Now test runs 7 hours instead of 12. Fix it.
> > > > @roydahan @fruch The data set is about 140GB on every node is created. Should I decrease it or rename the test?
> > > 
> > > 
> > > I think we should change the name of the yaml to match the size, also to match the job name (i.e. to say assymetric 12h)
> > > also if this file is only used in this test, I see no reason to have two separate configuration for only one parameter `db_nodes_shards_selection: "random"` (I think it was premature optimization to keep that separate in it's own yaml file)
> > 
> > 
> > @fruch
> > AFAIR in was done by intention (separate configuration) as we wanted to use this test for non-assymetric test
> 
> In the end, seems no one added those non-assymetic tests.
> 
> Anyhow the name for the yaml of this specific one is vague, and doesn't say much beside wrong size of the data set.

Suggest new name, please.

2022-09-11 05:12 UTC, juliayakovlev commented
@roydahan @fruch please, review

2022-09-11 06:16 UTC, merged

2022-09-11 06:59 UTC, juliayakovlev commented
@roydahan @fruch 
I changed configuration of https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-asymmetric-cluster-12h-test/configure. Do I need to change job name?

Also I need to know when the commit will be rebased and change the job configuration in branches

2022-09-11 07:14 UTC, fruch commented
I've FF those branches and now they include those changes.
you can change in both of them

2022-09-11 07:20 UTC, juliayakovlev commented
> I've FF those branches and now they include those changes. you can change in both of them

@fruch thanks. And what about jobs name?

2022-09-11 07:22 UTC, juliayakovlev commented
> I've FF those branches and now they include those changes. you can change in both of them

. @fruch @roydahan I see this test job in 4.6 and 5.0 branches. But the test wasn't run there. Do we plan to run it?

2022-09-11 07:25 UTC, fruch commented
> > I've FF those branches and now they include those changes. you can change in both of them
> 
> . @fruch @roydahan I see this test job in 4.6 and 5.0 branches. But the test wasn't run there. Do we plan to run it?

I think that now that we figured out the issues with scylla-bench retries, we do want to run it.

2022-09-11 07:25 UTC, juliayakovlev commented
> I've FF those branches and now they include those changes. you can change in both of them

@roydahan @fruch 
also there is this job in 2022.1 branch. Change there?

2022-09-11 07:28 UTC, fruch commented
> > I've FF those branches and now they include those changes. you can change in both of them
> 
> @roydahan @fruch also there is this job in 2022.1 branch. Change there?

not yet, first let see if we backport or not.

2022-09-11 07:30 UTC, fruch commented
> > > I've FF those branches and now they include those changes. you can change in both of them
> > 
> > 
> > . @fruch @roydahan I see this test job in 4.6 and 5.0 branches. But the test wasn't run there. Do we plan to run it?
> 
> I think that now that we figured out the issues with scylla-bench retries, we do want to run it.

Here's an example of the parameters we need to add for the retries to work
https://github.com/fruch/scylla-cluster-tests/commit/441ced3ac3566e27a6f454876d463946376bee31

But I would start with smaller amount of retries, something like that:
`-timeout=30s -retry-number=30 -retry-interval=80ms,1s`

2022-09-11 07:33 UTC, juliayakovlev commented
> > > > I've FF those branches and now they include those changes. you can change in both of them
> > > 
> > > 
> > > . @fruch @roydahan I see this test job in 4.6 and 5.0 branches. But the test wasn't run there. Do we plan to run it?
> > 
> > 
> > I think that now that we figured out the issues with scylla-bench retries, we do want to run it.
> 
> Here's an example of the parameters we need to add for the retries to work [fruch@441ced3](https://github.com/fruch/scylla-cluster-tests/commit/441ced3ac3566e27a6f454876d463946376bee31)
> 
> But I would start with smaller amount of retries, something like that: `-timeout=30s -retry-number=30 -retry-interval=80ms,1s`

@fruch we do not run s-b load in this test, just c-s. Where should I add the parameters?

2022-09-11 16:42 UTC, fruch commented
Never mind, I got confused with the asymtric large partitions test, where we do use s-b

2022-09-14 07:52 UTC, fruch commented
> @fruch thanks. And what about jobs name?

in the releases leave the names, if they already have histories of runs.

it would be rename in next release

2022-12-21 11:52 UTC, juliayakovlev commented
Need be backported to `2021.1` and `2022.1` - https://github.com/scylladb/qa-tasks/issues/840#issuecomment-1359508301