fix(rolling upgrade): Create scylla-bench tables in advance
scylladb/scylla-cluster-tests pull request #5301
Opened 2022-09-20 08:32 UTC by yarongilor

In order to avoid creating it during a mixed scylla versions mode
	of cluster nodes (not supported).

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-09-20 08:41 UTC, yarongilor commented
Tested in: https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/rolling-upgrade-debian10-test-large-partitions/10/

2022-09-20 09:01 UTC, fgelcer commented
you called for the commit title `fix(rolling upgrade)`, but you change 2 different tests, `longevity_large_partition_test.py` and `performance_regression_row_level_repair_test.py` and not `upgrade_test.py`

either fix the commit title and message, or fix in the correct place

2022-09-20 09:02 UTC, fgelcer commented
> per-commit fails for: `04350dcb - fix(nemesis): skip enospc nemesis`

we know that, and we should think of a way to check whether the issue linked to that commit is closed or not, and skip it while it is not...

2022-09-21 11:59 UTC, roydahan commented
@yarongilor, 
1. who said it's not supported to create a keyspace during a mixed mode?
2. Did you prove that this is the cause of the issue?
3. Please remove the reference of this PR and your commits from the original issue because it's creating a mess.

If this is the issue, we will keep the original issue opened, but we will change the summary to describe the cause.
Then, we will provide the reproducer with the original commit (or even a simpler one if possible - e.g. a dtest).

2022-09-21 14:30 UTC, yarongilor commented
> @yarongilor,
> 
> 1. who said it's not supported to create a keyspace during a mixed mode?
Heard it from Fabio.
> 2. Did you prove that this is the cause of the issue?
No, just proved it's not reproduced without s-b stress.
> 3. Please remove the reference of this PR and your commits from the original issue because it's creating a mess.
> 
> If this is the issue, we will keep the original issue opened, but we will change the summary to describe the cause. Then, we will provide the reproducer with the original commit (or even a simpler one if possible - e.g. a dtest).

2022-09-21 14:38 UTC, fruch commented
> > @yarongilor,
> > 
> > 1. who said it's not supported to create a keyspace during a mixed mode?
> 
> 
> Heard it from Fabio.
> > 2. Did you prove that this is the cause of the issue?
> 
> 
> No, just proved it's not reproduced without s-b stress.
> > 3. Please remove the reference of this PR and your commits from the original issue because it's creating a mess.
> > 
> > If this is the issue, we will keep the original issue opened, but we will change the summary to describe the cause. Then, we will provide the reproducer with the original commit (or even a simpler one if possible - e.g. a dtest).
> 
> 

All of our upgrade guides strictly says, not to do scheme changes or topology changes during the rolling upgrade:
https://docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.x.y-to-5.x.z/upgrade-guide-from-5.x.y-to-5.x.z-ubuntu.html

2022-09-21 15:33 UTC, roydahan commented
1. Even if it's highly recommended not to do it.
I don't think it's a known issue that a repair will fail for it.

2. To prove it, run the test with your fix.

3. A much simpler fix is to run the s-b stress in the prepare phase for 1 minute or less.

2022-09-22 09:01 UTC, fgelcer commented
@yarongilor , ack

2022-09-22 14:34 UTC, fgelcer requested changes
@yarongilor , you didn't do it for the most important now, that is rolling upgrade

2022-09-25 10:17 UTC, roydahan requested changes
I don't want this change as a general change.

2022-12-01 20:44 UTC, fruch commented
@yarongilor @fgelcer if this isn't needed anymore, please close !

2023-10-22 22:04 UTC, fruch commented
there is a different work around in place already, and this isn't needed anymore

2023-10-22 22:04 UTC, closed without merging