Azure rolling upgrade 2022.2
scylladb/scylla-cluster-tests pull request #5361
Opened 2022-10-20 19:50 UTC by KnifeyMoloko

Porting PR https://github.com/scylladb/scylla-cluster-tests/pull/5337 from master branch

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [ ] ~~I added the relevant `backport` labels~~
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2022-10-21 10:33 UTC, fgelcer approved these changes
LGTM

2022-10-21 11:14 UTC, vponomaryov commented
Precommit failed, please check it: https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-5361/1/execution/node/23/log/

2022-10-21 11:16 UTC, vponomaryov requested changes
Precommit failed, please check it: https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-cluster-tests/job/PR-5361/1/execution/node/23/log/

2022-10-31 12:08 UTC, soyacz approved these changes

2022-10-31 12:08 UTC, vponomaryov approved these changes

2022-10-31 12:08 UTC, merged