test(limit): perf test for limit streaming
scylladb/scylla-cluster-tests pull request #5443
Opened 2022-11-21 14:56 UTC by soyacz

Added stream_io_throughput_mb_per_sec limit to 250gb perf test with nemesis to see the impact on latency and nemesis duration.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2022-11-21 16:05 UTC, fruch approved these changes
LGTM

2022-11-21 18:57 UTC, fgelcer approved these changes
LGTM

2022-11-21 18:58 UTC, soyacz commented
@fruch @fgelcer  I'm not sure if you are aware - this is a push to perf-v12 branch - let me know if I should follow master->backport to perf-v12

2022-11-21 19:12 UTC, fruch commented
> @fruch @fgelcer  I'm not sure if you are aware - this is a push to perf-v12 branch - let me know if I should follow master->backport to perf-v12

Yes it should go via master

2022-11-21 19:17 UTC, fgelcer commented
> > @fruch @fgelcer  I'm not sure if you are aware - this is a push to perf-v12 branch - let me know if I should follow master->backport to perf-v12
> 
> Yes it should go via master

also, IMHO we shouldn't backport this kind of feature to `branch-perf-v12`
if you need it, you can use `branch-perf-v14` (if already created, it should be), or until it is created, use master

2022-11-21 23:29 UTC, roydahan commented
1. Push it to master, not perf-v12.
2. Move it out from performance test and add it as a feature test.
We're not testing here a performance regression and comparing it across versions.
3. We may want to test in the same test, different limits.
e.g. limit to 250, run a while, change to 500, run for a while, increase, run...

2022-11-21 23:30 UTC, roydahan requested changes
See my comment above.

2022-11-22 09:22 UTC, soyacz commented
> 1. Push it to master, not perf-v12.

done

> 2. Move it out from performance test and add it as a feature test.
>    We're not testing here a performance regression and comparing it across versions.

done

> 3. We may want to test in the same test, different limits.
>    e.g. limit to 250, run a while, change to 500, run for a while, increase, run...

That is not trivial - I'd need to modify the test to update configs in the middle, maybe adding more nemesis cycles for comparison. And still it's not clear for me how this test should look like then.
Shall I invest time in it?
I think easier is to just run test with different settings multiple times.

2022-11-22 17:29 UTC, fruch commented
> > 1. Push it to master, not perf-v12.
> 
> done
> 
> > 2. Move it out from performance test and add it as a feature test.
> >    We're not testing here a performance regression and comparing it across versions.
> 
> done
> 
> > 3. We may want to test in the same test, different limits.
> >    e.g. limit to 250, run a while, change to 500, run for a while, increase, run...
> 
> That is not trivial - I'd need to modify the test to update configs in the middle, maybe adding more nemesis cycles for comparison. And still it's not clear for me how this test should look like then.
> Shall I invest time in it?
> I think easier is to just run test with different settings multiple times.
> 

Since for other feature of limit, seems like you'll need the extract out the nemesis running out of this performance test.

Should be something roughly like this:

* start stress
* configure limit
* start nemesis thread with limiting it to one round 
* Wait for nemesis thread to end
* configure new limit
* start nemesis thread with limiting it to one round 
* wait for stress to end

2022-11-23 15:50 UTC, soyacz commented
> Should be something roughly like this:
> 
> * start stress
> * configure limit
> * start nemesis thread with limiting it to one round
> * Wait for nemesis thread to end
> * configure new limit
> * start nemesis thread with limiting it to one round
> * wait for stress to end

I see one problem with that - we don't know how long it will take, so stress thread may be too long.
Maybe start/stop stress thread for each limit and get the results?

2022-11-23 15:52 UTC, fgelcer commented
> I see one problem with that - we don't know how long it will take, so stress thread may be too long. Maybe start/stop stress thread for each limit and get the results?

we (you) took care of it in the perf with nemesis jobs... "gracefully" stopping stress command when the nemesis cycle was done

2022-11-23 18:03 UTC, fruch commented
> > I see one problem with that - we don't know how long it will take, so stress thread may be too long. Maybe start/stop stress thread for each limit and get the results?
> 
> we (you) took care of it in the perf with nemesis jobs... "gracefully" stopping stress command when the nemesis cycle was done

It good enough if you build ontop getting the results out of monitor, and not from stress command summary, you can't kill the command and get the summary.

2022-11-24 12:09 UTC, soyacz commented
> > 
> > we (you) took care of it in the perf with nemesis jobs... "gracefully" stopping stress command when the nemesis cycle was done
> 
> It good enough if you build ontop getting the results out of monitor, and not from stress command summary, you can't kill the command and get the summary.

I found `latency_calculator_decorator` which does the job already by taking latency from monitor. That's why we can kill stress command without loosing results (anyway we're interested in latency during specific nemesis and stress command spans across multiple nemesis - so we don't care much about c-s results).

But `latency_calculator_decorator` collects info only for latency - is it worth to develop something similar for throughput for this test?

2022-11-24 13:15 UTC, fruch commented
> 
> > > 
> > > we (you) took care of it in the perf with nemesis jobs... "gracefully" stopping stress command when the nemesis cycle was done
> > 
> > It good enough if you build ontop getting the results out of monitor, and not from stress command summary, you can't kill the command and get the summary.
> 
> I found `latency_calculator_decorator` which does the job already by taking latency from monitor. That's why we can kill stress command without loosing results (anyway we're interested in latency during specific nemesis and stress command spans across multiple nemesis - so we don't care much about c-s results).
> 
> But `latency_calculator_decorator` collects info only for latency - is it worth to develop something similar for throughput for this test?

Yes, let's see how we can share the implemention and make it easy to track any other metrics

2022-12-22 07:05 UTC, soyacz commented
> 1. Push it to master, not perf-v12.

done

> 2. Move it out from performance test and add it as a feature test.
>    We're not testing here a performance regression and comparing it across versions.

done

> 3. We may want to test in the same test, different limits.
>    e.g. limit to 250, run a while, change to 500, run for a while, increase, run...

This could be done in separate task. @roydahan if you think it is worth the time please create one and assign.


@fgelcer please review and approve if you find it ok.

2022-12-24 02:25 UTC, fgelcer submitted a review, later dismissed
LGTM

2022-12-25 09:14 UTC, fruch commented
@soyacz please fix the unit-test `ScyllaYamlTest::test_scylla_yaml`

2022-12-27 09:35 UTC, soyacz commented
> @soyacz please fix the unit-test `ScyllaYamlTest::test_scylla_yaml`

fixed

2022-12-27 12:16 UTC, fgelcer approved these changes
LGTM

2022-12-28 06:20 UTC, fruch commented
> > 1. Push it to master, not perf-v12.
> 
> done
> 
> > 2. Move it out from performance test and add it as a feature test.
> >    We're not testing here a performance regression and comparing it across versions.
> 
> done
> 
> > 3. We may want to test in the same test, different limits.
> >    e.g. limit to 250, run a while, change to 500, run for a while, increase, run...
> 
> This could be done in separate task. @roydahan if you think it is worth the time please create one and assign.

@soyacz please create the follow up task with all the details, and we'll merge this

> 
> 
> @fgelcer please review and approve if you find it ok.

2023-01-03 13:18 UTC, soyacz commented
> @soyacz please create the follow up task with all the details, and we'll merge this

followup task:
- https://github.com/scylladb/qa-tasks/issues/950

2023-01-03 14:12 UTC, soyacz commented
@fruch if there's nothing more to do, let's merge and close it.

2023-01-08 14:04 UTC, fruch approved these changes
LGTM

2023-01-08 14:05 UTC, merged