improvement(longevity-large-partition-8h): create mview after prepare
scylladb/scylla-cluster-tests pull request #5624
Opened 2023-01-01 14:57 UTC by ShlomiBalalis

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-01-01 18:28 UTC, fruch commented
@ShlomiBalalis please add some context, as to why we need to do this change, and why it needs to be backported.

2023-01-01 18:52 UTC, fgelcer requested changes
> @ShlomiBalalis please add some context, as to why we need to do this change, and why it needs to be backported.

agree, more context is needed for such changes

2023-01-08 12:17 UTC, ShlomiBalalis commented
I first made this change to create a specific scenario for a 2022.1.4 issue. Afterwards, @roydahan requested that I'll push it to master as well.

2023-01-08 12:21 UTC, fruch commented
> I first made this change to create a specific scenario for a 2022.1.4 issue. Afterwards, @roydahan requested that I'll push it to master as well.

regardless it should be communicated with more details (even if @roydahan would see this PR, he won't necessarily remember what it's for, even if he asked for it)

2023-01-15 21:00 UTC, roydahan commented
And I don't :)

2023-01-15 21:01 UTC, roydahan commented
But IIUC it's adding a MV for large partition table (which could be enough for the commit message).

2023-01-16 19:14 UTC, fruch commented
I'm still missing the *why* are we doing this, is this trying to overcome some bug ? It's trying to expose some issue ?

2023-01-17 09:26 UTC, merged