fix(performance_email_title): Add email title parameter to pipeline
scylladb/scylla-cluster-tests pull request #5774
Opened 2023-02-06 18:37 UTC by aleksbykov

New performance jobs use several configuration files to run same test with different attributes: driver(shared/non-shard aware), hardware performance test enabling, etc). Such test when send email report results could be difficult to split.

Add new parameter to pipeline which allow to set email title for specific job.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-02-06 18:41 UTC, roydahan commented on jenkins-pipelines/perf-regression-latency-non-shard-aware-125gb.jenkinsfile
> +    test_email_title: "latency disk-and-cache - non-shard-aware",
remove "latency"

2023-02-06 18:44 UTC, roydahan requested changes

2023-02-06 18:44 UTC, roydahan commented on jenkins-pipelines/perf-regression-latency-non-shard-aware-1TB.jenkinsfile
> +    test_email_title: "latency - non-shard-aware",
same

2023-02-06 18:44 UTC, roydahan commented on jenkins-pipelines/perf-regression-latency-non-shard-aware-250gb-with-nemesis.jenkinsfile
> +    test_email_title: "latency-with-nemesis - non-shard-aware"
The current ttile of this email is already:
"(latency during operations) - test_latency_write_with_nemesis -"

2023-02-06 18:44 UTC, roydahan commented on jenkins-pipelines/perf-regression-latency-shard-aware-125gb.jenkinsfile
> +    test_email_title: "latency disk-and-cache - shard-aware",
same for latency

2023-02-06 18:44 UTC, roydahan commented on jenkins-pipelines/perf-regression-latency-shard-aware-1TB.jenkinsfile
> +    test_email_title: "latency - shard-aware",
same

2023-02-06 18:44 UTC, roydahan commented on jenkins-pipelines/perf-regression-latency-shard-aware-250gb-with-nemesis.jenkinsfile
> +    test_email_title: "latency-with-nemesis - shard-aware"
same for latency during operations

2023-02-06 19:35 UTC, fgelcer reviewed
following the logic of `latency` jobs, i have a question

2023-02-06 19:35 UTC, fgelcer commented on jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min.jenkinsfile
> +    test_email_title: "throughput - non-shard-aware",
same here

2023-02-06 19:35 UTC, fgelcer commented on jenkins-pipelines/perf-regression-throughput-shard-aware-125gb.jenkinsfile
> +    test_email_title: "throughput disk-and-cache - shard-aware",
same here

2023-02-06 19:37 UTC, roydahan approved these changes

2023-02-06 19:37 UTC, merged

2023-02-06 19:38 UTC, fgelcer commented
@roydahan , did you see my comments above?

2023-02-06 21:31 UTC, roydahan commented on jenkins-pipelines/perf-regression-throughput-non-shard-aware-125gb.jenkinsfile
> +    test_email_title: "throughput disk-and-cache - non-shard-aware",
No.

2023-02-06 21:32 UTC, roydahan commented
No, but the answer is no.

2023-02-07 14:23 UTC, fgelcer commented on jenkins-pipelines/perf-regression-throughput-non-shard-aware-125gb.jenkinsfile
> +    test_email_title: "throughput disk-and-cache - non-shard-aware",
so why was requested to remove the latency from the email titles?