fix(k8s-functional): add refresh_ip in def test_operator_managed_tls
scylladb/scylla-cluster-tests pull request #5813
Opened 2023-02-15 10:53 UTC by fruch

Since in some of the test the ip address of the pod might change and this is one of the only places we using that ip address, and not the service ip, we should refresh the address
to avoid using the old address and fail like the following:

```
E   cassandra.cluster.NoHostAvailable:
    ('Unable to connect to any servers',
    {'10.96.180.204:9142': OSError(None, "Tried connecting to
    [('10.96.180.204', 9142)]. Last error: timed out")})
cassandra/cluster.py:3617: NoHostAvailable
```

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-02-15 11:23 UTC, soyacz submitted a review, later dismissed

2023-02-15 11:36 UTC, vponomaryov approved these changes
LGTM

2023-02-15 11:45 UTC, vponomaryov commented
The fix for the CI K8S tests is here: https://github.com/scylladb/scylla-cluster-tests/pull/5815

2023-02-15 14:51 UTC, vponomaryov commented
@fruch please share the link to the run where it failed like this.
Local K8S doesn't use pod IP addresses, it uses only service IP addresses for everything.
The only thing that comes into my mind that can cause this failure is that loader discovers pod IPs itself before it changes having service IPs as specified ones...

2023-02-15 19:48 UTC, fruch commented
> @fruch please share the link to the run where it failed like this.
> Local K8S doesn't use pod IP addresses, it uses only service IP addresses for everything.
> The only thing that comes into my mind that can cause this failure is that loader discovers pod IPs itself before it changes having service IPs as specified ones...

This test doesn't use loader, it's using the python driver directly

See 
https://argus.scylladb.com/test/cc4d518c-2e17-4251-83c2-0bbf7f70ca1c/runs?additionalRuns[]=059ec41b-7e47-450f-bf7a-aa71f7232421

2023-02-17 17:41 UTC, vponomaryov commented
> > @fruch please share the link to the run where it failed like this.
> > Local K8S doesn't use pod IP addresses, it uses only service IP addresses for everything.
> > The only thing that comes into my mind that can cause this failure is that loader discovers pod IPs itself before it changes having service IPs as specified ones...
> 
> This test doesn't use loader, it's using the python driver directly
> 
> See [https://argus.scylladb.com/test/cc4d518c-2e17-4251-83c2-0bbf7f70ca1c/runs?additionalRuns[]=059ec41b-7e47-450f-bf7a-aa71f7232421](https://argus.scylladb.com/test/cc4d518c-2e17-4251-83c2-0bbf7f70ca1c/runs?additionalRuns%5B%5D=059ec41b-7e47-450f-bf7a-aa71f7232421)

Looked at the logs.
The IP that was unreachable is `10.96.180.204`.
Pod IPs:
```
sct-cluster-dc-1-kind-0     2/2     Running     0             12m     10.244.254.203   kind-worker6
sct-cluster-dc-1-kind-1     2/2     Running     0             13m     10.244.59.136    kind-worker5
sct-cluster-dc-1-kind-2     2/2     Running     7 (57s ago)   14m     10.244.195.203   kind-worker3
```

Service IPs:
```
sct-cluster-dc-1-kind-0    ClusterIP      10.96.150.140   <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9180/TCP,5090/TCP,9100/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,9160/TCP   63m    statefulset.kubernetes.io/pod-name=sct-cluster-dc-1-kind-0
sct-cluster-dc-1-kind-1    ClusterIP      10.96.133.52    <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9180/TCP,5090/TCP,9100/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,9160/TCP   71m    statefulset.kubernetes.io/pod-name=sct-cluster-dc-1-kind-1
sct-cluster-dc-1-kind-2    ClusterIP      10.96.49.1      <none>        7000/TCP,7001/TCP,7199/TCP,10001/TCP,9180/TCP,5090/TCP,9100/TCP,9042/TCP,9142/TCP,19042/TCP,19142/TCP,9160/TCP   55m    statefulset.kubernetes.io/pod-name=sct-cluster-dc-1-kind-2
```

From the above we see that the failed IP is from the `service subnet`. Not pod IP.
So, the problem is unrelated to pod IPs.
The `refresh` will help also for service IPs, if they get changed for some occassional reason.
So, we can merge it, but the same problem may appear somewhere else on local K8S while we do not use IP change tracker here. Note that for local K8S we will need to track IP changes for `service` objects, not `pod endpoints` like in case of EKS and GKE.

2023-02-17 17:45 UTC, vponomaryov requested changes
Need to change the commit description.
It is wrong and missleading.
It must be something like following:

```
Local K8S uses kind of `stable` `service IP` addresses for connections.
But it also may be recreated getting new IP address.
So, refresh IP address in the `test_operator_managed_tls` test for case target IP address gets changed.
```

2023-03-06 09:56 UTC, vponomaryov approved these changes
LGTM

2023-03-06 13:41 UTC, soyacz approved these changes

2023-03-06 13:42 UTC, merged