QA908 extend longevity coverage for azure
scylladb/scylla-cluster-tests pull request #5846
Opened 2023-02-22 16:05 UTC by Mark-Gurevich

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-02-22 19:43 UTC, fgelcer requested changes

2023-02-22 19:43 UTC, fgelcer commented on jenkins-pipelines/longevity-1tb-7days-azure.jenkinsfile
> +#!groovy
need to change file name to reflect this new job being a 5 days long, and not 7 (i know you copied from another job that had that in name, but no one bothered yet to change it to 5 days, as it requires changing multiple Jenkins jobs)

2023-02-22 19:44 UTC, fgelcer commented
@Mark-Gurevich , few things:

1. add here the link to the large partition you created
2. check why the checks failed
3. let's start running part of the nemesis jobs, but we won't be able to run all of them in parallel, so let's get some 2, and start running them ASAP

2023-03-30 16:39 UTC, fgelcer commented
@Mark-Gurevich , why is it still a draft?
we need to merge and backport this ASAP

2023-03-30 20:25 UTC, Mark-Gurevich commented
> @Mark-Gurevich , why is it still a draft? we need to merge and backport this ASAP

it was draft because you told me to hold on with running these tests until we finish with individual nemesis.
Basically, we can merge it and run the tests from the official builds.

2023-03-31 07:25 UTC, fgelcer submitted a review, later dismissed
LGTM

2023-03-31 07:25 UTC, fgelcer commented on jenkins-pipelines/longevity-1tb-5days.jenkinsfile
once this one will be merged, you need to fix the calls for it on master and enterprise jobs.
once this one will be backported to 5.2 and 2023.1 you need to fix the respective jobs to use the renamed jenkinsfile

2023-04-02 10:28 UTC, fgelcer commented
ping @roydahan

2023-04-02 11:03 UTC, roydahan commented on test-cases/longevity/longevity-large-partition-4days.yaml
replace this longevity with longevity large-partitions-8h

2023-04-03 14:36 UTC, fgelcer approved these changes
LGTM

2023-04-03 15:09 UTC, fgelcer commented
ping @roydahan

2023-04-03 19:04 UTC, roydahan commented on test-cases/longevity/longevity-large-partition-4days.yaml
This one should had been removed, but not critical for now.

2023-04-03 19:05 UTC, roydahan approved these changes

2023-04-03 19:05 UTC, merged

2023-04-03 19:05 UTC, roydahan commented
@fgelcer run the job that creates these jobs for master, 5.2 and 2023.1.

Let's start running them 1 for 5.2 and the rest on 2023.1

2023-04-04 07:23 UTC, fgelcer commented
@roydahan , we can run it, but we need this PR to be backported to the relevant branches.
@scylladb/qa-maintainers

2023-04-04 07:27 UTC, fgelcer commented
> @fgelcer run the job that creates these jobs for master, 5.2 and 2023.1.
> 
> Let's start running them 1 for 5.2 and the rest on 2023.1

creating for [5.2](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/create-sct-test-jobs-for-branch/176/) and for [2023.1](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/create-sct-test-jobs-for-branch/177/)

2023-04-04 12:35 UTC, soyacz commented
backported