improvement(MV/SI): A new nemesis to add/remove MV/SI dynamically
scylladb/scylla-cluster-tests pull request #5852
Opened 2023-02-23 12:32 UTC by yarongilor

Test adding/removing MV/SI for existing tables under running stress.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-02-27 09:06 UTC, fgelcer commented
@yarongilor --> https://github.com/scylladb/scylla-cluster-tests/pull/5841#issuecomment-1445951385

2023-02-27 19:25 UTC, fgelcer commented
so, i suggested to do all sort of creating MV + stop and start nodes, and the idea is to use as base table, something that you will create for the nemesis itself, and IMHO some 100K lines would suffice, so the verification in the end could be to read using `CL=QUORUM`, comparing the base table with the MV (that will be sync'ed after the node[s] that was[were] down will be restarted, repaired and reshaped.

2023-02-28 18:43 UTC, yarongilor commented
@fgelcer , please approve running a test with AWS instances

2023-03-01 14:58 UTC, yarongilor commented
Tested in: https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-100gb-4h-test-restart-then-repair/10/

2023-03-01 17:47 UTC, yarongilor commented
Opened issue: https://github.com/scylladb/scylladb/issues/13052

2023-03-02 06:40 UTC, soyacz reviewed
This nemesis is very limited - creates MV on a small table (100k rows), always the same.  Also scenario is very specific - this looks rather like functional test than nemesis. 

Remember to add documentation, so we can get brief overview what nemesis does without reading implementation details.

2023-03-02 08:31 UTC, roydahan requested changes
Exactly as @soyacz wrote.
If the nemesis doesn’t use the test data (in this case one of the base tables) or in other cases, the test configuration,it’s not a nemesis.

In this case, the test should look for a base table from non_system_ks_cf and create the view for it.
Then, after view building completed it should let it run for a while (e.g 2% of test_duration) and drop the view.
If we want to test view drop while building, we may want to build 2 views, one to wait for building and another to drop while building.

2023-03-02 12:34 UTC, yarongilor commented
> Exactly as @soyacz wrote. If the nemesis doesn’t use the test data (in this case one of the base tables) or in other cases, the test configuration,it’s not a nemesis.
> 
> In this case, the test should look for a base table from non_system_ks_cf and create the view for it. Then, after view building completed it should let it run for a while (e.g 2% of test_duration) and drop the view. If we want to test view drop while building, we may want to build 2 views, one to wait for building and another to drop while building.

@roydahan , @soyacz , @fgelcer ,

- the original plan suggested in the task was indeed using an existing table with data for creating MV.
- @fgelcer later suggested this different approach of using a newly created table and MV.
- So i moved from original implementation to this approach.
- We can possibly combine both approaches - one new limited table with validation. one existing table (without data validation).
- Or we can remove current implementation completely and implement only the original one.
- It's not clear why continue running for %2 of test duration that can take 2 - 3 hours. why not running for 5 - 10 minutes?
- I can add the part of removing MV as a second step of the nemesis.

2023-03-07 20:24 UTC, roydahan commented
I don't see a point to do a view building for newly created table because we already have this in our user profile.

The test should behave quite similarly to the new nemesis of building index that @soyacz introduced and use the same utils he introduced (and possibly add few more).

Regarding the 2% it was a suggestion, the idea is to have something that is relative to the test duration and not always 5 minutes. we can have 1% as well, we should start doing it for more nemesis we have or adding...

2023-06-25 09:17 UTC, closed without merging