fix(k8s): use exclusive nemesis lock for cluster health validation too
scylladb/scylla-cluster-tests pull request #5972
Opened 2023-03-31 20:32 UTC by vponomaryov

We have several exclusive nemesis which disrupt more than 1 Scylla pod from different Scylla clusters. In this case dedicated lock is used to block all other nemesis when the exclusive one gets run. But the problem with it is that when we enable cluster health validation it fails with high probability because it is not locked as side nemesis are.
So, fix the exclusive nemesis logic the way that cluster health validation gets lock'ed too.

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2023-03-31 20:33 UTC, vponomaryov commented
Tested here: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-multitenant-eks/55/consoleFull

2023-04-02 14:50 UTC, fruch commented on sdcm/nemesis.py
> +            NEMESIS_LOCK.acquire()  # pylint: disable=consider-using-with
why always acquire it ?, and not limit the locking into the case we `using is_exclusive` ones ?

2023-04-02 14:51 UTC, fruch commented on sdcm/nemesis.py
> +            NEMESIS_LOCK.acquire()  # pylint: disable=consider-using-with
I would expect it to be a mirror image of how it's being released

2023-04-02 14:52 UTC, fruch approved these changes
LGTM

2023-04-02 14:53 UTC, fruch commented on sdcm/nemesis.py
> +            NEMESIS_LOCK.acquire()  # pylint: disable=consider-using-with
I do see it exactly as it was before... still a bit weird.

2023-04-04 09:29 UTC, soyacz commented on sdcm/nemesis.py
> +                if args[0].tester.params.get('k8s_tenants_num') > 1:
If `args[0].tester.params.get('k8s_tenants_num')` returns none or not a number it will cause exception and fail releasing `NEMESIS_LOCK`

2023-04-04 09:30 UTC, soyacz requested changes
Just one remark, besides LGTM

2023-04-04 09:57 UTC, merged