fix(oracle version): use latest 2021.1 version
scylladb/scylla-cluster-tests pull request #6030
Opened 2023-04-17 12:50 UTC by fgelcer

right now, older images were deleted, hence we
had to change to use newer images, but the concept of the oracle is to use the oldest version possible to compare the results.
per @roydahan 's request, moving it to use
latest 2021.1 version (that is 2021.1.15).

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-04-17 14:38 UTC, fruch approved these changes
LGTM

2023-04-17 16:34 UTC, vponomaryov requested changes
Unit tests failed with this:

```
ValueError: AMIs for oracle_scylla_version='2021.1.15' not found in eu-west-1
```

Need to apply more changes like here: https://github.com/scylladb/scylla-cluster-tests/pull/5850/files

2023-04-20 15:37 UTC, fgelcer commented
> Unit tests failed with this:
> 
> ```
> ValueError: AMIs for oracle_scylla_version='2021.1.15' not found in eu-west-1
> ```
> 
> Need to apply more changes like here: https://github.com/scylladb/scylla-cluster-tests/pull/5850/files

done, thank you @vponomaryov

2023-04-20 16:03 UTC, vponomaryov approved these changes
LGTM

2023-04-20 19:34 UTC, roydahan approved these changes

2023-04-20 19:34 UTC, merged

2023-06-14 17:35 UTC, roydahan commented
Backported to 2023.1, 2022.2 and 5.2

I hope this would eliminate the new issue that we started seeing with timeouts on the test_oracle (regardless of the fact that we can use larger timeout in Gemini).

2023-08-28 11:49 UTC, ShlomiBalalis commented
@scylladb/qa-maintainers Can you backport this pr to branch-2022.1 as well? It still uses 4.6.9, and fails because the image doesn't exist

2023-08-28 16:32 UTC, roydahan commented
Aha too many 2's and 1's :)

2023-08-28 16:34 UTC, roydahan commented
Too many conflicts, just send a PR to that branch,  It will be easier.

2023-08-28 16:35 UTC, ShlomiBalalis commented
> Aha too many 2's and 1's :)

Tell me about it

> Too many conflicts, just send a PR to that branch, It will be easier.

Sure

2023-08-28 17:08 UTC, ShlomiBalalis commented
> Too many conflicts, just send a PR to that branch, It will be easier.

Done: https://github.com/scylladb/scylla-cluster-tests/pull/6546