feature(audit): enable audit for 2 short and 2 long longevity jobs
scylladb/scylla-cluster-tests pull request #6091
Opened 2023-05-04 06:16 UTC by fruch

Reintroduce this change that was merge directly into a release branch and now missing in master and newer release branches

This patch enabled audit for 2 short and 2 long longevity jobs.

Signed-off-by: Amos Kong <amos@scylladb.com>
(cherry picked from commit d55877128b51901710849226c69dcaebba90f77c)

## Testing

- [ ] test with OSS version -
- [ ] test with 2023.1-rc5 -

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-05-04 06:20 UTC, fgelcer requested changes
it should have new jenkinsfiles, as this is a enterprise feature only...
[from doc](https://docs.scylladb.com/stable/operating-scylla/security/auditing.html):
```This feature is only available with Scylla Enterprise. If you are using Scylla Open Source, this feature will not be available```

2023-05-04 08:08 UTC, fruch commented
> it should have new jenkinsfiles, as this is a enterprise feature only... [from doc](https://docs.scylladb.com/stable/operating-scylla/security/auditing.html): `This feature is only available with Scylla Enterprise. If you are using Scylla Open Source, this feature will not be available`

the feature won't be available, but having them in configuration should cause any issue.
I've tested it with dtest, and I'm validating it with an SCT run, we should multiple all our jobs, just for adding this to some or all enterprise runs.

2023-05-04 21:11 UTC, roydahan commented
@fruch while I understand what you're saying, this may be an issue with the current way we test releases:
- We test releases in parallel - enterprise & OSS.
- We may see differences in the behavior between the "same" jobs in enterprise vs OSS, but it'll be hard to understand what's the cause ("hidden" configuration).

I think it's better to just have special jobs for it.

2023-05-08 21:41 UTC, fruch commented
> @fruch while I understand what you're saying, this may be an issue with the current way we test releases:
> 
> * We test releases in parallel - enterprise & OSS.
> * We may see differences in the behavior between the "same" jobs in enterprise vs OSS, but it'll be hard to understand what's the cause ("hidden" configuration).
> 
> I think it's better to just have special jobs for it.

Create new ones, not sure which long one to pick 50gb-4days ?

2023-05-09 23:39 UTC, roydahan commented
Choose ones that may have interesting things in their auditing.
E.g.:
- Authourization + authentication (maybe with ldap or MS even).
- Schema changes
- Try to also have different configuration for what we audit - e.g. auditing query is going to affect performance a lot, so it should be a short longevity that doesn't stress it much.

2023-05-14 07:01 UTC, fruch commented
> Choose ones that may have interesting things in their auditing. E.g.:
> 
> * Authourization + authentication (maybe with ldap or MS even).
longevity-100gb-4h has auth, but i'll one with ldap 

> * Schema changes
in this PR selected the 3h one

> * Try to also have different configuration for what we audit - e.g. auditing query is going to affect performance a lot, so it should be a short longevity that doesn't stress it much.

those job won't have audit query to begin with, those would start with test only writing of audit.
we later would add some code that would read them.

2023-05-14 08:47 UTC, fruch commented
> > Choose ones that may have interesting things in their auditing. E.g.:
> > 
> > * Authourization + authentication (maybe with ldap or MS even).
> >   longevity-100gb-4h has auth, but i'll one with ldap
> 
> > * Schema changes
> >   in this PR selected the 3h one
> 
> > * Try to also have different configuration for what we audit - e.g. auditing query is going to affect performance a lot, so it should be a short longevity that doesn't stress it much.
> 
> those job won't have audit query to begin with, those would start with test only writing of audit. we later would add some code that would read them.


`features-ldap-authorization-and-audit-longevity-100gb-4h.jenkinsfile` already has ldap enabled

2023-05-24 12:49 UTC, fruch commented
@aleksbykov 
was `longevity-schema-changes-3h-test` ever vetted ? i.e. seem like even with SCT master branch it doesn't survive it's whole duration ?

2023-05-26 09:28 UTC, aleksbykov commented
> @aleksbykov was `longevity-schema-changes-3h-test` ever vetted ? i.e. seem like even with SCT master branch it doesn't survive it's whole duration ? see https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/longevity-schema-changes-3h-test/4/

@fruch , this jobs pass on my staging. But latest master has 2 new nemesis CreateIndex and CreateMV, and c-s failed during this nemesis. I check latest your jobs and both failed during CreateIndex nemesis with c-s error.

2023-06-06 07:58 UTC, fruch commented
> > @aleksbykov was `longevity-schema-changes-3h-test` ever vetted ? i.e. seem like even with SCT master branch it doesn't survive it's whole duration ? see https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/longevity-schema-changes-3h-test/4/
> 
> @fruch , this jobs pass on my staging. But latest master has 2 new nemesis CreateIndex and CreateMV, and c-s failed during this nemesis. I check latest your jobs and both failed during CreateIndex nemesis with c-s error.

@aleksbykov so the `longevity-schema-changes-3h-test` is broken on SCT master cause of those new nemesis ? can you open SCT issue so we can track/address it ?

@fgelcer why aren't we running `longevity-schema-changes-3h-test` in 5.2/2023.1 ? isn't it one of the raft cases that were introduced ?

2023-06-06 11:13 UTC, fgelcer commented
> @fgelcer why aren't we running `longevity-schema-changes-3h-test` in 5.2/2023.1 ? isn't it one of the raft cases that were introduced ?

yes, we are ([Argus link here](https://argus.scylladb.com/workspace?state=WyI5MGIwZGMzOC1mNzM5LTQ0OTgtOTk2My1lZjU0NGI4MjllM2UiLCIwOTYzNWFkOS00MWQ1LTQ4OGMtOWQwMC1lZWRlOTYyZWE1ZmYiXQ)), and BTW, it is waiting for @vponomaryov investigation of last run (RC6) 's failure

2023-06-06 15:51 UTC, vponomaryov commented
> > @fgelcer why aren't we running `longevity-schema-changes-3h-test` in 5.2/2023.1 ? isn't it one of the raft cases that were introduced ?
> 
> yes, we are ([Argus link here](https://argus.scylladb.com/workspace?state=WyI5MGIwZGMzOC1mNzM5LTQ0OTgtOTk2My1lZjU0NGI4MjllM2UiLCIwOTYzNWFkOS00MWQ1LTQ4OGMtOWQwMC1lZWRlOTYyZWE1ZmYiXQ)), and BTW, it is waiting for @vponomaryov investigation of last run (RC6) 's failure

https://github.com/scylladb/scylladb/issues/14162

2023-06-12 08:13 UTC, fruch commented
since https://github.com/scylladb/scylladb/issues/14162 isn't directly related to audit, I'll move forward and merge this one

2023-06-12 08:13 UTC, merged

2023-06-14 22:58 UTC, fruch commented
@fgelcer can you add those new cases to the 2023.1 runs ? and get them assigned ?
https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/audit/

one might fail on https://github.com/scylladb/scylladb/issues/14162, but maybe can reseed to not run that specific one...