fix(cluster.py): do not print false errors not finding 'cpu_set' value
scylladb/scylla-cluster-tests pull request #6190
Opened 2023-05-26 11:46 UTC by vponomaryov

Consider as error only 2+ exit codes because the '1' exit code in case of 'grep' means 'match not found' which happens always on K8S.

It will allow us to avoid lots of false error messages like following:

    > Command: 'grep "^CPUSET" /etc/scylla.d/cpuset.conf'
    >
    > Exit code: 1
    >
    > Stdout:
    >
    >
    >
    > Stderr:
    >
    >
    >

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2023-05-28 06:34 UTC, fgelcer commented on sdcm/cluster.py
> +                " || EXIT_CODE=$? ; if [[ $EXIT_CODE != 1 ]]; then exit $EXIT_CODE; fi")
shound't it be `[[ $EXIT_CODE -eq  1 ]]` ?

2023-05-28 06:45 UTC, fruch commented on sdcm/cluster.py
> +                " || EXIT_CODE=$? ; if [[ $EXIT_CODE != 1 ]]; then exit $EXIT_CODE; fi")
wouldn't it be clearer to do all this logic on the python level ?

2023-05-29 21:55 UTC, fruch requested changes
see if you can move the logic from bash to python

2023-05-30 11:13 UTC, fruch approved these changes
LGTM

2023-05-30 11:39 UTC, soyacz approved these changes

2023-05-30 11:39 UTC, merged