fix(event filter): exclude 'libabsl' from stacktrace regex
scylladb/scylla-cluster-tests pull request #6265
Opened 2023-06-19 12:19 UTC by yarongilor

SCT incorrectly reports error events for
	standard log lines of the libabsl module.
	It should be filtered out.
some scylla log prints, like in the case of core dump, generates a line like:
```
Found module libabsl_stacktrace.so.2206.0.0 with build-id: 0c356bbf44c196a8964e52aba16bd6fb494dbd9e
Metadata for module libabsl_stacktrace.so.2206.0.0 owned by FDO found: {
```
As a result, an SCT error message is created:
```
2023-05-18 05:32:17.821: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=59f779b0-60e4-4558-8860-56f615e04d0c: type=STACKTRACE regex=stacktrace line_number=53393 node=longevity-10gb-3h-2023-1-db-node-17516d2f-0-6
Found module libabsl_stacktrace.so.2206.0.0 with build-id: 0c356bbf44c196a8964e52aba16bd6fb494dbd9e
```
[argus](https://argus.scylladb.com/test/23a9f4cc-4d94-42d4-a427-6ece4fd9a487/runs?additionalRuns[]=17516d2f-2f70-4947-a58d-1810bcc129f9)

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-06-19 12:26 UTC, fgelcer approved these changes
LGTM

2023-06-19 12:57 UTC, fruch requested changes
those prints are from coredump output, and it would generate much more then this one specific event, this doesn't solve the issue

2023-06-20 07:30 UTC, yarongilor commented
> those prints are from coredump output, and it would generate much more then this one specific event, this doesn't solve the issue

@fruch , this is the only error found in the core-dump logging of this test - https://argus.scylladb.com/test/23a9f4cc-4d94-42d4-a427-6ece4fd9a487/runs?additionalRuns[]=17516d2f-2f70-4947-a58d-1810bcc129f9

Do you have any other example?

2023-06-20 14:50 UTC, fgelcer approved these changes
@yarongilor please set backport labels to required branches.
LGTM

2023-06-20 17:22 UTC, merged