fix(Argus): use  set_test_id_only in sct.py
scylladb/scylla-cluster-tests pull request #6320
Opened 2023-07-03 14:00 UTC by temichus

use set_test_id_only instead of set_test_id

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-07-03 14:04 UTC, temichus commented
tested on failed/aborted cases https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/catch-failed-runs-earlier-artifacts-amazon2-test/

https://argus.scylladb.com/workspace?state=WyJhZmY5Y2VlYS03MjlmLTQ2ZDItOTAxYi04ZjhmZTExZjk4YzkiXQ

2023-07-03 14:43 UTC, fruch approved these changes
LGTM

2023-07-03 14:44 UTC, fruch commented
@temichus 
maybe add a bit more details to the commit message to why we need to use that function and not the other

2023-07-03 15:14 UTC, vponomaryov requested changes
Please, describe `why` is it needed in the commit message.

2023-07-04 10:04 UTC, temichus commented
> Please, describe `why` is it needed in the commit message.

described

2023-07-04 10:25 UTC, vponomaryov approved these changes
LGTM

2023-07-04 10:26 UTC, vponomaryov commented
@temichus please add appropriate `backport` labels

2023-07-04 12:38 UTC, soyacz approved these changes

2023-07-04 12:38 UTC, merged