fix(LongevityOperatorMultiTenantTest): support new generic test_duration
scylladb/scylla-cluster-tests pull request #6422
Opened 2023-07-25 12:21 UTC by fruch

in #5398 new configuration option to set the test duration were introduced, and broke the k8s multi-tanent longevity like this:

```
AttributeError: 'TenantForLongevityTest-2' object has no attribute '_stress_duration'.
  Did you mean: 'test_duration'?
```

this would call the same method to get those parameters initilized

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-07-25 14:42 UTC, vponomaryov requested changes
Unit tests fail:

```
15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_longevity_class_with_shared_options - AttributeError: 'TenantForFakeLongevityTest-1' object has no attribute '_init_test_duration'
15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_longevity_class_with_unique_options - AttributeError: 'TenantForFakeLongevityTest-1' object has no attribute '_init_test_duration'
15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_performance_class_with_shared_options - AttributeError: 'TenantForFakePerformanceTest-1' object has no attribute '_init_test_duration'
15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_performance_class_with_unique_options - AttributeError: 'TenantForFakePerformanceTest-1' object has no attribute '_init_test_duration'
```

2023-07-25 14:55 UTC, fruch commented
> Unit tests fail:
> 
> ```
> 15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_longevity_class_with_shared_options - AttributeError: 'TenantForFakeLongevityTest-1' object has no attribute '_init_test_duration'
> 15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_longevity_class_with_unique_options - AttributeError: 'TenantForFakeLongevityTest-1' object has no attribute '_init_test_duration'
> 15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_performance_class_with_shared_options - AttributeError: 'TenantForFakePerformanceTest-1' object has no attribute '_init_test_duration'
> 15:35:36  FAILED unit_tests/test_utils__operator__multitenant_common.py::UtilsOperatorMultitenantCommonTests::test_multitenant_performance_class_with_unique_options - AttributeError: 'TenantForFakePerformanceTest-1' object has no attribute '_init_test_duration'
> ```

fixed

2023-07-25 15:47 UTC, fruch commented
failing unittest would be taken care of in:
https://github.com/scylladb/scylla-cluster-tests/pull/6425

2023-07-25 15:47 UTC, merged

2023-08-08 10:58 UTC, fgelcer commented
@scylladb/qa-maintainers , once backporting #5398 , this one also should be backported