fix(mv_si_4d): improve prepare stress
scylladb/scylla-cluster-tests pull request #6435
Opened 2023-07-27 11:10 UTC by fgelcer

since we introduced custom time test, this
test is having too long prepare, hence it
times out... for this improvement, we are
trying to reduce its duration by removing
all reads from prepare, increasing parallelism
and removing nemesis during prepare.

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-07-27 11:20 UTC, fgelcer commented
giving it a try [here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/custom-time/job/mv-si-4d-reduced-preparella-/2/) to confirm the improvement on the prepare part (using as custom duration 60 min)

2023-07-30 21:10 UTC, fgelcer commented
[here is a snapshot](https://snapshots.raintank.io/dashboard/snapshot/giXQct8SwsaCin1wIbGVjepPQt66oP0j) of a master run (as it was before this PR's changes) - `test_id: 9eaec735-1bef-48a3-a6c2-cea6c753c816`

[here is a snapshot](https://snapshots.raintank.io/dashboard/snapshot/C7J14qfLaFMrvPhsqfsh0Js2gOpPzprY) using this PR (the duration itself is much shorter, so here comparing only the prepare) - `test_id: f091570b-0c39-4d7a-b131-22a9feebe2b4`

2023-07-31 18:32 UTC, roydahan requested changes
Unneeded change.

2023-07-31 18:56 UTC, fruch commented
> Since we have nemesis_during_prepare here and we have a lot of milage with this longevity, I think that we don't need to change it after all.
> It's better to have 12 hours run when we have nemesis during prepare than having 12h while prepare is faster but don't have nemesis for 5h.
> 
> So, if needed we can just extend the prepare timeout (if exist) or completely remove it and discard this PR.
> 

Nemesis during preparation I can see why we'll want.

But all those extra reads during preparation, they seem a bit pointless, and look a bit like a mistake no one noticed so far.

2023-07-31 21:05 UTC, fgelcer commented
> > Since we have nemesis_during_prepare here and we have a lot of milage with this longevity, I think that we don't need to change it after all.
> > It's better to have 12 hours run when we have nemesis during prepare than having 12h while prepare is faster but don't have nemesis for 5h.
> > So, if needed we can just extend the prepare timeout (if exist) or completely remove it and discard this PR.
> 
> Nemesis during preparation I can see why we'll want.
> 
> But all those extra reads during preparation, they seem a bit pointless, and look a bit like a mistake no one noticed so far.

so, @roydahan , should i keep the nemesis during prepare, and drop the reads after all? or leave as it is today (that is not great, because it takes ~10h to prepare... what is a bit too much for the custom time test... it means, we will need to increase the prepare custom time for this job as well

2023-08-09 08:13 UTC, fgelcer commented
> Another possibility is to use large instance type, leave everything as today but increase the threads number to make sure it finishes quicker.

i will do drop the reads during prepare (they are not really needed), increase instance type, and increase even more the prepare threads, but will keep nemesis during prepare...

made the changes, giving it a run [in here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/custom-time/job/mv-si-4d-reduced-preparella-/4/) to see if it will be enough

2023-08-09 12:13 UTC, fgelcer commented
> > Another possibility is to use large instance type, leave everything as today but increase the threads number to make sure it finishes quicker.
> 
> i will do drop the reads during prepare (they are not really needed), increase instance type, and increase even more the prepare threads, but will keep nemesis during prepare...
> 
> made the changes, giving it a run [in here](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/custom-time/job/mv-si-4d-reduced-preparella-/4/) to see if it will be enough

[here is a monitor](https://snapshots.raintank.io/dashboard/snapshot/bdR1Tngpj7Ni5GeXTxiBaSj3JIj4BlK3) for that
the prepare took here 2 hours 20 minutes

2023-09-10 17:01 UTC, yarongilor reviewed
Not sure i follow - is a single write command duplicated on 2 loaders? why not splitting the content?

2023-09-13 20:01 UTC, roydahan approved these changes

2023-09-13 20:01 UTC, merged