Manager longevities and corrupt then manager repair nemesis
scylladb/scylla-cluster-tests pull request #6531
Opened 2023-08-21 17:27 UTC by ShlomiBalalis

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-08-21 17:29 UTC, ShlomiBalalis commented
@roydahan Those are just a few options that I thought could be beneficial for testing. Also considered adding an operator scenario, but wasn't sure since I see we are not testing those on releases

2023-08-21 20:08 UTC, roydahan requested changes
All looks good, just remove the unnecessary new class and use nemesis_selector.

2023-08-21 20:08 UTC, roydahan commented on jenkins-pipelines/manager/longevity-large-partition-asymmetric-cluster-ManagerOperationsMonkey-3h.jenkinsfile
If you picked the 8h I think this one isn't needed

2023-08-22 09:31 UTC, ShlomiBalalis commented on jenkins-pipelines/manager/longevity-large-partition-asymmetric-cluster-ManagerOperationsMonkey-3h.jenkinsfile
A line in the release notes made me think this test will be worth it:
`A Repair job always starts on the host with the smallest shards (cores) count`

2023-08-22 09:32 UTC, ShlomiBalalis commented on jenkins-pipelines/manager/longevity-large-partition-asymmetric-cluster-ManagerOperationsMonkey-3h.jenkinsfile
And I've yet to find an option to do so in dtest

2023-08-22 09:43 UTC, Michal-Leszczynski commented
I don't have enough SCT knowledge to validate those changes, but here are some thoughts in terms of testing repair (perhaps it's going to be useful in some other tests).

If you repair all nodes in the cluster, you can expect that SM should schedule repair jobs for all token ranges of repaired table. This means, that scheduled token ranges fully cover Int64 range [min_int_64, max_int_64]. But perhaps it's too implementation specific to include in a test?

Here is some other scenario:
- repair task starts
- it encounters errors on some ranges but it proceeds (`--fail-fast=false`)
- repair task is paused
- repair is resumed - SM will try to repair failed ranges again

Maybe it would be nice to test that SM retries failed ranges on pause/resume? But I'm not sure how you can force Scylla to return error for given repair job (in SM repo we do that by setting interceptors on client used to communicate with Scylla).

2023-08-22 09:55 UTC, ShlomiBalalis commented on sdcm/nemesis.py
> +class ManagerOperationsMonkey(SisyphusMonkey):
Done

2023-08-22 09:55 UTC, ShlomiBalalis commented on configurations/manager/manager_operations.yaml
> +nemesis_class_name: 'ManagerOperationsMonkey'
Done

2023-08-22 10:11 UTC, roydahan commented on jenkins-pipelines/manager/longevity-large-partition-asymmetric-cluster-ManagerOperationsMonkey-3h.jenkinsfile
I didn't notice it's asymmetry.
Ok, leave it.

2023-08-22 10:15 UTC, roydahan commented
@Michal-Leszczynski these are good cases, some should already be covered by SCT regression suite, some we already discussed and should be checked.

However, the relevant place to mention these is the test plan for manager 3.2.

Here @ShlomiBalalis covers only one gap for manager regression.

2023-08-27 09:41 UTC, ShlomiBalalis commented
@roydahan So do you approve the PR?

2023-08-28 00:03 UTC, roydahan approved these changes

2023-08-28 02:37 UTC, dkropachev approved these changes

2023-08-28 06:03 UTC, soyacz approved these changes

2023-08-28 06:03 UTC, merged

2023-08-28 09:37 UTC, roydahan commented
We can backport to manager branch but hold the backports to Scylla branches.
I don't know if we will ever do them.