improvement(template-longevity-5gb-1h): Add MV and large partition load
scylladb/scylla-cluster-tests pull request #6560
Opened 2023-08-31 10:40 UTC by ShlomiBalalis

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-09-03 10:07 UTC, roydahan requested changes
I suggested few changes in number of partitions, amount of rows and size of rows.
I'm not sure about the concurrency and connections count you have there.
Anyway, need few iterations of testing.

Run 1 with my suggested changes and see how it looks in terms of load.
Then, run it for several different nemesis (use the ones we set for the nightly runs).

The hardest part would be to apply it for all the nemesis jobs, I'm afraid it won't be possible using the job builder since we've done some changes to the yamls of some jobs.

2023-09-03 10:07 UTC, roydahan commented on templates/test_config/template-longevity-5gb-1h.yaml.j2
> +             "scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=25 -clustering-row-count=5555 -clustering-row-size=uniform:1024..2048 -concurrency=100 -connection-co
```suggestion
             "scylla-bench -workload=sequential -mode=read -replication-factor=3 -partition-count=1000 -clustering-row-count=555 -clustering-row-size=uniform:10..2048 -concurrency=100 -connection-count=100 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 0 -duration=60m -validate-data"
```

2023-09-06 10:20 UTC, ShlomiBalalis commented
> The hardest part would be to apply it for all the nemesis jobs, I'm afraid it won't be possible using the job builder since we've done some changes to the yamls of some jobs.

Yeah, there are several manual changes. This will be fun!

2023-09-07 15:18 UTC, ShlomiBalalis commented
Inital run passed: https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/nemesis/job/longevity-5gb-1h-CorruptThenRepairMonkey-aws-test_wih-large-partition/6/
I'll try a few different scenarios

2023-09-07 21:25 UTC, fgelcer reviewed
only thing we have discussed, and is not yet in here, is the latest changes only "adding" the diff, instead of always starting from an brand new file from template...
like in few cases, that changes were made to different parameters, we would not need to care about them, in this case...

from a little local test i did, here is how we would add the diff only:
1. read config file (if exists) and loads into a Python dict
2. generates a new config file into a Python dict
3. runs a diff between both dicts, as: `original.update(dict(set(new.items() - original.items())))`
4. save back the original config files, including the diff changes into the file

everything else, seem fine, specially seen multiple tests did have good workload, and finished with success

2023-09-07 21:25 UTC, fgelcer commented
@roydahan , this change will affect the nightly jobs

2023-09-10 16:27 UTC, ShlomiBalalis commented on sdcm/utils/nemesis.py
> +                file.write(nemesis_config_body + '\n')
I honestly think my solution is more readable. @roydahan Can you be the tie breaker?

2023-09-10 16:28 UTC, ShlomiBalalis commented
@roydahan The row size change has worked

2023-09-12 10:22 UTC, fgelcer commented
@roydahan , if this is done, i suggest getting it merged, so we can run on the official master jobs, and if there will be follow up fixes required, they should be sent as separated PRs...
so, please, review, and merge

2023-09-12 10:24 UTC, fgelcer approved these changes
LGTM

2023-09-13 19:21 UTC, roydahan commented on templates/test_config/template-longevity-5gb-1h.yaml.j2
> +prepare_write_cmd:  ["cassandra-stress write cl=QUORUM n=5048570 -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode c
Remove the compaction strategy.

2023-09-18 16:37 UTC, ShlomiBalalis commented on templates/test_config/template-longevity-5gb-1h.yaml.j2
> +prepare_write_cmd:  ["cassandra-stress write cl=QUORUM n=5048570 -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode c
Done

2023-09-18 17:52 UTC, fgelcer requested changes
pre-commit checks failed on YAML files verification... multiple of them... looks like you remove closing parenthesis/brackets

please, check and fix (according to the pre-check)

2023-09-20 09:40 UTC, ShlomiBalalis commented
> pre-commit checks failed on YAML files verification... multiple of them... looks like you remove closing parenthesis/brackets
> 
> please, check and fix (according to the pre-check)

It's funny, I didn't get any error when rebasing before, but did now when amending. I think our checks are not running during interactive rebase.
Anyway, should be fixed now.

2023-09-20 10:42 UTC, fgelcer approved these changes
LGTM

2023-09-27 17:40 UTC, roydahan approved these changes

2023-09-27 17:41 UTC, roydahan commented
Merging and hoping for the best in the nightly runs...

2023-09-27 17:41 UTC, merged

2023-09-28 07:40 UTC, fgelcer commented
i don't htink we need to backport this change to any other branches, but @roydahan WDYT?

2023-09-28 11:37 UTC, roydahan commented
We probably should, but let's see it's stable first.
The individual nemesis are already in 2023.1.