fix(rolling upgrade): disable audit
scylladb/scylla-cluster-tests pull request #6585
Opened 2023-09-07 08:55 UTC by juliayakovlev

Audit was disabled by default in 2023.1 by
https://github.com/scylladb/scylla-enterprise/pull/3094. But it is still enabled in 2022.1 and 2022.2.
It cause to error in cassandra-stress:
```
ERROR 13:04:18,965 Authentication error on host: Cannot achieve consistency level for cl ONE. Requires 1, alive 0
```

Disable audit in rolling upgrade tests to prevent this failure

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-09-07 09:03 UTC, fruch commented
@roydahan FYI, 

the idea is todo this only for 2023.1 branch, since the disable isn't gonna be backported into 2022.* branches,
and it generate too much noise for us.

2023-09-07 17:14 UTC, roydahan commented
Don't do it.
We need to test what exist in the field and not what makes the test green.

If we want to ignore this error, you can send a PR to do that.

2023-09-07 17:14 UTC, roydahan requested changes
Change is not approved

2023-09-11 08:32 UTC, juliayakovlev commented
Closed. Opened PR with another solution: https://github.com/scylladb/scylla-cluster-tests/pull/6589

2023-09-11 08:42 UTC, closed without merging