Add new kms ci jobs
scylladb/scylla-cluster-tests pull request #6606
Opened 2023-09-15 16:46 UTC by vponomaryov

## PR pre-checks (self review)

- [x] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [x] I didn't leave commented-out/debugging code
- [x] I added the relevant `backport` labels
- [ ] ~~New configuration option are added and documented (in `sdcm/sct_config.py`)~~
- [ ] ~~I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)~~
- [x] All new and existing unit tests passed (CI)
- [ ] ~~I have updated the Readme/doc folder accordingly (if needed)~~

2023-09-18 09:31 UTC, fruch commented on test-cases/longevity/longevity-encryption-at-rest-20GB-6h-multidc.yaml
> +region_aware_loader: true
we should remove it

2023-09-18 09:33 UTC, fruch commented on test-cases/longevity/longevity-encryption-at-rest-20GB-6h-multidc.yaml
> +instance_type_db: 'i3en.xlarge'
let pick a small instance, maybe i4i.2xlarge ?

2023-09-18 09:37 UTC, fruch requested changes
just changing the instance on multi-dc

2023-09-20 10:10 UTC, vponomaryov commented on test-cases/longevity/longevity-encryption-at-rest-20GB-6h-multidc.yaml
> +region_aware_loader: true
Done

2023-09-20 10:10 UTC, vponomaryov commented on test-cases/longevity/longevity-encryption-at-rest-20GB-6h-multidc.yaml
> +instance_type_db: 'i3en.xlarge'
Done

2023-09-21 08:24 UTC, vponomaryov commented
@fruch it is waiting for you?

2023-09-21 08:40 UTC, fruch approved these changes
LGTM

2023-09-21 08:40 UTC, merged