fix(nemesis jobs): Remove MVs from individual nemesis
scylladb/scylla-cluster-tests pull request #6697
Opened 2023-10-18 13:41 UTC by fruch

Since those introduced we are hitting again
and again an issue with unbounded view updates.

we are taking it out for now.

Ref: https://github.com/scylladb/scylladb/issues/15717

## PR pre-checks (self review)

- [ ] I followed [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) and [best practices](https://docs.google.com/document/d/1jihgOKb5iGRlD8_HQ92O0JbLk1kASUoZT23i_MXFSKI)
- [ ] I didn't leave commented-out/debugging code
- [ ] I added the relevant `backport` labels
- [ ] New configuration option are added and documented (in `sdcm/sct_config.py`)
- [ ] I have added tests to cover my changes (Infrastructure only - under `unit-test/` folder)
- [ ] All new and existing unit tests passed (CI)
- [ ] I have updated the Readme/doc folder accordingly (if needed)

2023-10-18 13:52 UTC, roydahan requested changes

2023-10-18 14:27 UTC, fruch commented on test-cases/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey.yaml
> -extra_network_interface: true
fixed

2023-10-18 14:27 UTC, fruch commented on test-cases/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey.yaml
> -extra_network_interface: true
fixed

2023-10-18 14:55 UTC, roydahan commented on test-cases/nemesis/longevity-5gb-1h-BlockNetworkMonkey.yaml
> -extra_network_interface: true
@fruch one more

2023-10-19 07:37 UTC, fgelcer approved these changes
LGTM

2023-10-19 08:30 UTC, soyacz approved these changes

2023-10-19 08:44 UTC, merged