feature(restart_scylla_server): add adaptive timeout
scylladb/scylla-cluster-tests pull request #7020
Opened 2023-12-27 13:40 UTC by fruch

since we have seen a few time scylla might take more time to start then we might anticipate:

```
sdcm.remote.libssh2_client.exceptions.CommandTimedOut: Command did not complete within 500 seconds!
Command: 'sudo systemctl restart scylla-server.service'
Stdout:
Stderr:
```

we now default to soft timeout of 1800s (900s for stop / 900s for start), and hard timeout of 3600s (~1h)

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevent to this change (if needed)

2023-12-27 14:20 UTC, vponomaryov requested changes
There are following precommit errors:

```
15:44:03  ************* Module sdcm.cluster_k8s
15:44:03  sdcm/cluster_k8s/__init__.py:2085:4: W0237: Parameter 'verify_up_timeout' has been renamed to 'ignore_status' in overridden 'BaseScyllaPodContainer.restart_scylla_server' method (arguments-renamed)
15:44:03  sdcm/cluster_k8s/__init__.py:2086:30: W0613: Unused argument 'ignore_status' (unused-argument)
15:44:03  
15:44:03  --------------------------------------------------------------------
15:44:03  Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)
15:44:03  
15:44:03  ************* Module sdcm.cluster_docker
15:44:03  sdcm/cluster_docker.py:160:4: W0237: Parameter 'verify_up_timeout' has been renamed to 'ignore_status' in overridden 'DockerNode.restart_scylla_server' method (arguments-renamed)
15:44:03  sdcm/cluster_docker.py:160:95: W0613: Unused argument 'ignore_status' (unused-argument)
```

2023-12-27 22:06 UTC, fruch commented
> There are following precommit errors:
> 
> ```
> 15:44:03  ************* Module sdcm.cluster_k8s
> 15:44:03  sdcm/cluster_k8s/__init__.py:2085:4: W0237: Parameter 'verify_up_timeout' has been renamed to 'ignore_status' in overridden 'BaseScyllaPodContainer.restart_scylla_server' method (arguments-renamed)
> 15:44:03  sdcm/cluster_k8s/__init__.py:2086:30: W0613: Unused argument 'ignore_status' (unused-argument)
> 15:44:03  
> 15:44:03  --------------------------------------------------------------------
> 15:44:03  Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)
> 15:44:03  
> 15:44:03  ************* Module sdcm.cluster_docker
> 15:44:03  sdcm/cluster_docker.py:160:4: W0237: Parameter 'verify_up_timeout' has been renamed to 'ignore_status' in overridden 'DockerNode.restart_scylla_server' method (arguments-renamed)
> 15:44:03  sdcm/cluster_docker.py:160:95: W0613: Unused argument 'ignore_status' (unused-argument)
> ```

fixed

2023-12-27 23:21 UTC, roydahan approved these changes

2023-12-27 23:23 UTC, merged

2023-12-31 12:42 UTC, mykaul commented
Pretty much what I've asked (long ago) @ https://github.com/scylladb/scylla-cluster-tests/issues/5438