fix(coredump): remove unnecessary info
scylladb/scylla-cluster-tests pull request #7368
Opened 2024-04-25 09:39 UTC by soyacz

We don't need details about system modules in coredump details we post in issues. Removing it from the coredump event so it's never reposted there. Fixes also download instructions.

fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7357

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-04-25 11:08 UTC, fruch approved these changes
LGTM

2024-04-25 11:08 UTC, fruch commented on sdcm/coredump.py
> +        download_instructions = 'gsutil cp gs://%s .\ngunzip %s' % (upload_url, coredump.rsplit('/', 1)[-1])
Why not use pathlib ? i.e. it's a path we are handling here..

2024-04-25 11:18 UTC, michoecho approved these changes
LGTM.

(Though I think that none of `coredumpctl info` is useful, neither the parts you filtered out nor the ones you left. I mean, it's not a bad idea to have it in the logs, but I wouldn't paste them into github issues. But that's just my opinion.)

2024-04-25 11:22 UTC, vponomaryov requested changes
Need to fix the unit tests

2024-04-25 11:30 UTC, fruch commented
> LGTM.
> 
> (Though I think that none of `coredumpctl info` is useful, neither the parts you filtered out nor the ones you left. I mean, it's not a bad idea to have it in the logs, but I wouldn't paste them into github issues. But that's just my opinion.)

When you open a bug you can pick which information you think is important, I think the backtrace can be helpful, for example if you don't have the decoded backtraces from scylla.

Anyhow there's a link to Argus, and there you can find all of the data you need, and eventually people would stop cheery-picking the wrong data

2024-04-25 13:08 UTC, soyacz commented
> Need to fix the unit tests

unit tests fixed

2024-04-30 07:48 UTC, fruch approved these changes
LGTM

2024-04-30 07:49 UTC, merged