improvement(speed): speed up wait db up
scylladb/scylla-cluster-tests pull request #7445
Opened 2024-05-17 07:20 UTC by soyacz

We wait 60 seconds between trying cql port is taken. This makes waiting for node to be up a multiply of minute (at least minute).

Speed up by checking up status every 5 seconds.
Also simplified verification of port being used to reduce number of remoter commands run on node.
Moved reporting housekeeping to background thread as we anyway don't care much about result.

refs: https://github.com/scylladb/scylla-cluster-tests/issues/7242

### Testing

- [X] - provision tests
- [X] - ami artifact test: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/artifacts-ami-test/6/
- [x] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/provision-test/24/

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-05-17 09:11 UTC, vponomaryov requested changes
Unit tests fail in a specific way to this PR. So, something is broken.

2024-05-17 09:52 UTC, soyacz commented
> Unit tests fail in a specific way to this PR. So, something is broken.

True, there was an error. Fixed it.
Still before merging I'll want to verify it with ipv6 and possibly public network - should be working, but better to be safe I think.

2024-05-17 11:45 UTC, soyacz commented
test passed except Azure where another commit broke it. Fix is here: https://github.com/scylladb/scylla-cluster-tests/pull/7446

2024-05-17 13:12 UTC, soyacz commented
I tried test with ipv6 - wait_db_up passed port check, but the test failed on later stage. More details here: https://github.com/scylladb/scylla-cluster-tests/issues/7447

Still I don't like 'worrying' error when `is_port_used` method finds port is not used:
```
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > Node longevity-10gb-3h-speed-up-db-node-e6323f19-3 [52.17.71.170 | 10.4.1.93 | 2a05:d018:12e3:f000:4eca:abac:68a4:7d4d]: Error checking for 'scylla-server' on port 9042: Encountered a bad command exit code!
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > Command: 'grep :2352 /proc/net/tcp /proc/net/tcp6'
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > Exit code: 1
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > Stdout:
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > Stderr:
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,270 f:cluster.py      l:1217 c:sdcm.cluster_aws     p:ERROR > 
< t:2024-05-17 12:40:51,271 f:wait.py         l:52   c:sdcm.wait            p:DEBUG > wait_for: Retrying db_up: attempt 1 ended with: False
```
Also I'll try with 5s interval.

2024-05-21 11:44 UTC, soyacz commented
last test with typical cluster (6db nodes, 2 loaders, 1 monitor) in progress.

Please review.

2024-05-21 15:13 UTC, soyacz commented
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/provision-test/24/ failed due external reason.
All nodes startup took ~70seconds instead 370s -> This PR brings ~300s improvement (on 'modern' cluster, previous versions gains are smaller).

2024-05-22 08:57 UTC, soyacz commented
@fruch @vponomaryov it's ready for review.

As to checks:
eks test failed - seems unrelated (test_scylla_yaml_override test failed).
Disabling test-provision tag will not help with marking checks are successful - so I cannot make checks green simply disabling this tag and rerun.
Will run it again after conflict resolution. Maybe this time passes.

2024-05-22 09:02 UTC, fruch commented on test-cases/PR-provision-test.yaml
> +nemesis_class_name: MgmtRepair
keep in mind to remove revert this

2024-05-22 09:14 UTC, fruch approved these changes
LGTM, remove the repair nemesis

2024-05-22 13:17 UTC, fruch commented on test-cases/PR-provision-test.yaml
> +nemesis_class_name: MgmtRepair
We should document open issues for those things

We can switch to not doing any nemesis, if we want to focus on provision

We could add labels for running some of the individual nemesis

2024-05-22 14:17 UTC, soyacz commented
> LGTM, remove the repair nemesis

removed.
Issue for the nemesis: https://github.com/scylladb/scylla-cluster-tests/issues/7472

2024-05-22 14:33 UTC, merged

2024-05-26 17:34 UTC, fruch commented
backport should wait for #7489 to also get backported