fix(teardown): stop sending email within SCT test
scylladb/scylla-cluster-tests pull request #7494
Opened 2024-05-28 07:12 UTC by soyacz

During SCT test we detect if it runs on jenkins. In that case we skip sending emails from within a test. But actually there's no point to send emails if not executed from jenkins either. If someone needs that, can use `hydra send-email` specifically.

Removed `send_email` from test teardown.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7477

### Testing

- [ ] - [artifact test](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/artifacts-ami-test/8/)

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-05-28 07:18 UTC, fruch requested changes
If we get rid of it, the SCT configuration needs to go too, it's not in use anymore AFAIK

2024-05-28 07:50 UTC, fruch submitted a review, later dismissed
LGTM

2024-05-28 08:09 UTC, soyacz commented
> LGTM

needed to remove also from all the configs. Testing again.

2024-05-28 09:58 UTC, vponomaryov commented
Not sure but the unit test failure may be caused by this PR:
```
11:20:48  ____________________________ TeardownFailsTest.test ____________________________
11:20:48  
11:20:48  self = <unit_tests.test_tester.TeardownFailsTest testMethod=test>
11:20:48  
11:20:48      def tearDown(self):
11:20:48          super().tearDown()
11:20:48  >       self._validate_results()
11:20:48  
11:20:48  unit_tests/test_tester.py:102: 
11:20:48  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
11:20:48  
11:20:48  self = <unit_tests.test_tester.TeardownFailsTest testMethod=test>
11:20:48  
11:20:48      def _validate_results(self):
11:20:48          super()._validate_results()
11:20:48  >       assert self.event_summary == {'NORMAL': 2, 'ERROR': 1}
11:20:48  E       AssertionError: assert {'NORMAL': 2} == {'ERROR': 1, 'NORMAL': 2}
11:20:48  E         Omitting 1 identical items, use -vv to show
11:20:48  E         Right contains 1 more item:
11:20:48  E         {'ERROR': 1}
11:20:48  E         Full diff:
11:20:48  E         - {'ERROR': 1, 'NORMAL': 2}
11:20:48  E         + {'NORMAL': 2}
```

If we consider that the sending email was always failing in unit tests then it must be updated too.

2024-05-30 07:55 UTC, fruch commented
@soyacz I'll fix the unittest

2024-05-30 08:04 UTC, fruch commented
Just moved it to a different function did that trick

2024-05-30 08:04 UTC, fruch approved these changes
LGTM

2024-05-30 08:22 UTC, vponomaryov approved these changes
LGTM

2024-05-30 08:32 UTC, merged

2024-05-30 09:29 UTC, soyacz commented
> Just moved it to a different function did that trick

THanks, sorry I didn't take it previously, but I'm busy with perf test.

2024-05-30 09:38 UTC, fruch commented
> > Just moved it to a different function did that trick
> 
> THanks, sorry I didn't take it previously, but I'm busy with perf test.

I know, that's why I'm pushing it.