fix(parallel-operations): disable when force gossip
scylladb/scylla-cluster-tests pull request #7827
Opened 2024-07-02 08:12 UTC by soyacz

When scylla yaml has `force_gossip_topology_changes` set to `True` then parallel node operations should be disabled.

Added proper handling, configuration and updated `ScyllaYaml` model.

### Testing

- [ ] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/lukasz/job/nemesis/job/longevity-5gb-1h-GrowShrinkClusterNemesis-gce-test/3/

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-07-02 09:32 UTC, fruch approved these changes
LGTM

2024-07-02 09:39 UTC, vponomaryov requested changes
Need to update unit tests.
After it LGTM.

2024-07-02 10:15 UTC, soyacz commented
> Need to update/fix unit tests. After it LGTM.

yeah, I always forget about it. 
Anyway I did one more update to disable tablets along in the configuration as test failed when creating schema (possibly due tablets enabled).

2024-07-02 10:17 UTC, fruch commented
> > Need to update/fix unit tests. After it LGTM.
> 
> yeah, I always forget about it. Anyway I did one more update to disable tablets along in the configuration as test failed when creating schema (possibly due tablets enabled).

I think we should fix those test to not be so picky about the content, we gain nothing from it.

2024-07-02 11:22 UTC, soyacz commented
> > > Need to update/fix unit tests. After it LGTM.
> > 
> > 
> > yeah, I always forget about it. Anyway I did one more update to disable tablets along in the configuration as test failed when creating schema (possibly due tablets enabled).
> 
> I think we should fix those test to not be so picky about the content, we gain nothing from it.

Anyway, fixed.
Jenkins test also looks like passing now and `Starting nodes sequentially` is in logs.

2024-07-03 11:20 UTC, aleksbykov approved these changes
LGTM

2024-07-03 20:16 UTC, merged