fix(cql-stress): update cql-stress to latest version
scylladb/scylla-cluster-tests pull request #7829
Opened 2024-07-02 13:22 UTC by soyacz

Updating cql-stress to latest version.
This version contains the fix for https://github.com/scylladb/cql-stress/pull/86

### Testing

- [ ] - integration tests, I'll take it for a ride also in different test where I need it

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-07-02 13:25 UTC, fruch commented
Let's hope my work on the integration tests paid off 🐱

2024-07-02 13:26 UTC, vponomaryov submitted a review, later dismissed
LGTM

2024-07-02 13:31 UTC, fruch approved these changes

2024-07-02 13:46 UTC, vponomaryov commented
@soyacz need also to update the version in the unit tests

2024-07-02 14:08 UTC, vponomaryov approved these changes
LGTM

2024-07-02 16:15 UTC, fruch approved these changes

2024-07-02 22:00 UTC, fruch commented
@soyacz 

FYI, this version is broken, now mixed doesn't work at all...

https://github.com/scylladb/cql-stress/pull/86#issuecomment-2204524664

2024-07-03 05:11 UTC, muzarski commented
> @soyacz
> 
> FYI, this version is broken, now mixed doesn't work at all...
> 
> [scylladb/cql-stress#86 (comment)](https://github.com/scylladb/cql-stress/pull/86#issuecomment-2204524664)

I opened a PR: https://github.com/scylladb/cql-stress/pull/96

2024-07-03 07:22 UTC, fruch commented
@soyacz 

here's an integration test that catches the issue:

```python
def test_03_cql_stress_cassandra_stress_mixed(request, docker_scylla, prom_address, params):
    loader_set = LocalLoaderSetDummy(params=params)

    cmd = (
        """cql-stress-cassandra-stress write cl=ONE duration=10s """
        """-schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=1) """
        """compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 """
        """-rate threads=10 -pop seq=1..10000000"""
    )

    write_cs_thread = CqlStressCassandraStressThread(
        loader_set, cmd, node_list=[docker_scylla], timeout=120, params=params
    )

    def cleanup_write_thread():
        write_cs_thread.kill()

    request.addfinalizer(cleanup_write_thread)

    write_cs_thread.run()
    write_cs_thread.get_results()

    cmd = (
        """cql-stress-cassandra-stress mixed cl=ONE duration=30s """
        """-schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=1) """
        """compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 """
        """-rate threads=10 -pop seq=1..10000000"""
    )

    cs_thread = CqlStressCassandraStressThread(
        loader_set, cmd, node_list=[docker_scylla], timeout=120, params=params
    )

    def cleanup_thread():
        cs_thread.kill()

    request.addfinalizer(cleanup_thread)

    cs_thread.run()

    @timeout(timeout=60)
    def check_metrics():
        output = requests.get("http://{}/metrics".format(prom_address)).text
        regex = re.compile(
            r"^sct_cql_stress_cassandra_stress_mixed_gauge.*?([0-9\.]*?)$", re.MULTILINE)
        assert "sct_cql_stress_cassandra_stress_mixed_gauge" in output

        matches = regex.findall(output)
        assert all(float(i) > 0 for i in matches), output

    check_metrics()

    output = cs_thread.get_results()
    assert "latency mean" in output[0]
    assert float(output[0]["latency mean"]) > 0

    assert "latency 99th percentile" in output[0]
    assert float(output[0]["latency 99th percentile"]) > 0
```

2024-07-03 07:50 UTC, fruch commented
I've upload the test in:
https://github.com/scylladb/scylla-cluster-tests/pull/7837

2024-07-03 07:51 UTC, fruch requested changes
we need to wait for https://github.com/scylladb/cql-stress/pull/96 to be merged
and then rebuilt the image

2024-07-18 07:27 UTC, fruch commented
@soyacz 

can you fix `test_21_nested_values` to not depend on any specific set of default images ?
it's a pointless test if it fails every time we change the defaults. it's not it's purpose whatsoever.

2024-07-18 10:31 UTC, soyacz commented
> @soyacz
> 
> can you fix `test_21_nested_values` to not depend on any specific set of default images ? it's a pointless test if it fails every time we change the defaults. it's not it's purpose whatsoever.

fixed, let's wait for the results

2024-07-22 09:04 UTC, vponomaryov approved these changes
LGTM

2024-07-22 11:11 UTC, fruch approved these changes
LGTM

2024-07-22 11:11 UTC, merged