feature(c-s): start using c-s docker image from dockerhub
scylladb/scylla-cluster-tests pull request #8206
Opened 2024-07-31 08:30 UTC by fruch

we are migrating c-s from scylla-tools-java into a new repository, and now it's has it's own docker image and releases in dockerhub, we don't need to pull in scylla old docker images for c-s anymore.

Ref: https://hub.docker.com/r/scylladb/cassandra-stress

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-07-31 16:45 UTC, CodeLieutenant submitted a review, later dismissed
LGMT

2024-08-01 10:26 UTC, fruch commented
@CodeLieutenant 

now we need to test with a few longevities to see it's working as expected

2024-08-02 05:08 UTC, soyacz approved these changes
Looks like eks-provision test failed due unrelated thing.

LGTM
Can you point to the repo of c-s?

2024-08-02 05:32 UTC, fruch commented
> Looks like eks-provision test failed due unrelated thing.
> 
> LGTM
> Can you point to the repo of c-s?

It should be under scylladb/cassandra-stress

But it wasn't yet transferred from CodeLieutenant/cassandra-stress

@CodeLieutenant should be working with @avikivity to get it into place

2024-08-02 05:33 UTC, fruch commented
We should wait with the backports for at least after seeing tier1 weekly runs

2024-08-02 07:55 UTC, CodeLieutenant commented
> @CodeLieutenant should be working with @avikivity to get it into place

I've sent the request to @avikivity for the transfer, and now, just waiting for him to accept it, and transfer it to @scylladb

2024-08-02 09:11 UTC, vponomaryov requested changes
It breaks the K8S setups:

```
sct-loaders           sct-loaders-local-dc-1-0-pod-0               0/1     StartError   0              175m    10.16.0.65      kind-worker7         <none>           <none>
sct-loaders           sct-loaders-local-dc-1-0-pod-1               0/1     StartError   0              156m    10.16.0.66      kind-worker7         <none>           <none>
```

```
    state:
      terminated:
        containerID: containerd://7f668d306719f72817730b4bf926425bc180a26b6a9ebebba75b593ff57ae8fd
        exitCode: 128
        finishedAt: "2024-08-01T11:35:23Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
```

2024-08-02 09:14 UTC, vponomaryov commented
EKS CI job passed having the same failure on loaders side.

2024-08-04 15:45 UTC, fruch commented
@CodeLieutenant 

Let's add bash, for better compatibility

2024-08-09 22:25 UTC, CodeLieutenant commented
> Let's add bash, for better compatibility

Added in [PR 9](https://github.com/scylladb/cassandra-stress/pull/9)

2024-08-12 11:22 UTC, vponomaryov commented on sdcm/stress_thread.py
> +                                                                          f' --entrypoint /bin/sh'
Why `sh` if we have `bash`?

2024-08-12 13:15 UTC, fruch commented on sdcm/stress_thread.py
> +                                                                          f' --entrypoint /bin/sh'
cause I forgot to revert it

2024-08-12 13:17 UTC, fruch commented on sdcm/stress_thread.py
> +                                                                          f' --entrypoint /bin/sh'
now it's reverted

2024-08-12 13:37 UTC, vponomaryov approved these changes
LGTM

2024-08-12 17:37 UTC, CodeLieutenant submitted a review, later dismissed

2024-08-13 09:15 UTC, vponomaryov commented
Integration test failed on the expect C-S output words:

```
17:12:03      def test_01_cql_stress_cassandra_stress(request, docker_scylla, prom_address, params):
17:12:03          loader_set = LocalLoaderSetDummy(params=params)
17:12:03      
17:12:03          cmd = (
17:12:03              """cql-stress-cassandra-stress write cl=ONE duration=1m """
17:12:03              """-schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=1) """
17:12:03              """compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 """
17:12:03              """-rate threads=10 -pop seq=1..10000000"""
17:12:03          )
17:12:03      
17:12:03          cs_thread = CqlStressCassandraStressThread(
17:12:03              loader_set, cmd, node_list=[docker_scylla], timeout=120, params=params
17:12:03          )
17:12:03      
17:12:03          def cleanup_thread():
17:12:03              cs_thread.kill()
17:12:03      
17:12:03          request.addfinalizer(cleanup_thread)
17:12:03      
17:12:03          cs_thread.run()
17:12:03      
17:12:03          @timeout(timeout=60)
17:12:03          def check_metrics():
17:12:03              output = requests.get("http://{}/metrics".format(prom_address)).text
17:12:03              regex = re.compile(
17:12:03                  r"^sct_cql_stress_cassandra_stress_write_gauge.*?([0-9\.]*?)$", re.MULTILINE)
17:12:03              assert "sct_cql_stress_cassandra_stress_write_gauge" in output
17:12:03      
17:12:03              matches = regex.findall(output)
17:12:03              assert all(float(i) > 0 for i in matches), output
17:12:03      
17:12:03          check_metrics()
17:12:03      
17:12:03          output = cs_thread.get_results()
17:12:03  >       assert "latency mean" in output[0]
17:12:03  E       IndexError: list index out of range
```

2024-08-13 20:19 UTC, fruch commented
we are using `c6i.2xlarge` for the runner, so that 8 vcpu, and 16Gb ram.
should suffice, anyhow we'll wait for occurrences of such a thing to think if it worth chasing

2024-08-13 20:21 UTC, merged