fix(disrupt_mgr): skip take_snapshot error per issue
scylladb/scylla-cluster-tests pull request #8550
Opened 2024-09-03 18:23 UTC by dimakr

We have https://github.com/scylladb/scylla-manager/issues/3389 issue that keeps repeating during scylla-manager related disruptions. It was decided to put the error symptoms/events under SkipPerIssue filter until the issue itself is attended and fixed.

### Testing
PR provision for sanity check. 

### PR pre-checks (self review)
- [] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-09-09 06:14 UTC, fruch commented on sdcm/sct_events/setup.py
> +    if SkipPerIssues('scylladb/scylla-manager#3389', params=sct_config):
let's put this logic around the mgmt repair nemesis, as a context manager

not over everything

2024-09-09 06:14 UTC, fruch requested changes
Should be specific around the nemesis in question

2024-09-09 06:14 UTC, fruch commented on sdcm/sct_events/setup.py
> +    if SkipPerIssues('scylladb/scylla-manager#3389', params=sct_config):
those error are kind of general, and it might mask them in place we don't intend like this

2024-09-10 17:22 UTC, fruch approved these changes
LGTM

2024-09-10 19:28 UTC, dimakr commented
The unit test was ok yesterday, but is failing today:
```
 FAILED unit_tests/test_base_version.py::TestBaseVersion::test_2024_2
 AssertionError: assert {'2024.1', '2024.2', '6.0'} == {'2024.1', '6.0'}
```

2024-09-10 20:32 UTC, fruch commented
> The unit test was ok yesterday, but is failing today:
> ```
>  FAILED unit_tests/test_base_version.py::TestBaseVersion::test_2024_2
>  AssertionError: assert {'2024.1', '2024.2', '6.0'} == {'2024.1', '6.0'}
> ```
> Upd: I see that 2024.2.0-rc2 was released yesterday late evening
> 

The fix for this issue is

https://github.com/scylladb/scylla-cluster-tests/pull/8612

2024-09-11 07:05 UTC, merged