test(gradual): add pipeline for gradual test with tablets
scylladb/scylla-cluster-tests pull request #9175
Opened 2024-11-12 12:28 UTC by juliayakovlev

Add Jenkins pipeline for predefined throughput steps test with tablets

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-11-12 16:52 UTC, roydahan requested changes

2024-11-12 16:52 UTC, roydahan commented on jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes-tablets.jenkinsfile
the name shouldn't include vnodes

2024-11-13 16:27 UTC, juliayakovlev commented on jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes-tablets.jenkinsfile
changed

2024-11-14 17:03 UTC, fruch submitted a review, later dismissed
LGTM

2024-11-14 17:03 UTC, fruch commented
> I would recommend adding it to the triggers as well
> 
> @roydahan you think this should be triggered weekly ? or same as other tablets cases, every 3 weeks ?

@roydahan WDYT ?

2024-11-15 00:03 UTC, roydahan commented
Weekly.

2024-11-18 19:10 UTC, fruch approved these changes
LGTM

2024-11-18 19:11 UTC, merged