improvement(azure): add instance state debug log after provision
scylladb/scylla-cluster-tests pull request #9221
Opened 2024-11-15 12:00 UTC by soyacz

Sometimes we cannot connect to Azure instance after provisioning and we don't know why.

Added debug log after provisioning instance with states info.

closes: https://github.com/scylladb/scylla-cluster-tests/issues/9201

### Testing

- [ ] - [azure artifact test](https://argus.scylladb.com/tests/scylla-cluster-tests/3e60f00a-c341-44a2-a35f-47143e56b328)

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-11-15 12:02 UTC, soyacz commented
@fruch in my opinion we get spot terminations before first ssh connection - with this PR we should see it (and if it is true, we can add code to raise proper error so it's clear during investigations).

2024-11-15 12:21 UTC, dimakr approved these changes
LGTM

2024-11-15 17:19 UTC, vponomaryov requested changes
Need to fix unit tests

2024-11-17 07:19 UTC, fruch commented
> @fruch in my opinion we get spot terminations before first ssh connection - with this PR we should see it (and if it is true, we can add code to raise proper error so it's clear during investigations).

o.k. sound reasonable to me

2024-11-18 11:52 UTC, vponomaryov approved these changes
LGTM

2024-11-18 13:02 UTC, fruch approved these changes
LGTM

2024-11-18 13:02 UTC, merged