full_storage_utilization_test: reclaim and scale out tests
scylladb/scylla-cluster-tests pull request #9305
Opened 2024-11-20 15:39 UTC by cezarmoise

Adds test cases and jenkins files for 90% storage utilization tests.
Covers these test cases:

- Space reclaim
- [x] https://github.com/scylladb/scylla-cluster-tests/issues/9169 
- [x] https://github.com/scylladb/scylla-cluster-tests/issues/9166 
- [x] https://github.com/scylladb/scylla-cluster-tests/issues/9167
- Scale out
- [x] https://github.com/scylladb/scylla-cluster-tests/issues/9256
- [x] https://github.com/scylladb/scylla-cluster-tests/issues/9257  
  These test cases are implemented as performance tests, to check that scaling out and scaling in do not cause performance issue at 90% utilization, under a 50% load.
- [x] https://github.com/scylladb/scylla-cluster-tests/issues/9597

The tests are meant to be run manually and checking their monitoring stack is part of their passing condition.

refs: https://github.com/scylladb/scylla-cluster-tests/issues/9129

### [Argus Dashboard of all cases](https://argus.scylladb.com/test_runs?state=WyJkMzE4ZWZjMi05MWIxLTQ5Y2UtOWM0Yi1mNmMwZjBhMzkyMDAiLCJiNDc0NjEzOC02OGI5LTQ0NGQtOGFlNi1jZTA3ZTZkYmMzMGUiLCI4Y2I5NWZkMS01MjdkLTQ5OTMtYjhmOC0wZjYyMTZmOTczZGUiLCIyOWJlYTNkZC0wNDljLTRhNjQtYjM2OC1kYTA2NTk2OGZlYzQiLCI4M2YzYWZmZi0yNTcyLTQ4MjYtYTJiMC0xNWM5ZTE0ZWFjZDgiLCI5MGU1ZDgwYi04Y2NlLTRkOGMtODgxNy1jM2FlYWYyNDE4MTMiXQ)

2024-11-21 08:40 UTC, cezarmoise commented
https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/1b0e85b6817bd400a91761886c3cb1853a944ca3

Also include test keyspaces when reconfiguring replication strategy to include the new dc.

Last test run: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/cezar/job/byo-longevity-test/69/consoleFull 

```
04:34:09  < t:2024-11-21 02:34:06,572 f:full_storage_utilization_test_2.py l:131  c:FullStorageUtilizationTest2 p:INFO  > Node     Total GB     Used GB      Avail GB     Used %  
04:34:29  < t:2024-11-21 02:34:28,756 f:full_storage_utilization_test_2.py l:143  c:FullStorageUtilizationTest2 p:INFO  > 1        436          396          40           91.0%
04:34:51  < t:2024-11-21 02:34:50,943 f:full_storage_utilization_test_2.py l:143  c:FullStorageUtilizationTest2 p:INFO  > 2        436          393          44           90.0%
04:35:13  < t:2024-11-21 02:35:13,134 f:full_storage_utilization_test_2.py l:143  c:FullStorageUtilizationTest2 p:INFO  > 3        436          395          42           91.0%
04:35:36  < t:2024-11-21 02:35:35,329 f:full_storage_utilization_test_2.py l:143  c:FullStorageUtilizationTest2 p:INFO  > 4        436          403          34           93.0%
04:35:36  < t:2024-11-21 02:35:35,851 f:full_storage_utilization_test_2.py l:143  c:FullStorageUtilizationTest2 p:INFO  > 5        436          37           400          9.0%
04:35:58  < t:2024-11-21 02:35:58,183 f:full_storage_utilization_test_2.py l:143  c:FullStorageUtilizationTest2 p:INFO  > 6        436          37           400          9.0%
04:36:21  < t:2024-11-21 02:36:20,536 f:full_storage_utilization_test_2.py l:143  c:FullStorageUtilizationTest2 p:INFO  > 7        436          37           400          9.0%
04:36:21  < t:2024-11-21 02:36:20,536 f:full_storage_utilization_test_2.py l:153  c:FullStorageUtilizationTest2 p:INFO  > Cluster  3052         1698         1360         56.0%
```

Did not redistribuite data to new dc.

2024-11-21 21:06 UTC, cezarmoise commented
https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/b2e8d565f4a47de0c0442375006cba40ecb7efba

Added code to put usage at certain points in the results tab, e.g. 
![Screenshot 2024-11-21 230618](https://github.com/user-attachments/assets/00a446fa-0c7b-4391-987c-0eb17d0f1e12)

2025-01-30 10:17 UTC, pehala commented
How long do think, before this PR is reviewable and out of draft?

2025-02-13 12:36 UTC, pehala commented on sdcm/nemesis.py
> +class GrowFillMoneky(Nemesis):
Will these be run also on a normal longevities?

2025-02-13 12:36 UTC, pehala commented on sdcm/nemesis.py
> +class GrowFillMoneky(Nemesis):
s/Moneky/Monkey

2025-02-13 12:36 UTC, pehala commented on test-cases/features/elasticity/elasticity-90-percent-i4i-2xlarge-drop.yaml
> +ami_id_db_scylla_desc: 'VERSION_DESC'
Why do we need this?

2025-02-13 12:36 UTC, pehala commented on data_dir/nemesis.yml
> -  - config_changes = True
was trhis change done automatically?

2025-02-13 12:36 UTC, pehala commented on jenkins-pipelines/oss/features/elasticity/elasticity-90-percent-truncate.jenkinsfile
> +    post_behavior_db_nodes: 'destroy',
I do not think we need to define as many variables as we have here

2025-02-13 12:36 UTC, pehala commented on performance_regression_test.py
> +        self.wait_no_compactions_running(n=240)
Why? And what will its effect be on rest of the performance tests

2025-02-13 12:36 UTC, pehala commented on sdcm/nemesis.py
> +            stress_cmd = f"cassandra-stress write n=400000 cl=QUORUM -mode native cql3 " \
WIll change affect other nemesis as well?

2025-02-13 12:50 UTC, cezarmoise commented on data_dir/nemesis.yml
> -  - config_changes = True
Yes, running the unit test locally changes some files.

2025-02-13 12:54 UTC, cezarmoise commented on sdcm/nemesis.py
> +            stress_cmd = f"cassandra-stress write n=400000 cl=QUORUM -mode native cql3 " \
Yes, this is a fix. Because the keyspace name was not added to the schema, it would never be created with the name we wanted.
I noticed when running `disrupt_drop`. It didn't recreate the table, so drop failed. Truncate was not affected since it leaves the table behind.

2025-02-13 12:57 UTC, cezarmoise commented on sdcm/nemesis.py
> +class GrowFillMoneky(Nemesis):
No, I named the functions without the `distrupt_` prefix. That's why I named it `Monkey` instead of `Nemesis`.
The only difference is that it is not shown in the Argus tab for nemesis, but it doesn't matter since we run it alone.
Technically, `GrowShrinkClusterNemesis` could be used instead of adding a new one.

2025-02-13 13:04 UTC, cezarmoise commented on performance_regression_test.py
> +        self.wait_no_compactions_running(n=240)
After the XFS fix we started writing more data to clusters, and for really big instances it didn't finish compactions in time.
`n` in this case is the number of retries, and it retries once per minute.
It won't effect other tests except by preventing timeout failures.

2025-02-18 12:57 UTC, cezarmoise commented
Pushed https://github.com/scylladb/scylla-cluster-tests/commit/332d00d312135677fb3bca2e8f8c152a321936ed with PR fixes:
- rebased to master
- fixed Monkey typo
- removed extra variables in jenkinfsfiles that were just the defaults

2025-02-23 15:41 UTC, pehala approved these changes

2025-02-26 09:57 UTC, pehala commented
Changing to draft, as this PR needs to be adjusted to use 3 racks

2025-03-03 09:12 UTC, cezarmoise commented on performance_regression_test.py
> +        self.wait_no_compactions_running(n=240)
This needed increased because is was too short for tests that fill an 8XL cluster to 90%

2025-03-03 09:13 UTC, cezarmoise commented on data_dir/nemesis.yml
file auto-updated by unit tests

2025-03-03 09:13 UTC, cezarmoise commented on data_dir/nemesis_classes.yml
file auto-updated by unit tests

2025-03-03 09:14 UTC, cezarmoise commented on performance_regression_test.py
> +        if self.params.get('pre_create_keyspace'):
This allows pre-creating the test keyspaces and set initial tablets to them, same as longevity tests.

2025-03-03 09:18 UTC, cezarmoise commented on sdcm/nemesis.py
> +    def add_new_nodes_to_racks(self, count, racks, instance_type: str = None) -> list[BaseNode]:
Compared to `add_new_nodes`, this allows adding nodes to different racks without waiting for tablet migration

2025-03-03 09:24 UTC, cezarmoise commented
Changes:
- b516630f937aef6b130bff5d42424109a7e2732f
  - cherry-picked from https://github.com/scylladb/scylla-cluster-tests/pull/10099 to allow setting initial tablets

- ef341e26be3687e412321d48c79c68424c241ebe
  - add new methods for growing a cluster on each rack
  - this could probably be merged with the existing methods

- e3253a6e14c24e6980100c000b3dee1ccafc4104
  - updated all tests to use 3 availability zones (3 racks)
  - updated all tests to use 3 loaders (1 per rack)
  - updated all tests' initial write commands to have 1 stress write per loader
  - improve amount of data in the initial write to be closer to 90%

2025-03-03 09:30 UTC, cezarmoise commented on sdcm/tester.py
> +                self.log.exception("Error while checking regression")
This logs a traceback of the error.

For example, if a test does not have `use_hdrhistogram: true`, then the error would be 
> 2025-03-02 13:55:20.759: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=f0a49a5c-6891-43c3-8f99-85b5798e090f, source=PerformanceRegressionTest.check_regression() message=Failed to check regression
exception='NoneType' object is not iterable

which is not useful at all

2025-03-07 13:13 UTC, cezarmoise commented
https://github.com/scylladb/scylla-cluster-tests/commit/3a5d3fb88c3f426ba4a80e030fa7e788484782bb

- cleaned up commits
- removed commits that were unrepeated (moved to other PRs)
- use GrowShrinkClusterNemesis instead of writing new code

2025-03-11 08:48 UTC, pehala commented on data_dir/nemesis.yml
> +- disrupt_add_remove_dc: []
I would say this nemesis should have some flags

2025-03-11 09:22 UTC, pehala commented on data_dir/nemesis.yml
> +- disrupt_add_remove_dc: []
I know, but it means you did not include any flags for your nemesis. I think it should be marked appropriately

2025-03-11 09:28 UTC, cezarmoise commented on data_dir/nemesis.yml
> +- disrupt_add_remove_dc: []
`disrupt_add_remove_dc` is an existing nemesis, not added by this PR

2025-03-12 13:25 UTC, Lakshmipathi commented on test-cases/features/elasticity/elasticity-90-percent-perf-i4i-large-grow-i4i-4xlarge.yaml
> +parallel_node_operations: true
we dont need `auto_snapshot: false` for this config file?

2025-03-12 14:05 UTC, cezarmoise commented on test-cases/features/elasticity/elasticity-90-percent-perf-i4i-large-grow-i4i-4xlarge.yaml
> +parallel_node_operations: true
I only used that for the reclaim tests, so as to make it faster by not waiting for compaction to reclaim space.

2025-03-13 14:39 UTC, cezarmoise commented
https://github.com/scylladb/scylla-cluster-tests/commit/739c4f4e7820826fc8cd246d3ea194387b67373b: rebase to fix PR checks

2025-03-14 14:08 UTC, cezarmoise commented
https://github.com/scylladb/scylla-cluster-tests/commit/295827a8ba25756a97f717e7d694be17bd2a1210 use pre_create_keyspace for ttl case instead of user profile.

2025-03-18 09:49 UTC, cezarmoise commented
https://github.com/scylladb/scylla-cluster-tests/commit/734bfb4cf03f78bee3953d3ae55b90d4bf9d3d41 update workload on grow larger test case to be the same as grow smaller, since they use the same instance types

2025-03-18 10:47 UTC, pehala submitted a review, later dismissed

2025-03-20 15:20 UTC, cezarmoise commented
Ci is failing due to https://github.com/scylladb/scylla-cluster-tests/issues/10450

2025-03-20 16:31 UTC, roydahan requested changes
While I understand the approach of trying to utilize the peformance regression test with nemesis, the new nemesis that were added here aren't comply with the concept of nemesis and they will probably break all other longevities.

If you do it only to utlize the context manager of measuring latency or something like that, there are are probably better ways to do it.

Also, the commit message isn't descriptive enough to explain the motivations and the changes you want to introduce and their reasons.

2025-03-20 16:35 UTC, roydahan commented
One more thing, regardless of my review above.
If you would want to introduce new nemesis (which again, shouldn't be the case IMO here), the testing of this PR should have cover much much more than your cases, proving they won't break our longeivites.
Sample of such testing:
1. Several longevities running only these nemesis multiple times.
2. Several longevities running multiple nemesis which this nemesis is part of them.
3. Parallel longevities that includes this nemesis from one of our existing cases.

2025-03-20 16:52 UTC, vponomaryov requested changes

2025-03-20 16:52 UTC, vponomaryov commented on sdcm/nemesis.py
> +            self.tester.verify_stress_thread(stress)
Agree with @roydahan 

About the current approach:
At first, many scenarios have only "reads" as a main stress configured in the `stress_cmd` config option, reads do not add more data, obviously.
At second, above comment `write more data to the cluster` is false.
Running the same command we create load, but we re-write the same data.
So, there will be no `more data` and no change in the used disk space.

2025-03-20 16:52 UTC, vponomaryov commented on sdcm/nemesis.py
> +class GrowFillMonkey(Nemesis):
+1

2025-03-27 13:51 UTC, cezarmoise commented on sdcm/nemesis.py
> +class DropMonkey(Nemesis):
I didn't find any nemesis that just does a drop.
But I don't really need it since I can just put `post_prepare_cql_cmds`

Removed in https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/cf3c25725d7ed467c9e8ca0c5911d6c5b2632efd

2025-03-27 13:52 UTC, cezarmoise commented on sdcm/nemesis.py
> +class GrowFillMonkey(Nemesis):
Removed, refactored as test_custom_time.

https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/d9f61e10b4846c8ddea0770a570e9d84d2d3c6ed and https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/605e613008c6ae56a02e433066aa155363c6ad1b

2025-03-27 13:59 UTC, cezarmoise commented
Changes:
- https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/cf3c25725d7ed467c9e8ca0c5911d6c5b2632efd: uses only existing nemesis and parameters for tests
- https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/79e27826691139145e3dd1e475897e68e5b97340: updated commit message
- https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/d9f61e10b4846c8ddea0770a570e9d84d2d3c6ed: add parameter to allow longevity test to grow with a different cluster type than the initial cluster
- https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/605e613008c6ae56a02e433066aa155363c6ad1b: refactored old nemesis into longevity test

2025-03-27 14:07 UTC, cezarmoise commented on sdcm/nemesis.py
> +            self.tester.verify_stress_thread(stress)
My understanding was that if the function is not named `distrupt_`, it will not be picked up by Sisyphus.
But I refactored it out in https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/605e613008c6ae56a02e433066aa155363c6ad1b

2025-04-07 08:18 UTC, cezarmoise commented
@scylladb/qa-maintainers please review

2025-04-07 14:31 UTC, vponomaryov commented on test-cases/features/elasticity/elasticity-90-percent-i4i-2xlarge-truncate.yaml
> +  "cassandra-stress write no-warmup cl=QUORUM n=480000000 -schema keyspace=ks_truncate 'replication(strategy=NetworkTopologyStrategy,replication_factor=3)' -mode cql3 native -rate threads=200 -col 's
We have nemesis `disrupt_truncate` which uses exactly the same keyspace name -> `ks_truncate`.
And the `nemesis_during_prepare` SCT config option is enabled by default...

So, to avoid possible unexpected problems, I recommend renaming all the new keyspaces here to some more unique names like `ks_90percent_util_truncate`...

2025-04-07 14:31 UTC, vponomaryov commented on test-cases/features/elasticity/elasticity-90-percent-perf-i4i-2xlarge-grow-fill-i4i-large.yaml
> +test_duration: 2880
Where is this new config file is used?
Missing jenkinsfile for it?

2025-04-11 13:39 UTC, cezarmoise commented on test-cases/features/elasticity/elasticity-90-percent-i4i-2xlarge-truncate.yaml
> +  "cassandra-stress write no-warmup cl=QUORUM n=480000000 -schema keyspace=ks_truncate 'replication(strategy=NetworkTopologyStrategy,replication_factor=3)' -mode cql3 native -rate threads=200 -col 's
renamed in https://github.com/scylladb/scylla-cluster-tests/pull/9305/commits/8e62b9fa81650c190269b5b98dca562883683fe1

2025-04-14 08:57 UTC, pehala approved these changes

2025-05-09 08:12 UTC, pehala commented
> @scylladb/qa-maintainers please review

re-ping

2025-05-09 13:42 UTC, soyacz reviewed
It's very hard to verify if this PR is ok:
1. I miss docstrings for these cases - I propose to add intention on top of each yaml
2. e.g. `elasticity-90-percent-perf-i4i-8xlarge-grow-fill-i4i-large.yaml` test linked(??) to https://github.com/scylladb/scylla-cluster-tests/issues/9597#issuecomment-2633291581doesn't match - I can see drops of throughput, and actually I don't see throttling.
3. It's hard to look at selected test results... - I don't know which yaml refers to which run id.

Next time I propose to create separate PR's for each case.

2025-06-01 19:34 UTC, cezarmoise commented
closed if favor of https://github.com/scylladb/scylla-cluster-tests/pull/10999, https://github.com/scylladb/scylla-cluster-tests/pull/11000 and https://github.com/scylladb/scylla-cluster-tests/pull/11001

2025-06-01 19:34 UTC, closed without merging