fix(nemesis-target-pool): set method attribute for target pool
scylladb/scylla-cluster-tests pull request #9517
Opened 2024-12-09 18:47 UTC by aleksbykov

Decorator `disrupt_method_wrapper` rewrites target node pool and always set Nemesis._target_node_pool as data_nodes. This cause that target node is chosen from cluster.data_nodes always. This happemed because we have decorators chain:
disrupt_method_wrapper -> target_(data/zero/all)_nodes -> disrupt_*

Target node is chosen in `disrupt_method_wrapper`, and any changes in target_*_pool does not affect of target node if it is run in complex nemesis as SisyphusMonkey and also has affect in parallel nemesis run

Set method attribute disrupt_*.target_pool for later use in decorator `disrupt_method_wrapper`, allows correctly set target pool for disrupt nemesis

### Testing

- [ ]

### PR pre-checks (self review)

- [ ] I added the relevant `backport` labels
- [ ] I didn't leave commented-out/debugging code

### Reminders

- Add New configuration option and document them (in `sdcm/sct_config.py`)
- Add unit tests to cover my changes (under `unit-test/` folder)
- Update the Readme/doc folder relevant to this change (if needed)

2024-12-09 21:56 UTC, fruch commented
@aleksbykov 

see #9502 

you still have this in you PR inside `set_targer_node()`, and it won't work cause `_target_node_pool` is not a list of nodes anymore:
```
nodes = [node for node in self._target_node_pool if not node.running_nemesis]
```

2024-12-09 22:00 UTC, fruch requested changes
it's not enough just to move the assigning  to `_target_node_pool` form the decorators
`_target_node_pool` shouldn't hold a list of nodes ontop of the nemesis class.

set_target node should alway look at cluster current nodes lists, and not cache anything in that regards

2024-12-10 08:50 UTC, aleksbykov commented
> @aleksbykov
> 
> see #9502
> 
> you still have this in you PR inside `set_targer_node()`, and it won't work cause `_target_node_pool` is not a list of nodes anymore:
> 
> ```
> nodes = [node for node in self._target_node_pool if not node.running_nemesis]
> ```

@fruch , i took a look into your PR. It also will have same problem even with node type, because  the disrupt_wrapper will always use the data_nodes, and target node has been chosen before, the node_pool_type would changed by decorator

2024-12-10 09:10 UTC, aleksbykov commented
@fruch , can you take a look. I use your solution related to storing pool type

2024-12-10 11:44 UTC, aleksbykov commented
Jobs with this fixed passed (main funcitonality) error messages not related to fix:
 - https://argus.scylladb.com/tests/scylla-cluster-tests/a3de455c-ef14-44a0-a173-04db281f9f0c
 - https://argus.scylladb.com/tests/scylla-cluster-tests/55f9cd42-4182-49e3-8eb0-a42b4feb7da8 - Passed

2024-12-10 16:38 UTC, temichus approved these changes

2024-12-10 19:12 UTC, merged