feature(views-with-tablets): enable testing materialized views with tablets
scylladb/scylla-cluster-tests pull request #9615
Opened 2024-12-24 13:54 UTC by wmitros

We plan to disallow materialized views in tablet keyspaces, until the remaining issues with them
are resolved. For that, we've introduced the "views-with-tablets" experimental feature, so that
they can be enabled regardless, for example for testing. Currently, the feature has no effect,
but we want to prepare the cluster tests to use it, so that they won't start failing when it
starts actually having an effect.

While improving views with tablets, we should make sure that the existing tests keep passing,
so we should run materialized view (and index) tests with tablets using the experimental feature.

The feature doesn't affect tests ran on vnodes. For tablets, the tests would fail without the feature
due to unsupported configuration.

Considering that, we should enable the feature by default for all tests running on 2025.1 or later.

The change includes:
* adjusting experimental_features based on scylla version in sct_config, setting the new feature
when running on 2025.1 or later
* adding a new parameter "enable_views_with_tablets_on_upgrade". When it's set, we enable the new
feature in upgrade_test.py after upgrading a node. Currently, there are no upgrade tests to 2025.1,
so it isn't used
* adding a config file configurations/enable_views_with_tablets_on_upgrade.yaml that enables the
mentioned parameter without setting an env variable

2024-12-24 14:30 UTC, wmitros commented
Looks like yaml tests aren't using the default configurations, fixed in rebase

2025-01-13 07:38 UTC, piodul commented
@wmitros why is this PR a draft? What is missing?

2025-01-14 14:01 UTC, piodul commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
> When testing upgrades to future versions, we'll need to
> keep the experimental_feature also for base version, with an exception for sequential upgrades,
> (currently we only have 2021.1->2022.1->2023.1 test in test_custom_profile_sequential_rolling_upgrade)
> where the base version of the sequence might not have this experimental feature, so we'll need
> to adjust it accordingly.

It would be great if the feature were enabled programmatically for the base version as well, but I'm not familiar with SCT enough to tell you how to do that. @fruch perhaps you will know?

If it's not feasible, alternatively you could add a comment near the `experimental_features` key which explains when the `views-with-tablets` feature needs to be provided and when not.

2025-01-14 14:01 UTC, piodul commented on upgrade_test.py
> +            scylla_yaml_updates.update({"experimental_features": ["views-with-tablets"]})
Do we need something similar in `_rollback_node`, too?

2025-01-15 22:06 UTC, wmitros commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
> > Materialized views are currently not allowed in tablet keyspaces, due to some
> > pending issues. However, they can be enabled using the "views-with-tablets" experimental feature.
> 
> This is not technically true, they can be created in tablet keyspaces right now but we want to forbid this. 

I updated the description for the current state




> It would be great if the feature were enabled programmatically for the base version as well, but I'm not familiar with SCT enough to tell you how to do that. @fruch perhaps you will know?

I'm not sure there is such a way in general for all tests. I saw that when tablets were introduced, we added a `enable_tablets_on_upgrade` config option that we used on specific test pipelines - we could probably do something like that here as well, but currently no tests would use it, as we don't have tests for upgrading to 2025.1, and the developers that were adding these tests would have to remember about it.

> If it's not feasible, alternatively you could add a comment near the `experimental_features` key which explains when the `views-with-tablets` feature needs to be provided and when not.

For now I added a comment for the `experimental_features` configuration option

2025-01-16 06:08 UTC, fruch commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
The only downside of using this in default for everything, that is gonna block people from using older versions

And it's gonna waste lots of people's time,

We are using older releases during development

I think this is different from the regular extra configuration in scylla yaml that wasn't there before, and existence of it does not break anything 

I think moving it into the with the same version logic you used in upgrade tests

2025-01-16 06:09 UTC, fruch commented on upgrade_test.py
> +            scylla_yaml_updates.update({"experimental_features": ["views-with-tablets"]})
I don't know, someone need to cross check it in the code 

Anyhow I would recommend appending to the flags, now the code is override anything that any might have put in there before

2025-01-16 10:57 UTC, piodul commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
Older versions of scylla which do not support this experimental feature will not recognize it, and will fail to start. If we are using SCT with older versions of scylla then it sounds like it will be a problem.

@fruch is there a way to adjust the configuration programmatically?

I found an old PR which _removed_ the experimental "tablets" feature from SCT (https://github.com/scylladb/scylla-cluster-tests/pull/7512). It looks like the approach there was to modify Jenkinsfiles (`configurations/raft/enable_raft_experimental.yaml`). Would it be a viable approach here instead of adding "views-with-tablets" to the list of default features?

2025-01-16 18:39 UTC, vponomaryov requested changes

2025-01-16 18:39 UTC, vponomaryov commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
@piodul 
I agree with @fruch that defaults must not limit us to only one scylla version.
For example, I use various scylla versions with the `master` SCT branch all the time.

Yes, additional small file in the `configurations` is good solution.

Also, note that each CI job can be provided with the updated SCT config option in the jenkins pipeline `extra_environment_variables` parameter.
One of the recent examples:
![Screenshot from 2025-01-16 20-08-09](https://github.com/user-attachments/assets/323b076e-2834-4d69-8883-5880fba4f2b3)

In this case it is not needed to update SCT configs.

So, choose whatever fits your needs better.

2025-01-16 18:39 UTC, vponomaryov commented on docs/configuration_options.md
> +Unlock specified experimental features. The 'views-with-tablets` feature is enabled in the default configuration, but it should not be enabled when testing versions older than 2025.1-dev or 6.3-dev
6.3-dev won't exist

2025-01-16 18:39 UTC, vponomaryov commented on upgrade_test.py
> +            scylla_yaml_updates.update({"experimental_features": ["views-with-tablets"]})
We restore original scylla.yaml file. See following:
https://github.com/scylladb/scylla-cluster-tests/blame/c22fba4d/upgrade_test.py#L434

2025-01-16 21:34 UTC, nyh commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
By the way, today I was hit with the same problem in test/cqlpy/run's "--release" feature which is supposed to allow running old versions of Scylla, but the newly added views-with-tablets doesn't work on old versions. My fix is https://github.com/scylladb/scylladb/pull/22350. Basically test/cqlpy/run.py has a rather-ugly list of configuration "overrides", specific options that need to be added or removed from specific past versions. This list is ugly, but isn't long or hard, and I'm rather please with the power it gives me to run tests against old versions (e.g., just today in https://github.com/scylladb/scylladb/pull/22354 I wrote a test and then ran it against 10 different versions of Scylla).

2025-01-16 23:17 UTC, fruch commented on upgrade_test.py
> +        if self.is_enterprise and version >= "2025.1.0~dev" or not self.is_enterprise and version >= "6.3.0~dev":
6.3.0-dev does exists, it never gonna be released
since today master is 2025.1.0-dev, so we can drop it now

2025-01-16 23:26 UTC, fruch commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
@piodul 

there two place we can do it programmatically: 
1) in `proposed_scylla_yaml`, where we read `append_scylla_yaml` and use it
2) in `sct_config.py` after `sct_config.get_version_based_on_conf()` is called, and we have the version information

the first is the simplest, but it's buried in not so clear place
the 2nd might be better and clear place for more changes per release we need to do in SCT configuration.

2025-01-19 23:36 UTC, wmitros commented on docs/configuration_options.md
> +Unlock specified experimental features. The 'views-with-tablets` feature is enabled in the default configuration, but it should not be enabled when testing versions older than 2025.1-dev or 6.3-dev
Ok, I removed 6.3 from the description

2025-01-19 23:36 UTC, wmitros commented on upgrade_test.py
> +        if self.is_enterprise and version >= "2025.1.0~dev" or not self.is_enterprise and version >= "6.3.0~dev":
I removed 6.3 mentions in the new version

2025-01-19 23:37 UTC, wmitros commented on defaults/test_default.yaml
> +experimental_features: ['views-with-tablets']
> 2. in `sct_config.py` after `sct_config.get_version_based_on_conf()` is called, and we have the version information


I added a new method for changing the config based on the release in `sct_config.py` after `sct_config.get_version_based_on_conf()`, please take a look

2025-01-19 23:40 UTC, wmitros commented
In the new version I change the `views-with-tablets` feature to be enabled programmatically, based on the version.
I also added a new config parameter `enable_view_with_tablets_on_upgrade` to be used for 2025.1 upgrade tests

2025-01-20 09:54 UTC, wmitros commented on docs/configuration_options.md
> +
Removed

2025-01-20 09:54 UTC, wmitros commented on sdcm/sct_config.py
> +            self['experimental_features'] = ['views-with-tablets']
I don't think any test is currently using other experimental features, but it should be possible for new/manual tests. Added in rebase

2025-01-20 09:54 UTC, wmitros commented on sdcm/sct_config.py
> +             "where we create such views."),
Unfortunately, pre-commit is requiring this indentation

2025-01-20 17:33 UTC, piodul approved these changes

2025-01-21 09:21 UTC, piodul commented
@fruch @vponomaryov please re-review - we need this to unblock https://github.com/scylladb/scylladb/pull/22217, which is required for 2025.1

2025-01-21 19:28 UTC, fruch approved these changes
LGTM

2025-01-21 19:30 UTC, fruch commented on configurations/enable_views_with_tablets_on_upgrade.yaml
nothing is using this one, it's for doing things manual ? 

do we want to leave a job that is using this ?

2025-01-21 19:31 UTC, merged

2025-01-21 21:28 UTC, Annamikhlin commented
`artifacts-centos9-test` - https://jenkins.scylladb.com/job/releng-testing/job/artifacts/job/artifacts-centos9-test/87/
 `artifacts-rocky8-test` - https://jenkins.scylladb.com/job/releng-testing/job/artifacts/job/artifacts-rocky8-test/88/

failed with error:
```
p:ERROR >     if 'views-with-tablets' not in self.get('experimental_features', []):
p:ERROR > TypeError: SCTConfiguration.get() takes 2 positional arguments but 3 were given
21:42:00  ERROR: script returned exit code 1
```
@wmitros / @fruch - could you please take a look? it's preventing from next to pass

2025-01-21 22:22 UTC, wmitros commented
> `artifacts-centos9-test` - https://jenkins.scylladb.com/job/releng-testing/job/artifacts/job/artifacts-centos9-test/87/ `artifacts-rocky8-test` - https://jenkins.scylladb.com/job/releng-testing/job/artifacts/job/artifacts-rocky8-test/88/
> 
> failed with error:
> 
> ```
> p:ERROR >     if 'views-with-tablets' not in self.get('experimental_features', []):
> p:ERROR > TypeError: SCTConfiguration.get() takes 2 positional arguments but 3 were given
> 21:42:00  ERROR: script returned exit code 1
> ```
> 
> @wmitros / @fruch - could you please take a look? it's preventing from next to pass

I posted https://github.com/scylladb/scylla-cluster-tests/pull/9894, I'm surprised this wasn't caught by CI

2025-01-21 22:26 UTC, fruch commented
> > `artifacts-centos9-test` - https://jenkins.scylladb.com/job/releng-testing/job/artifacts/job/artifacts-centos9-test/87/ `artifacts-rocky8-test` - https://jenkins.scylladb.com/job/releng-testing/job/artifacts/job/artifacts-rocky8-test/88/
> > failed with error:
> > ```
> > p:ERROR >     if 'views-with-tablets' not in self.get('experimental_features', []):
> > p:ERROR > TypeError: SCTConfiguration.get() takes 2 positional arguments but 3 were given
> > 21:42:00  ERROR: script returned exit code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @wmitros / @fruch - could you please take a look? it's preventing from next to pass
> 
> I posted #9894, I'm surprised this wasn't caught by CI

you beat me in few minutes,

I've posted a fix as well (but with a unittest)
https://github.com/scylladb/scylla-cluster-tests/pull/9895

2025-01-21 22:30 UTC, fruch commented
@wmitros 

CI unittest test didn't cover it, cause it's a new functionality that was added 

other test even if we would have run them (integration, or longevity) might miss that if we were running it with anything but master (CI doesn't run with master by default, it run with older releases)

2025-01-21 22:36 UTC, wmitros commented
> > > @wmitros / @fruch - could you please take a look? it's preventing from next to pass
> > 
> > 
> > I posted #9894, I'm surprised this wasn't caught by CI
> 
> you beat me in few minutes,
> 
> I've posted a fix as well (but with a unittest) #9895

Adding a unittest seems useful, so I'll close mine