node_exporter: upgrade to v1.8.2, remove unneeded collectors
scylladb/scylla-cluster-tests pull request #9621
Opened 2024-12-26 08:50 UTC by mykaul

This PR update node_exporter to v1.8.2 (just like Scylla) and removes the unneeded collectors that are enabled by default (just like Scylla). The only exception is interrupts - which are still enabled by default by Scylla and are not needed here.

### Testing
- NOT tested.

### PR pre-checks (self review)

- [x] I added the relevant `backport` labels
- [x] I didn't leave commented-out/debugging code

2024-12-26 09:25 UTC, mykaul commented
Unsure why CI failed:
![image](https://github.com/user-attachments/assets/3f32a838-65bb-4a50-a246-581a33f2bb47)

2024-12-27 07:37 UTC, soyacz commented
it failed on precommit (visible in GH checks), more specifically commit lint. We follow a structured tilte: `<feature | fix | improvement>(<area>): <message>` and commit message must be long enough.

2024-12-29 10:27 UTC, mykaul commented
> it failed on precommit (visible in GH checks), more specifically commit lint. We follow a structured tilte: `<feature | fix | improvement>(<area>): <message>` and commit message must be long enough.

It's not mentioned @ https://github.com/scylladb/scylla-cluster-tests?tab=readme-ov-file#contribution-instructions , but I'll fix...

2024-12-30 08:18 UTC, soyacz commented
Still failing on precommit due `body's lines must not be longer than 120 characters [body-max-line-length]`
best to install pre-commit hooks that will validate locally so no need to wait for CI.

2025-01-07 19:19 UTC, fruch commented
I've fixed the commit message, AWS provision test passed

2025-01-07 19:19 UTC, fruch approved these changes
LGTM

2025-01-07 19:21 UTC, fruch requested changes
waiting for provision test to pass

2025-01-08 08:54 UTC, soyacz approved these changes
LGTM

2025-01-09 09:34 UTC, fruch approved these changes

2025-01-09 09:34 UTC, merged